feat: add PEP 621 config only
pypa/packaging.python.org pull request #1031
Opened 2021-12-12 17:29 UTC by henryiii

This is a simpler, PEP 621 _only_ version of #1030. Might be ready to go this route, but this would be what I think we could do.

Also, I'd love to move this over to using pipx. That would really simplify the ending commands (building and publishing), and would remove the unix/windows split from everything except the first line, where pipx would be installed.

2021-12-21 20:40 UTC, brettcannon approved these changes

2021-12-21 20:40 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +(from the above) tha are specified dynamically instead of being listed in
```suggestion
(from the above) tha are specified dynamically during the building of your project instead of being listed in
```

2021-12-21 20:40 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +description to be dynamic.
```suggestion
the static :file:`pyproject.toml`. For example, Flit allows ``version`` and
``description`` to be dynamic.
```

2021-12-21 20:40 UTC, brettcannon commented
LGTM, but I don't manage this site. 😁

2021-12-21 20:47 UTC, henryiii commented
Maybe it was harder to notice because of the draft status? I took the draft off, maybe that would help.

2021-12-26 11:24 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +:pep:`621`: provides a standard way to define metadata. Flit is used below, but
This phrase says `Flit is used below`, but the example does not seem to contain any flit specific configuration (or `[tool.flit]` table)...

2021-12-26 11:30 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +here; the tutorial will assume you are using :ref:`Flit`, though any backend
Based on the discussions in #1030, should this mention flit in this way?

Maybe:

```rst
You can select a variety of backends that support :pep:`621` (e.g. :ref:`Flit`, :ref:`PDM`).
```

Also related to #1030, if the idea is to wait until at least some of the most used backends support PEP 621, maybe setuptools can be included here in the near future :)

2021-12-29 03:15 UTC, webknjaz reviewed
I agree that we need to wait for the setuptools PR to be complete. Also, I feel like there may be links on the internet pointing to this document in the context of setuptools that may become misleading. Not sure what we can do about that, though.

2021-12-29 21:31 UTC, bhrutledge requested changes
Echoing other comments here and in #1030, I appreciate the effort, but I think we should wait for https://github.com/pypa/setuptools/issues/2671. With that in mind, I'm wondering if someone could open a PR that updates this tutorial _as if_ setuptools had support for PEP 621. In addition to being proactive instead of reactive, it might serve as an additional validation of the work in setuptools.

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +here; the tutorial will assume you are using :ref:`Flit`, though any backend
I think it would be more helpful to make an explicit recommendation with a single config (i.e. no tabs), maybe with an indication that there are alternatives (which already exists in "Next steps"). I think many/most newcomers won't know what a build backend is, and will have no basis for choosing one. As written, I think this serves as an implicit recommendation of Flit, and per the conversation in #1030, I don't think that's desired at present.

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
>  --------------------
I think this should be a sub-heading of `Creating pyproject.toml`, since it's now part of that file.

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> -be required, but can be omitted with newer versions of setuptools and pip.
It will be very nice to remove the `setup.py`/`setup.cfg` complexity...eventually. 😉

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +:pep:`621`: provides a standard way to define metadata. Flit is used below, but
I don't think this paragraph (which needs copy-editing) is necessary, and it would be more helpful to have an overview of what metadata is used for.

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +  happy with a trove classifier too.
Given that there's a `LICENSE` file, it seems like it should be included in the example.

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +``description`` to be dynamic.
This feels a bit too sparse to be helpful to newcomers, and I don't think this is the place to go into depth. Maybe we could just indicate that there are kinds of metadata, and provide links to their specification?

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +here; the tutorial will assume you are using :ref:`Flit`, though any backend
I'm also hesitant to emphasize Flit and PDM because those tools have their own CLI's with many more useful features. It seems to me that they're not intended to be used in the manner presented in this tutorial, i.e. as one of several tools, and I think that could be confusing/misleading.

On the other hand, setuptools _is_ intended to be just the build backend, and its documentation aligns better with this tutorial.

2021-12-29 21:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +backends might have other expectations or settings.
I think this and and the addition below is another example where the implicit choice of a build backend adds potentially-confusing complexity to the tutorial.

2021-12-29 21:46 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +here; the tutorial will assume you are using :ref:`Flit`, though any backend
Flit-core is intended to be usable in this manner, with standards-compliant tools. It _also_ has a cli that bundles useful tooling with a simple spelling (heavily due to pre-dating things like PEP 660, also to provide an "easy" solution for users). The backend in PDM is likely less so, and is probably mostly intended to provide an all-in-one solution when using PDM. But you can use it this way.

2021-12-29 21:50 UTC, henryiii commented
I think having the tabs (with setuptools emphasized as the first tab) is probably fine - this is meant to be a general packaging tutorial, and for many users, Flit is likely a great way to get started, it's light and much faster than setuptools, and isn't struggling with the distutils drop like setuptools 60+ currently is. Having tabs indicates that this is a general tutorial rather than a specific, one tool only thing, and seems to be the direction we are moving. If we really can do the tutorial identically for each of at least setuptools and Flit (optionally PDM too), then I think that would be helpful for setuptools as well - it would provide motivation to make sure that custom `tool.setuptools` is not required for a basic, Python only package.

2021-12-29 21:51 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +  happy with a trove classifier too.
I was copying what was done before - maybe the current tutorial should be updated first to include the LICENSE?

2021-12-29 21:53 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +``description`` to be dynamic.
I felt having an idea of what to look for - say if you were writing an app and needed to know there's a `scripts` somewhere, was helpful (and it's a very basic, common-needs list already). Some new users will be coming from NPM or some other system, and this will be enough to help them know what to look for. That's my thought, anyway.

2021-12-29 21:56 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +backends might have other expectations or settings.
I think it helps keep it general to have 2-3 backends, and setuptools can always have a pure-setuptools tutorial. The fact PyPA has two backends already is really a nice reason to make this general, and with tabs, user's don't have to change over. Maybe I can hide the discussion inside the tab a bit. I'll try an updated version, and I'll pretend setuptools is compatible (good target for setuptools to try to achieve).

2021-12-30 19:39 UTC, henryiii commented
I've added setuptools, and tried to bundle any discussion about backends into the tabs. Someone reading the tutorial would just see setuptools unless they try to select a different tab.

PEP 621 configuration is now shown in the Scikit-HEP developer docs, BTW. No tabs there since we don't have those set up. https://scikit-hep.org/developer/pep621. The "regular" page there will become a binary (probably scikit-build) packing guide eventually.

2021-12-31 13:17 UTC, bhrutledge requested changes
Thanks for continuing to chip away at this, in spite of naysayers like myself. It's helpful to have something concrete to react to, and I'm optimistic that some collaboration will lead to a polished final version.

2021-12-31 13:17 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +  happy with a trove classifier too.
Probably, but that change would just be deleted by this PR, so I think it's fine to define `license` in this PR.

2021-12-31 13:17 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +``description`` to be dynamic.
Agreed re: leaving breadcrumbs for what other features. I don't think this block accomplishes that as well as it could; before merging this, I'd want to rewrite it.

2021-12-31 13:17 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +backends might have other expectations or settings.
I think this paragraph should be removed, since it's primarily about project layout, and this section is about metadata.

2021-12-31 13:17 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +configuration is stored in the ``[project]`` table.
Given the example, I think this is sufficient, but I think there's an opportunity to give a high-level overview of what package metadata is.

```suggestion
:pep:`621` provides a standard way to define package metadata in :file:`pyproject.toml`.
```

2021-12-31 14:09 UTC, takluyver commented on source/tutorials/packaging-projects.rst
> +        build-backend = "flit_core.buildapi"
Part of my aim with Flit was that - for packages which it's suitable for - the people developing/maintaining a package could use just one tool to work with it (install, development install, prepare & upload distributions). Pip roughly works as a single entry point for consuming packages other people have published, and it seems to be a common complaint that the tools for developing & publishing packages are fragmented.  Our standardisation efforts are making this worse in some ways - e.g. we now expect package maintainers to use `python -m build` and `pip` instead of `setup.py`. But obviously it's also good to have commands that work for any backend.

Maybe the logical next step is for something - a future version of Flit, or a new package - to work as a package-maintainer oriented CLI for build, twine and the relevant parts of pip, regardless of which build backend they use.

But I think we don't have quite enough experience of the 'PEP 517 world' to do that yet. We've got quite a few backends good for relatively simple packages, but we're still working out what backend features are important. And the really important question of how this all works for packages with serious build steps is largely unanswered - e.g. scipy is working on building with meson, but I don't think that's joined up with producing the Python packages yet.

2021-12-31 15:07 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "flit_core.buildapi"
A lot of these things didn't work when flit was written - editable installs only just recently were added[^1], and are still provisional. It well pre-dates PEP 621. Etc. So there was no way to use flit except by using the CLI to get an editable install. Etc. But those things are being fixed. There still may be specialized development related stuff specific to backends - that's fine, this is a general, introductory tutorial.

A _huge_ part of this PR is due to the reason for the tabs - _I want to clearly show this is general for any package_ - it's not a setuptools tutorial anymore, it's a PEP standards tutorial that multiple tools all support. I want to develop a PEP 517/621 backend for scikit-build, and I don't want to have to rewrite all of this material for it, I'd like it to be something people can get from packaging.python.org - I can focus on writing the parts specific to building. Same thing for SciPy's Meson project. This should also be useful for Whey and Trampolim. By clearly indicating this works on any PEP 621 backend, it makes it easier for PEP 621 backends, which we want to encourage.

There is totally room for a custom CLI for a system - in fact, with the loss of `setup.py <commands>`, even setuptools might be very tempted to add a CLI, who knows. But that's what the Flit/PDM/other documentation is for. `packaging.python.org` is the place for showing universal standards and recommended tools. We could mention that that exists, and link to the flit docs, but we should show the general tooling.

I think pipx solves this fragmentation problem, by the way. `pip run build`, `pip run twine`, etc. work beautifully anywhere pipx is installed, including GitHub Actions. My publish action looks the same regardless of the backend, in fact most of my GHA code doesn't change much for any backend - using pip, build, and twine via pipx. If people just used pipx more, the need for a custom CLI for publishing and building might just go away.

[^1]: I was _almost_ going to say I've used flit-core for years and never installed flit, but I realized I have used it for editable installs. I've never used it for publish or building, though, and the init at least used to produce non-PEP 621 pyproject's, and it doesn't set up any of the extra stuff I'd consider essential for a good Python package, so I have a cookie cutter for that (scikit-hep/cookie supports 7 backends including Flit & PDM). I don't think the packages in the PyPA that are planning on switching (like packaging) are interested in moving all the tooling over to flit commands, but are rather looking for a light-weight reproducible build system to use wit h the existing GHA publish action, pip, nox/tox, build, etc. The fact there's no chicken-and-egg problem with flit-core being self-contained might get wheel to switch, too. ;)

2021-12-31 15:10 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "flit_core.buildapi"
One of the really fantastic things about PDM, by the way, is that due to PEP 621, it can use any PEP 621 backend, and it reads the same metadata for its own package locking use. So you can use flit-core with PDM, or trampolim, or whey. It's fantastic, and shows what having a standard can provide. And I think this is exactly the place to teach those standards, in a non-tool specific way.

And yes, you can use pdm publish to publish a flit package. Etc.

2021-12-31 15:31 UTC, takluyver commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
I definitely agree with this. There is real value in the abstractions we've developed to separate backends and frontends, but it's absolutely *not* helpful for beginners. An introductory tutorial on how to package your code is entirely the wrong place to start explaining abstraction layers or how to pick between different backends. The tutorial should present people with as few choices as possible, and give them one simple path to achieve something concrete. Leave the explanations and options for somewhere else.

This goes doubly where a new user doesn't have any sensible way to choose. Setuptools has 'many options' - what options? Do I care about those options? Flit is '10x faster' - probably a meaningless number, but even if it wasn't, packaging a project in 1 second vs 0.1 seconds doesn't matter much. PDM 'has some features not present in Flit'.... what features?! About the only concrete bit of information is that Flit is for 'pure Python' projects, and I don't know how clear that term is to newcomers. Other than that, the information provided is pretty much useless to the people this tutorial is aimed at.

But even if you could find a way to usefully describe the strengths of each of these backends in a sentence or two (which I suspect is impossible), I still think it's the wrong approach for a tutorial. It should be telling users 'here's a sensible default which is likely to work for you', not 'here are three possible options for you to think about before you continue'. A tutorial should only force readers to choose where there's no reasonable default that will work for most projects.

2021-12-31 15:59 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
How is this worse that the setup.py/setup.cfg tabbed selection we have there today? I don't think this tutorial is intended to be so simple that it can't prepare users who might need more soon. The reason for setup.py was to allow users to do more creative things that an absolute beginner might not need. That's where the tabs are useful - you don't need to change them if you don't want to, and any one of the tabs works identically from the user's perspective. I think it helps solidify the tutorial as general, not tool specific, and it helps keep setuptools's target configuration simple - if this was setuptools specific, then I can almost promise that a `[tool.setuptools]` section will end up being added / required, especially for package discovery or src folders. And it's simpler than what we have today, by quite a bit, even with the tabs.

Nothing later changes, no options are different (unlike setup.py/setup.cfg). I can clean up the references to other tools that @bhrutledge found later. But I like the tabs. Does no one else? @brettcannon @pradyunsg @webknjaz?

Also, if this is only "super simple" for entering users and doesn't have any choice, why would it use the slower, more powerful setuptools over Flit, by your own reasoning? Currently, Flit seems more likely to work reliably, actually, since it's self contained, while setuptools is fighting over the vending of distutils breaking things, besides being faster.

2021-12-31 16:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
I completely agree with @takluyver's agreement. 😉 

> How is this worse that the setup.py/setup.cfg tabbed selection we have there today?

Personally, I'd prefer only showing `setup.cfg`, but given the prevalance of `setup.py` in other docs/blogs/tutorials, and the similar names, I think the current tabs have some value. They're also different ways of configuring the same tool. In this PR, the tabs show configuring different tools in the same way.

> Also, if this is only "super simple" for entering users and doesn't have any choice, why would it use the slower, more powerful setuptools over Flit, by your own reasoning?

I believe @takluyver addressed this in https://github.com/pypa/packaging.python.org/pull/1030#issuecomment-991876540.

FWIW, I'm not a setuptools evangelist. If there was some sort of consensus around recommending `flit_core` as the backend, I'd be on board. That said, I appreciate the legacy of setuptools, the ongoing efforts to improve it (esp. the docs), and its flexibility. It seems to follow the the "batteries included" ethos of Python and Django, i.e. it's not the fastest or the simplest, but it works well for simple and complex use cases.

2021-12-31 16:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
Also, from a maintainer's perspective, I can imagine this will complicate troubleshooting on https://github.com/pypa/packaging-problems, because error messages could vary based on the chosen backend. It also just gives us more to keep updated, and raises the question of "Why just Setuptools/Flit/PDM, but not Whey/Trampolim/etc.?"

2021-12-31 16:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +        build-backend = "flit_core.buildapi"
> A _huge_ part of this PR is due to the reason for the tabs - _I want to clearly show this is general for any package_ - it's not a setuptools tutorial anymore, it's a PEP standards tutorial that multiple tools all support.
> 
> I want to develop a PEP 517/621 backend for scikit-build, and I don't want to have to rewrite all of this material for it, I'd like it to be something people can get from packaging.python.org.

I think we may have different ideas about the scope of this tutorial. As I wrote earlier, I've seen it's main value to be going from knowing nothing about Python packaging to having a published package. It accomplishes that by moving in a straight line, introducing key concepts, files, and tools along the way.

The tutorial is _not_ general for any package. For example, it doesn't cover applications. The intro even states "This tutorial uses a simple project named `example_package`. We recommend following this tutorial as-is using this project, before packaging your own project."

> By clearly indicating this works on any PEP 621 backend, it makes it easier for PEP 621 backends, which we want to encourage.

I think we can indicate that while still limiting the example configuration to a single tool.

2021-12-31 17:57 UTC, takluyver commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
> How is this worse that the setup.py/setup.cfg tabbed selection we have there today?

I'm repeating what @bhrutledge already said, but I already don't particularly like this for a tutorial. I can see why it's like that, and I think it does a reasonable job of explaining how to make the choice (basically: use `setup.cfg` if you can). I think the tutorial should aim to minimise the choices it presents to users, but you can make an argument that setup.cfg vs setup.py is something we can't really hide at the moment. Presenting one choice doesn't justify presenting more.

> Also, if this is only "super simple" for entering users and doesn't have any choice, why would it use the slower, more powerful setuptools over Flit, by your own reasoning? Currently, Flit seems more likely to work reliably

I'm torn over this. I don't think the speed difference is very important, but Flit is designed to be simple and reliable, and as far as possible to offer 'one way to do it'. I can certainly see (and be flattered by :-) the argument that Flit should be the default recommendation.

As I mentioned on #1030, a large part of my argument against recommending it by default is basically selfish: I don't want the support burden of maintaining the default tool for making Python packages, or the expectations that come with any hint that it's the 'official' tool (see also pipenv).

More objectively, though, I think that part of why Flit can be simple & reliable is that it's never aimed to cover every use case, so it benefits hugely from the 80/20 rule. I'm not sure that's viable for a tool that's the default recommendation. People might understand for a big feature like extension modules, but e.g. the people who want to get the version number from a git tag are really convinced that that is the one true way, and that Flit is outright wrong to not support it. I think you could easily find 5-10 'small' features like that, and either throw away the simplicity by supporting them, or frustrate a substantial fraction of users by refusing. I think an opt-in alternative tool can be simple in a way that it's very hard for the default tool to be. :shrug:

2022-01-01 02:42 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "flit_core.buildapi"
> The tutorial is not general for any package. For example, it doesn't cover applications.

I meant general for any backend package that follows PEP 621, not for user packages, sorry for the poor usage of "package" there. If you want to work with setuptools, flit, or PDM, you can use this tutorial to get started. Having a single tab box here would formalize that, and make it nice and visual, without distracting too much from the tutorial - much less than the current setup.cfg/setup.py split. Hopefully, Poetry, as well as Scikit-build and Meson and others in the future. The point of PEP 621 was to generalize configuration so it just doesn't matter what tool you use for basics - you can pick a tool based on the advanced features, like git version support, etc.

2022-01-01 02:51 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
I feel like there are two competing arguments - one is that this is is targeting simple, basic users who do not need to be exposed to more complex configuration (though selecting a backend is not that complex) - those sorts of users would be clearly in the 80%, and would be much better off with Flit. The other is that this is the "recommended default" for everyone, and that should be setuptools, since it's powerful _later_ - that's why the old tutorial didn't remove setup.py - it was to help users transition to power usage. I think by providing a little bit of choice here, it provides a similar effect, with a much lower cost - you don't need to learn a different configuration language, or anything like that.

I just want a single tabbed box, with at least setuptools and flit (and maybe PDM), to graphically illustrate that this works with multiple PEP 621 backends, and is not a "setuptools" tutorial, but a "Python packaging" tutorial. This is part of why PEP 621 was written, IMO.

> pypa/packaging-problems ... "Why just Setuptools/Flit/PDM, but not Whey/Trampolim/etc.?"

Setuptools and Flit are in the PyPA, so the maintainers are part of packaging-problems. PDM isn't, but it's lead maintainer is also in the PyPA. We could just reduce it to setuptools and Flit though. (Technically, Trampolim is maintained entirely by PyPA members too, but it's a bit more experimental at the moment, I think - and it also requires src configuration for this).

2022-01-01 03:13 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
If we just say "and others work", beginning user's won't have a clue as to how to enable them. If we have tabs, then it will clearly, visually show how you change. We _could_ say "the rest of this tutorial will assume setuptools" or something like that, but I'd much rather keep it general, but it's better than completely removing the visual example of how you pick a backend.

2022-01-01 15:12 UTC, takluyver commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
I started typing a different reply, but perhaps a more useful way to frame my argument is this:

Once setuptools supports PEP 621 (assuming it will at some point), is there any particular reason someone reading this tutorial should consider using Flit instead of Setuptools?

- You mention Flit is faster, but I think Setuptools is comfortably fast *enough* for most use cases, so this isn't a compelling argument by itself.
- Setuptools supports a bunch of things that Flit doesn't and won't.
- Some of the main convenience features Flit had when it launched are now in Setuptools as well, like reading the version from a module and including package data automatically. You have to opt into them with Setuptools, but the tutorial could tell you to do that.
- Flit is simpler because it doesn't have to support all the history & legacy that Setuptools does - but the other side of the coin is that Setuptools is thoroughly battle tested, and there's a wealth of examples for everything you want to do.

I'll probably keep using Flit, because I know it inside out and it fits what I want from a packaging tool (of course it does :wink: ). But once you can use setuptools with a `[project]` table in a pyproject.toml file, I'm not sure even I will push people to consider Flit instead. If the legacy of Flit is that it's helped us figure out a load of standards which then let people do more interesting things - like Poetry, or your own proposal for revamping scikit-build - that's ultimately more important than having loads of people using Flit itself.

2022-03-15 01:34 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +    This is the classic backend for building projects; large, slow, complex.
If a user cares about things like built-in support for C-extensions or plugins, then I think there are a bit past the target for this tutorial. The idea is to say "if you don't need anything special, something like flit or hatch will give you a simple, light-weight build with simpler error tracebacks, etc." It's not to say setuptools is "slow" (should reword), but it's slower (~5 seconds) than flit - you are paying for the ability to do complex and legacy things.

2022-03-15 09:59 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +    This is the classic backend for building projects; large, slow, complex.
Hi @henryiii thank you very much for your reply (also thank you very much for taking your time to work in this text, I am very sure it is going to help a lot of people).

> If a user cares about things like built-in support for C-extensions or plugins, then I think there are a bit past the target for this tutorial.

That is a very fair point, although we can discuss a bit about it[^1]. If you and the tutorial maintainers feel that it is not worthy to emphasize the good parts of setuptools in the tutorial because they are not relevant to the target audience, that is completely fine. I just would like to ask to please not use negative wording when referring to `setuptools`.

Saying that `setuptools` is slower than other backends is completely fair, because it is true (at least at present moment). However publishing this information devoid of context just contributes towards generating animosity against the package, and that in turn, generates a very shallow discussion in the community, which does not benefit anyone. I am sure this is not your intention here, but is a possible side effect of the proposed text.

> you are paying for the ability to do complex and legacy things.

For sure, if you start with setuptools, you are going to spend extra time waiting for your build to be complete, but also if at any point in time you need to add Cython, you might have an easier time[^2]... Since people may not be running the build process with a high frequency, that price may be perfectly reasonable (I would be surprised if a packaging novice builds the same package enough times in a short interval for the build velocity to be significant).

We can encourage users to think about the tradeoffs of different backends since moment zero, when they decide to publish a package. That is a fair approach. But then it would be nice if the discussion is more informative and complete. Alternatively we can go for a less opinionated approach.

[^1]: I think being a completely complete packaging novice does not imply that the user will not have the need or interest for plugins or other language extensions. I can think about 2 very likely situations:
    1. The user have been programming for a while in Python before they decide to publish their first package. At this point they might already be familiar with git, so using a plugin like `setuptools-scm` makes complete sense.
    2. The user is a complete Python beginner but they come from another language background like C/Go/Rust/Zig etc... A plugin system here makes perfect sense also.

[^2]: Considering that a significant part of the community [uses Python for data-science, ML, etc](https://www.jetbrains.com/lp/python-developers-survey-2020/), this hypothetical situation is not as outlandish it might seem at first...

2022-03-15 17:51 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +    This is the classic backend for building projects; large, slow, complex.
> That is a very fair point, although we can discuss a bit about it[1](#user-content-fn-1-f54f9d18cfa1ad9ea56666ceced74763). If you and the tutorial maintainers feel that it is not worthy to emphasize the good parts of setuptools in the tutorial because they are not relevant to the target audience, that is completely fine. I just would like to ask to please not use negative wording when referring to `setuptools`.

That seems like a reasonable request. If the need to motivate folks to consider other tools we can use positive wording for Flit and friends instead: fast, simple, straightforward. But probably saying _something_ as to why people should even consider a different tool than the one they see all the blog posts mention is probably warranted.

2022-03-15 18:21 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +    This is the classic backend for building projects; large, slow, complex.
Yes, I'm going to try to reword this to focus only on positive things for each, with the negative aspects implied by omission; flit could be be "small and lightweight", implying setuptools is not, etc. I think this should remain pretty small and lightweight (the description, not the packages!), since the primary point is to show it really doesn't matter what they pick, the material below is valid for all of them.

2022-03-15 18:31 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +    This is the classic backend for building projects; large, slow, complex.
Thank you very much @henryiii!
I really appreciate the understanding ❤️

2022-03-15 18:46 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
Setuptools takes 13 seconds to build a wheel and SDist via build, while Flit takes 8 seconds[^1]. That's much nicer user experience IMO for something that used to take 1-2 seconds before isolated builds. The error messages if something go wrong with Flit point at a 2K LoC codebase in fairly clean and modern Python, while Setuptools points at over 40K lines of code with many layers, distutils, etc. During the Distutils removal, Flit has been more stable, as well. If someone doesn't need C-extensions, special plugins, etc (which I assume is most of the users reading this tutorial), then yes, I think Flit (or Hatch, perhaps) is still a reasonable, if not better, beginner choice. It's completely trivial to move to setuptools when they both support the same PEP 621 configuration, so it seems quite reasonable to start on Flit until you need something more.

However, I've placed setuptools first in the current draft.

That's part of the point of this showing multiple backends - the backend just doesn't matter at this level. That's the point of PEP 621, and where packaging has been trying to move. We don't want to "force" the ecosystem to use a tool (setuptools or flit or anything else) anymore. Having a choice (even just setuptools/flit) makes it much easier for third parties not in the choices (like Scikit-Build when it adds PEP 621 support) to just point users here, rather than rewriting this tutorial with "scikit-build-core"[^2] inserted. It's completely obvious where the "scikit-build-core" part would go, since it's a tabbed selection already. If this was hardcoded to setuptools, it's a setuptools tutorial, not a generic one, and it's not easy for a non-expert[^3] user to read it and know what needs to change to use a different backend and what remains true regardless.

FYI, you can see an example of live at https://scikit-hep.org/developer/pep621.

[^1]: Might even go down in Python 3.11.
[^2]: Or meson or any other future or existing backend)
[^3]: Anyone who has not read PEP 517, 518, and 621

2022-03-15 18:50 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +    This is the classic backend for building projects; large, slow, complex.
FWIW, I originally left off the opinions entirely (like you see at https://scikit-hep.org/developer/pep621), but some reasoning here was requested. IMO, the main point here is it doesn't matter, the tutorial is the same regardless of which backend you choose. I expect most users will not click tabs and will just select whichever one is there by default, that is, first.

2022-03-24 16:57 UTC, flying-sheep commented on source/tutorials/packaging-projects.rst
> +should contain one of these build-system blocks:
I also think flit’s default of “package all that’s in git” is much better than “learn an arcade single purpose syntax and create a MANIFEST.in file from it”.

I think we should keep the choice and add tabs to the “[Including other files](https://python-packaging-user-guide--1031.org.readthedocs.build/en/1031/tutorials/packaging-projects/#including-other-files)” section.

Also it’s time to make `setup.py` (and `MANIFEST.in`) disappear from this guide :partying_face:

2022-05-10 14:26 UTC, henryiii commented
This now uses pypa/hatch's hatchling by @ofek as the first option, and is ready as far as I'm concerned.

2022-05-10 14:29 UTC, ofek commented
I'm fine with that, thanks for letting me know!

2022-05-11 22:33 UTC, brettcannon requested changes
LGTM, but I think we should avoid referencing PEPs and instead reference the specs to be a bit more future-proof.

2022-05-11 22:33 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +:file:`pyproject.toml` file should contain one of these build-system blocks:
Should we add a note saying to check with the tools' documentation for the most up-to-date snippet to include?

2022-05-11 22:33 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +The options allowed here are defined in :pep:`621`. In short, they are:
```suggestion
The options allowed here are defined in the :ref:`project metadata specification <declaring-project-metadata>`. In short, they are:
```

2022-05-11 22:33 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +- ``version`` is the package version. See :pep:`440` for more details on
```suggestion
- ``version`` is the package version. See the :ref:`version specifier specification <version-specifiers>` for more details on
```

2022-05-11 22:33 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +  There also is a more advanced table form described in :pep:`621`.
```suggestion
  There also is a more advanced table form described in the :ref:`project metadata specification <declaring-project-metadata>`.
```

2022-05-11 22:33 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +the above) tha are specified dynamically during the building of your project
```suggestion
the above) that are specified dynamically during the building of your project
```

2022-05-12 04:05 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +    support and many plugins, like :ref:`setuptools_scm`. EXPERIMENTAL.
```suggestion
    support and many plugins, like :ref:`setuptools_scm`.
```

The core support is not considered experimental anymore, just `tool.setuptools` is.

2022-05-12 04:11 UTC, henryiii commented
There was a discussion on the packaging discord about making the first option a placeholder, forcing a user to select a tab. This avoids "biasing" the reader to one backend (the first no-click one), but there was a good counter argument that this would detract a bit too much from the spirit of a tutorial. I think the current implementation is a good balance of concerns, providing a default but also an option that visually shows what part needs to change to select another backends, and providing motivation for a backend to "work out of the box" with this tutorial (this is one reason setuptools works without extra package configuration now!).

2022-05-12 04:13 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +:file:`pyproject.toml` file should contain one of these build-system blocks:
We are pretty general here, and we can update the snippet if it needs changing.

2022-05-12 09:41 UTC, bhrutledge commented
@henryiii Quick note to say thanks for moving this forward, and that I'm hoping to review it this weekend.

Where on the pypa discord is the discussion that you referenced?

2022-05-12 13:11 UTC, ofek commented
@bhrutledge #general

2022-05-12 13:12 UTC, henryiii commented
Starting on https://discord.com/channels/803025117553754132/803025117995073578/973526733947023400, slightly punctuated.

2022-05-12 14:07 UTC, ofek requested changes

2022-05-12 14:07 UTC, ofek commented on source/tutorials/packaging-projects.rst
> +  :ref:`hatch`, and :ref:`poetry`.
To match the ordering above

```suggestion
* Consider alternatives to :ref:`setuptools` such as :ref:`hatch`, :ref:`flit`,
  :ref:`pdm`, and :ref:`poetry`.
```

2022-05-12 20:36 UTC, brettcannon approved these changes

2022-05-13 04:40 UTC, henryiii commented
From a suggestion on Discord, I've made a PR - https://github.com/pradyunsg/sphinx-inline-tabs/pull/30; and if that goes in, then you'd be able to link to this page with a selected tab set(s) preset too, like `https://packaging.python.org/en/latest/tutorials/packaging-projects?tabs=Windows&tabs=Setuptools`.

2022-05-15 19:55 UTC, bhrutledge requested changes

2022-05-15 19:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +Setuptools; most backends that support :pep:`621` should work. Your
From what I can tell, this is the first mention of the word "backend", which to me assumes the reader will know what "backend" means. It also seems to imply familiarity with Hatchling, etc.

As others have expressed (in this PR and in the [Discord thread](https://discord.com/channels/803025117553754132/803025117995073578/974078958108807190)), I feel strongly that this tutorial should provide an unambiguous recommendation for build backend. I think it would be helpful to define what "backend" means, and indicate that there are alternatives (which is currently done in the "next steps" below), possibly with a link to separate article on pros/cons.

I have some of the same reservations about Hatchling being the recommendation [as I did for Flit](https://github.com/pypa/packaging.python.org/pull/1031#discussion_r777000444). From what I can tell, Hatchling has no documentation outside of the [Hatch documentation](https://hatch.pypa.io/latest), which (rightfully) focuses on using the `hatch` CLI instead of tools like `build` and `twine`. I imagine newcomers to packaging would find that confusing.

2022-05-15 19:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +    SCM versioning and plugins.
In general, I don't think these descriptions are sufficient for helping a reader choose a backend.

2022-05-15 19:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +:file:`pyproject.toml` file should contain one of these build-system blocks:
I think this speaks to the value of a single backend recommendation, i.e. more likely to be accurate, less to maintain.

2022-05-15 19:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +allows ``version`` and ``description`` to be dynamic.
My [earlier comment](https://github.com/pypa/packaging.python.org/pull/1031#discussion_r776496437) still stands:

> Agreed re: leaving breadcrumbs for other features. I don't think this block accomplishes that as well as it could; before merging this, I'd want to rewrite it.

Instead of a list of keywords, how about a paragraph that lists the kinds of things that can be configured (dependencies, command-line scripts, keywords), with a "learn more" link to an appropriate reference?

2022-05-15 19:55 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +:pep:`621` provides a standard way to define metadata in :file:`pyproject.toml`.
This is the second of three direct links to PEP 621, which @brettcannon [suggested we avoid](https://github.com/pypa/packaging.python.org/pull/1031#pullrequestreview-970065478), but was only changed in [one instance](https://github.com/pypa/packaging.python.org/pull/1031/files#diff-04bfc8bd25a83763d519bf1a6e9178b31618e941c4a8cda88438c7aa39940d79R197).

2022-05-15 20:16 UTC, ofek commented on source/tutorials/packaging-projects.rst
> +Setuptools; most backends that support :pep:`621` should work. Your
> From what I can tell, Hatchling has no documentation outside of the [Hatch documentation](https://hatch.pypa.io/latest), which (rightfully) focuses on using the hatch CLI instead of tools like build and twine. I imagine newcomers to packaging would find that confusing.

That's not at all a fair interpretation of the docs (unless you haven't read).

The very first thing says:

> Standardized [build system](https://hatch.pypa.io/latest/build/#packaging-ecosystem) with reproducible builds by default

the linked section's first line says:

> Hatch [complies](https://hatch.pypa.io/latest/config/build/#build-system) with modern Python packaging specs and therefore your projects can be used by other tools with Hatch serving as just the build backend.

that link show the PEP 517 configuration.

I literally don't how to make that more prominent 🙂 Any ideas?

2022-05-15 22:33 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +Setuptools; most backends that support :pep:`621` should work. Your
@ofek It's not my intention to disparage Hatch or its documentation; both are an impressive effort. It's true that I have not thoroughly read the docs. After taking a closer look, I found the [configuration section](https://hatch.pypa.io/latest/config/metadata/), which seems like a really helpful reference.

That said: putting myself in the shoes of a complete newcomer to packaging, having just gone through a tutorial that uses `build`, `twine`, and `venv`, I think I would find it confusing to go to Hatch's documentation and be presented with an entirely different command-line tool, and I might find it difficult to determine what I can configure without also having to adopt that tool.

Beyond that, given setuptools has been the recommendation for so long, I don't feel comfortable changing that recommendation based solely on the discussion in this PR and on Discord. I'm concerned that if we change the recommendation, long-time packaging folks will disagree. But I'm just one (relatively new and limited) maintainer of this project, and I honestly don't know how to resolve this. Maybe a discussion/vote on [packaging forum](https://discuss.python.org/c/packaging/14) and/or the [pypa-committers list](https://mail.python.org/archives/list/pypa-committers@python.org/)?

Thanks for being patient with me. I'm invested in the utility of this tutorial, since it was my introduction to Python packaging at PyCon 2019, and I've put a decent amount of time into improving it. And, FWIW, I'm very much looking forward to a future without `setup.cfg`.

2022-05-15 23:06 UTC, ofek commented on source/tutorials/packaging-projects.rst
> +Setuptools; most backends that support :pep:`621` should work. Your
> I think I would find it confusing to go to Hatch's documentation and be presented with an entirely different command-line tool

That would be true of the main page of any tool that offers a CLI. You'd have to link to the relevant page(s):

- https://hatch.pypa.io/latest/config/metadata/
- https://hatch.pypa.io/latest/config/dependency/
- https://hatch.pypa.io/latest/config/build/

2022-05-16 03:48 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +:file:`pyproject.toml` file should contain one of these build-system blocks:
If this is just a setuptools tutorial, why not just replace the whole page with a link to setuptools, and put the tutorial there? I feel part of the point of a general "packaging" tutorial is to have a general tutorial. This was not possible before PEP 621 & 517, so it had to be setuptools, but now it is. We even have three valid backends in the PyPA, shouldn't they be represented here?

2022-05-16 04:31 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +Setuptools; most backends that support :pep:`621` should work. Your
> As others have expressed (in this PR and in the [Discord thread](https://discord.com/channels/803025117553754132/803025117995073578/974078958108807190)),

Others here and in the Discord thread have also expressed support for keeping this general - in fact there was support for an even more extreme version of this, where the default tab would be "please select a backend" to avoid putting one of the backends as "recommended" - since most users will not bother to change tabs - they will see the first tab as "recommended" unless they are actively looking for options - or coming in from a link from a different backend, where the tabs will help illustrate exactly what part of the tutorial is backend specific (which is why I like the tabs).

I think the current system is a nice balance of both sides, providing a small amount of unobtrusive choice, but not forcing the reader to make a choice. I'd recommend others weigh in, though!

Which backend should be the "only" backend? `tools.setuptools` is still experimental and there are a lot of older pre-PEP 621 copies of it around, and it's large and full of legacy cruft still, causing slower builds and harder error messages - it can be powerful, but it seems to be an overkill for newcomers and simple Python only projects. Flit is lite and fast, with simple error messages, but a crippled file include/exclude system that won't include `LICENSE.md` by default but will include `__pycache__` folders. Hatchling seems to be a nice balance, with reasonable defaults & nice error messages. For a nice newcomer experience, I think Hatchling is likely best.

2022-05-16 04:35 UTC, henryiii commented
Timing and output tests:

Setuptools takes 14.5 seconds (10.5 seconds with `build[virtualenv]`) and produces a lot of beginner unfriendly output.

<details><summary>Setuptools output (click to expand)</summary>

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=61.0)
* Getting dependencies for sdist...
/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-f9wdxp_e/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
running egg_info
creating src/package.egg-info
writing src/package.egg-info/PKG-INFO
writing dependency_links to src/package.egg-info/dependency_links.txt
writing requirements to src/package.egg-info/requires.txt
writing top-level names to src/package.egg-info/top_level.txt
writing manifest file 'src/package.egg-info/SOURCES.txt'
reading manifest file 'src/package.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/package.egg-info/SOURCES.txt'
* Building sdist...
/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-f9wdxp_e/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
running sdist
running egg_info
writing src/package.egg-info/PKG-INFO
writing dependency_links to src/package.egg-info/dependency_links.txt
writing requirements to src/package.egg-info/requires.txt
writing top-level names to src/package.egg-info/top_level.txt
reading manifest file 'src/package.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/package.egg-info/SOURCES.txt'
running check
creating package-0.1.0
creating package-0.1.0/src
creating package-0.1.0/src/package
creating package-0.1.0/src/package.egg-info
copying files to package-0.1.0...
copying LICENSE -> package-0.1.0
copying README.md -> package-0.1.0
copying pyproject.toml -> package-0.1.0
copying src/package/__init__.py -> package-0.1.0/src/package
copying src/package.egg-info/PKG-INFO -> package-0.1.0/src/package.egg-info
copying src/package.egg-info/SOURCES.txt -> package-0.1.0/src/package.egg-info
copying src/package.egg-info/dependency_links.txt -> package-0.1.0/src/package.egg-info
copying src/package.egg-info/requires.txt -> package-0.1.0/src/package.egg-info
copying src/package.egg-info/top_level.txt -> package-0.1.0/src/package.egg-info
Writing package-0.1.0/setup.cfg
Creating tar archive
removing 'package-0.1.0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=61.0)
* Getting dependencies for wheel...
/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-_ogaifzn/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
running egg_info
writing src/package.egg-info/PKG-INFO
writing dependency_links to src/package.egg-info/dependency_links.txt
writing requirements to src/package.egg-info/requires.txt
writing top-level names to src/package.egg-info/top_level.txt
reading manifest file 'src/package.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/package.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-_ogaifzn/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/package
copying src/package/__init__.py -> build/lib/package
running egg_info
writing src/package.egg-info/PKG-INFO
writing dependency_links to src/package.egg-info/dependency_links.txt
writing requirements to src/package.egg-info/requires.txt
writing top-level names to src/package.egg-info/top_level.txt
reading manifest file 'src/package.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/package.egg-info/SOURCES.txt'
installing to build/bdist.macosx-12-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-12-x86_64
creating build/bdist.macosx-12-x86_64/wheel
creating build/bdist.macosx-12-x86_64/wheel/package
copying build/lib/package/__init__.py -> build/bdist.macosx-12-x86_64/wheel/package
running install_egg_info
Copying src/package.egg-info to build/bdist.macosx-12-x86_64/wheel/package-0.1.0-py3.10.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.macosx-12-x86_64/wheel/package-0.1.0.dist-info/WHEEL
creating '/Users/henryschreiner/git/webpages/packaging.python.org/tmp1/package/dist/tmp06ix4v9l/package-0.1.0-py3-none-any.whl' and adding 'build/bdist.macosx-12-x86_64/wheel' to it
adding 'package/__init__.py'
adding 'package-0.1.0.dist-info/LICENSE'
adding 'package-0.1.0.dist-info/METADATA'
adding 'package-0.1.0.dist-info/WHEEL'
adding 'package-0.1.0.dist-info/top_level.txt'
adding 'package-0.1.0.dist-info/RECORD'
removing build/bdist.macosx-12-x86_64/wheel
Successfully built package-0.1.0.tar.gz and package-0.1.0-py3-none-any.whl

________________________________________________________
Executed in   14.51 secs    fish           external
   usr time   12.16 secs    0.09 millis   12.16 secs
   sys time    1.94 secs    1.51 millis    1.94 secs
```

</details>

Hatchling takes 10.7 seconds (4.9 seconds with `build[virtualenv]`) and produces no unnecessary output. Most of the time is environment creation.

<details><summary>Hatchling output (click to expand)</summary>

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchling>=0.7)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchling>=0.7)
* Getting dependencies for wheel...
* Building wheel...
Successfully built package-0.1.0.tar.gz and package-0.1.0-py3-none-any.whl

________________________________________________________
Executed in   10.69 secs    fish           external
   usr time    7.80 secs    0.12 millis    7.80 secs
   sys time    1.69 secs    1.90 millis    1.69 secs
```

</details>

Takes 9 seconds (3.6 seconds with `build[virtualenv]` and produces no unnecessary output.

<details><summary>Flit output  (click to expand)</summary>

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (flit_core >=3.4)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (flit_core >=3.4)
* Getting dependencies for wheel...
* Building wheel...
Successfully built package-0.1.0.tar.gz and package-0.1.0-py3-none-any.whl

________________________________________________________
Executed in    9.00 secs    fish           external
   usr time    7.23 secs    0.11 millis    7.23 secs
   sys time    1.60 secs    1.95 millis    1.60 secs
```

</details>

Pdm-PEP517 takes 9.6 seconds (4.5 seconds with `build[virtualenv]`) and produces some extra output, much less than setuptools but more than the others.

<details><summary>pdm-pep517 output (click to expand)</summary>

```
* Creating venv isolated environ [...]

2022-05-16 04:38 UTC, henryiii commented
I also tried an error test for all backends. I set the version to `0..0` to see what they produced. IMO for CLI design, by the way, this should not be a traceback at all. It's a known error, it should print a known error and quit. But I think we are stuck with this as the mechanism PEP 517 build backends communicate errors to build/pip.

Setuptools had a very descriptive error... But at the _top_ of the traceback, not the bottom! I wonder if this could be improved with `add_note` in Python 3.11?

<details><summary>Setupools output (click to expand)</summary>

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=61.0)
* Getting dependencies for sdist...
/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
configuration error: `project.version` must be pep440
DESCRIPTION:
    The version of the project as supported by :pep:`440`.

GIVEN VALUE:
    "0..0"

OFFENDING RULE: 'format'

DEFINITION:
    {
        "type": "string",
        "format": "pep440"
    }
Traceback (most recent call last):
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 297, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/build_meta.py", line 181, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
[build-system]
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 122, in setup
    dist.parse_config_files()
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/dist.py", line 864, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 54, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 120, in read_configuration
    validate(subset, filepath)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-3sv0istq/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 43, in validate
    raise error from None
ValueError: invalid pyproject.toml config: `project.version`

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
```

</details>

Hatchling has a better message in the traecback, simple and to the point, though the least descriptive. You can see the much simpler design in the depth of the traceback, as well.

<details><summary>Hatchling output (click to expand)</summary>

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchling>=0.7)
* Getting dependencies for sdist...
* Building sdist...
Traceback (most recent call last):
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
[build-system]
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 314, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-cu1g1ijq/lib/python3.10/site-packages/hatchling/build.py", line 21, in build_sdist
    return os.path.basename(next(builder.build(sdist_directory, ['standard'])))
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-cu1g1ijq/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 146, in build
    artifact = version_api[version](directory, **build_data)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-cu1g1ijq/lib/python3.10/site-packages/hatchling/builders/sdist.py", line 133, in build_standard
    with SdistArchive(self.project_id, self.config.reproducible) as archive:
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-cu1g1ijq/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 347, in project_id
    self.metadata.version,
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-cu1g1ijq/lib/python3.10/site-packages/hatchling/metadata/core.py", line 64, in version
    self._set_version()
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-cu1g1ijq/lib/python3.10/site-packages/hatchling/metadata/core.py", line 161, in _set_version
    self._version = str(Version(version))
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-cu1g1ijq/lib/python3.10/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0..0'

ERROR Backend subproccess exited when trying to invoke build_sdist
```
</details>

Flit has the best message in the traecback, describing that the version number doesn't match PEP 440 rules, which is a nice touch. You can also see the simplest traceback, a tiny bit shorter than Hatchling, though not much.

<details><summary>Flit output (click to expand)</summary>


```
* Creating venv isolated environment...
* Installing packages in isolated environment... (flit_core >=3.4)
* Getting dependencies for sdist...
Traceback (most recent call last):
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/henryschreiner/.local/pipx/.cache/ccf0646f0626594/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 297, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/build-env-1iazo15g/lib/python3.10/site-packages/flit_core/buildapi.py [...]

2022-05-16 04:49 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +Setuptools; most backends that support :pep:`621` should work. Your
Also, RE docs: This is a problem with all the backends - almost everyone with a PEP 517 backend is pushing their own command line tool[^1] - Flit, PDM, Hatch, Poetry, etc. The only one doing this right is Setuptools, actually! I would really like to see a modern pure PEP 517 backend that wasn't tool specific. PEP 621 has enabled this - PDM can be used with any backend, and I think Hatch can too. I'd love to see Flit and Poetry join - you shouldn't need to pick the "blessed" backend of a tool to use that tool. Then maybe the backends will merge into a couple of standard ones (ultra-simple no-dependency like Flit-core and full-features like Hatchling), and Poetry/PDM/Hatch/Flit project will all use one of those two backends. I can dream, at least. :)

Maybe it would be nice if Hatchling and Hatch separated a bit, with Hatching's docs being distinct from Hatch (they already have distinct release numbers - maybe could even be two repos?). They could be cross linked, but one is on "how to configure your build", the other is on "how to configure your environment"s. Maybe Hatch could include an example of using a different build backend, too, like flit-core or setuptools. I don't know, just a thought.

2022-05-16 05:10 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +    SCM versioning and plugins.
Hmm, I have an idea. Maybe making it clear that the tutorial is intended for whatever backend comes first, but then mentioning something like "the concepts in this tutorial hold for other backends too; you can select these other backends and more"?

The point of the box is to show this is general for all packaging, not tied to one tool, and to allow other tools (like the upcoming-but-not-very-soon Poetry 2.0 PEP 621 support) to just point at this page; readers coming in from a packaging backend will know exactly what needs to be customized and what is universally applicable with the tabs. That's why I like the tabs, and why I am so set on "packaging.python.org" not forcing one tool only - even if it "choses" a tool for the tutorial, I want it to be clear it's not "only" - tabs are a great graphical way to do that. But it's fine if the page makes it clear that a reader is not required to "pick".

One idea that I like less is to add a bit of JS to the page allowing a link to control the (not tabbed) backend. So you could link to this page with `?requires="hatchling>=0.7"&build-backend=hatchling.build` appended and it would display that backend. This doesn't show a reader what part can be changed, but does still fulfill the requirement that this becomes more useful than just a one-package tutorial. I prefer my idea above, though.

2022-05-16 05:14 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +allows ``version`` and ``description`` to be dynamic.
I'll try this soon, along with some other suggested updates. ~~Though I think the itemized summary gives a user a quick idea of exactly what is possible - most things are named well, so if a user is looking for~~ I just reread the list, and I don't think that's true for anything other than `maintainers`. Okay.

2022-05-18 00:29 UTC, ofek commented
@henryiii Can you please retry with Hatchling v1.0.0?

2022-05-31 10:40 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +Setuptools; most backends that support :pep:`621` should work. Your
In an attempt to get more feedback, I've started [a discussion on the packaging forum](https://discuss.python.org/t/removing-setup-cfg-and-setup-py-from-the-packaging-tutorial/16096).

2022-06-03 01:14 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +:pep:`621` provides a standard way to define metadata in :file:`pyproject.toml`.
What would the alternative be? The worst offender is "most backends that support PEP 621 should work.". `pyproject.toml` isn't correct; tools like Poetry and Enscons don't support PEP 621; it's hard to say "most" and exclude Poetry. Maybe "most backends that support the `project` table"?

2022-06-03 02:31 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +:pep:`621` provides a standard way to define metadata in :file:`pyproject.toml`.
Attempted something; there now is no mention of "621".

2022-06-03 02:32 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +allows ``version`` and ``description`` to be dynamic.
Attempted a paragraph form, and removed `license`, `optional-dependencies`, and moved `maintainers` to a mention in `authors`.

2022-06-03 20:34 UTC, ofek approved these changes
Great improvement 👏

2022-06-03 21:01 UTC, eli-schwartz commented on source/tutorials/packaging-projects.rst
> +        build-backend = "flit_core.buildapi"
> But I think we don't have quite enough experience of the 'PEP 517 world' to do that yet. We've got quite a few backends good for relatively simple packages, but we're still working out what backend features are important. And the really important question of how this all works for packages with serious build steps is largely unanswered - e.g. scipy is working on building with meson, but I don't think that's joined up with producing the Python packages yet.

Just last week, SciPy merged the change to default the pyproject.toml backend to Meson (via https://pypi.org/project/meson-python/) instead of setuptools. The Python wheels are now pure Meson in the lead-up to SciPy 1.9.0; maybe answers are forthcoming. :)

2022-06-03 21:04 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "flit_core.buildapi"
Expect news on https://iscinumpy.dev/post/scikit-build-proposal/ in the near future as well. ;)

2022-06-03 21:31 UTC, brettcannon commented on source/tutorials/packaging-projects.rst
> +:pep:`621` provides a standard way to define metadata in :file:`pyproject.toml`.
The change WFM!

2022-06-03 21:55 UTC, ezio-melotti commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
In the [rendered version](https://python-packaging-user-guide--1031.org.readthedocs.build/en/1031/tutorials/packaging-projects/#creating-pyproject-toml), I noticed that unlike all other tabs that only change the code block, this set of tabs include changes to both the text and the code, with no visual indication about where the tab content ends (this might be a problem with the Sphinx theme though).

I think it would be better to:
* have a bullet list with the 4 paragraphs (as a user I would be interested in reading about all 4)
* after the list add the tabs with the 4 code blocks (I don't need to see them all unless I'm comparing them)

This change will also make the behavior of the tabs more consistent with the rest of the page.

2022-06-04 13:45 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
There was significant worry that making the choice too large a part of the tutorial would "scare off" people trying to complete the tutorial. Having everything inside the tab was one way to avoid keeping this opt-in - a reader only is exposed to the other backend if they click on the tabs. I think there are two options:

1. Go with it as is, maybe enhancing the separation a bit. The text is small and above the code box, so I think it still stays fairly well together. It could be seen as a theme issue more than an content issue.
2. Drop Flit and PDM, and then have the 2-item bullet list with Hatchling and Setuptools. We want Hatchling as the default, but the rest of the pages cover setuptools, so that's the perfect choice as a second one.

My interest in the tabs is to illustrate that this is general and show what part changes visually, and two tabs does that as well as four, so I'm fine with either option.

2022-06-06 21:37 UTC, domdfcoding commented on source/tutorials/packaging-projects.rst
> +    name = "example-pkg-YOUR-USERNAME-HERE"
In the rest of the guide the name is `example-package-YOUR-USERNAME-HERE`.

2022-06-06 21:47 UTC, domdfcoding commented on source/tutorials/packaging-projects.rst
> +    Bug Tracker = "https://github.com/pypa/sampleproject/issues"
```suggestion
    "Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
```

2022-06-07 01:00 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
I reworked this section to rely on the project summaries to describe the tools, and attempted to define "build backend" (although maybe it warrants its own glossary definition). Take a look at the [rendered version](https://python-packaging-user-guide--1031.org.readthedocs.build/en/1031/tutorials/packaging-projects/#creating-pyproject-toml). 

@henryiii @ofek @brettcannon Is this accurate, concise, and helpful, at least enough for now?

I still want to walk through the tutorial with each each of these tools to verify that it works as promised.

2022-06-07 13:10 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
You forgot `__init__.py`. All four backends do not support automatic namespace packages (this includes the classic tutorial with setuptools if you don't manually specify things).

Missing dependencies is a bug in PDM, I think.

License is a bit odd, but I think this is a problem with not following PEP 621 exactly; it says that specifying the classifier should be enough. (I recently dropped the license specification, due to the wording in PEP 621 and due to PEP 639 & setuptools).

2022-06-07 13:23 UTC, ofek commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
> Hatchling fails after pip install with the src layout

The tutorial adding the user's name to the package name will mess up detection if the package directory does not match https://hatch.pypa.io/1.2/plugins/builder/#default-file-selection

> All generate notably different sdists, with Hatchling many more project files

https://hatch.pypa.io/1.2/plugins/builder/#default-file-selection_1

> It's not clear if any of them properly specify the license

How so?

2022-06-07 13:30 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
> You forgot `__init__.py`.

@henryiii How so? It's in the source tree, and in the sdists:

```
% tree -I venv -I dist -I __pycache__ -I '*.egg-info'
.
├── LICENSE
├── README.md
├── pyproject.toml
├── src
│   └── example_package
│       ├── __init__.py
│       └── example.py
└── tests
    └── test_example.py
```

2022-06-07 13:37 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
Why is it not in the wheel listings at the end of the gist? Are the package names and project names mismatched?

2022-06-07 14:39 UTC, pradyunsg commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
For flit, it looks for a name matching the `name` key. If that's not the same as the import name, you need to configure it to find the correct name. See sphinx-theme-builder's pyproject.toml for details. (sorry, on mobile with bad data, so no links)

2022-06-07 14:47 UTC, ofek commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
I don't think the name should be unique i.e. no need to make learners upload a test package.

2022-06-07 14:53 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
> I don't think the name should be unique i.e. no need to make learners upload a test package.

The goal of this tutorial is for users to upload a package to TestPyPI and `pip install` it.

2022-06-07 14:55 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
Two different learner's packages will not be co-installable in the current form, they override each other. Unless you really know what you are doing, it's a bad idea to have a package that doesn't match the module name. Would adding this to the folder name too be a good idea?

FYI, bug in PDM fixed in https://github.com/pdm-project/pdm-pep517/commit/0deab24890bb93a208740d5ed456e057686ab70a so probably next release.

2022-06-07 15:04 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
> it's a bad idea to have a package that doesn't match the module name.

@henryiii Is this documented anywhere? I feel like I've seen this behavior relatively frequently (i.e., the `pip install` name is different from the `import` name).

2022-06-07 15:11 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
You cannot have two packages with the same module inside, unless there are no file conflicts, or every conflicting file is exactly the same. So if `scikit-build` actually installs `skbuild`[^1], then you can't have a `pip install skbuild` package, they would conflict. PyPI names are "owned", so unless you also own the PyPI name you are installing to, then another package has every right to take it.

I'm not sure it's documented, other than that `tool.<name>` should match the package name.

This doesn't mean it's not done, just that it's usually a bad idea, and probably shouldn't be the default for a new package in a tutorial. I think all backends except setuptools assume the default is to match. Setuptools triggers the package search with a few exclusions (like for `test*`), since that's how `find_packages` worked and I expect it's using it internally.

[^1]: It does.

2022-06-07 15:28 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
> * setuptools doesn't support editable installs

Regarding setuptools lack of editable installs. Currently I am waiting for [some reviews](https://github.com/pypa/setuptools/pull/3265) from the other maintainers to support editable install without `setup.py`. Hopefully we can get it working soon.

> * It's not clear if any of them properly specify the license

This is likely going to be solved once PEP 639 is fully approved.

2022-06-09 01:34 UTC, ezio-melotti commented on source/tutorials/packaging-projects.rst
> +        build-backend = "pdm.pep517.api"
> I reworked this section to rely on the project summaries to describe the tools, and attempted to define "build backend" (although maybe it warrants its own glossary definition). Take a look at the [rendered version](https://python-packaging-user-guide--1031.org.readthedocs.build/en/1031/tutorials/packaging-projects/#creating-pyproject-toml).

Thanks @bhrutledge, the tabs look much better now!

2022-06-10 09:54 UTC, flying-sheep requested changes

2022-06-10 09:54 UTC, flying-sheep commented on source/tutorials/packaging-projects.rst
> +    name = "example-package-YOUR-USERNAME-HERE"
This needs to be unified with the package name to work with Flit and Hatch out of the box:

https://gist.github.com/bhrutledge/01509dc194a6d0608407cc84b97ac58e#comments

2022-06-10 11:53 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +    name = "example-package-YOUR-USERNAME-HERE"
We've been discussing that at https://github.com/pypa/packaging.python.org/pull/1031#discussion_r891360078

2022-06-12 13:47 UTC, flying-sheep commented on source/tutorials/packaging-projects.rst
> +    name = "example-package-YOUR-USERNAME-HERE"
I missed that because the thread you talked in was about something kinda unrelated.

There seemed to be no definite resolution. You asked:

> Would adding this to the folder name too be a good idea?

And nobody answered. Leaving things as they are will result in the errors that @bhrutledge documented in the gist, so one needs to either a) use the generic name for both b) use the personalized name for both, or c) configure each backend so it copes with the mismatch.

I think with the stated goals being to have separate learners’ packages co-installable and to leave things generic without backend specific config, the only remaining option seems to be “rename the folder to `example_package_YOUR_USERNAME_HERE`”

2022-06-12 13:58 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +    name = "example-package-YOUR-USERNAME-HERE"
@flying-sheep Thanks for your thoughts. I came to the same conclusion that you did (i.e. renaming the folder being the only option), and [said as much](https://github.com/pypa/packaging.python.org/pull/1031#discussion_r891349779) in the discussion thread. To avoid further fragmentation of this discussion, please post any additional comments to that thread.

2022-06-14 13:11 UTC, sbaack commented
Hi! I just tried this out: created the example project as described in the tutorial and tested all the mentioned build backends. `python -m build` fails with `flit`:

`ValueError: No file/folder found for module example-package-YOUR-USERNAME-HERE`

All the other build backends work as expected. I never used `flit` before, but my theory is that it needs some additional configuration to support the src-layout used in the tutorial?

2022-06-14 13:16 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +recommends :ref:`Hatchling <hatch>` for its simplicity and speed, but it will
Leaving my recent `setuptools` contributor hat aside[^1], I was trying to follow the `hatchling` documentation to see how a new user would respond to an explicit recommendation of using the tool.

I personally found that `hatchling` is very intertwined with `hatch`, which might make things difficult to understand for beginners.

I am listing below a few points that might cause some kind of trouble for new users (at least as they stand today):

- I could not find [documentation specific to `hatchling`](https://pypi.org/project/hatchling/1.3.1/).
  - If after completing the tutorial the user decides to go after the documentation, they will only be directed to `hatch`'s documentation (which has the complexity of project and environment management added to it).
- While reading `hatch`’s documentation I noticed that all non-PEP 621 configuration is done via the `[tool.hatch]` table. This raises the question:
  - Does it mean that you cannot use these configurations if you are not using the `hatch` CLI?

[^1]: My obvious preference would be that this tutorial does not include any explicit recommendation for backends. Given that all the backends are PEP 621 compliant, the simplicity of use for simple packages/new users should be roughly the same for all of them (i.e. filling out the `[build-backend]` and `[project]` table), and from the standpoint of the tutorial there is no need to recommend one tool over the other. In this regard however, setuptools can be temporarily (before the PEP 660 PR is merged) considered “more complicated”, because users will need to add an extra `setup.py` file  if they want to use editable installs.

2022-06-14 13:24 UTC, ofek commented on source/tutorials/packaging-projects.rst
> +recommends :ref:`Hatchling <hatch>` for its simplicity and speed, but it will
> Does it mean that you cannot use these configurations if you are not using the `hatch` CLI?

No, relevant comment: https://github.com/pypa/packaging.python.org/pull/1031#discussion_r873220647

> I could not find documentation specific to hatchling

This tutorial should link to what's in: https://github.com/pypa/packaging.python.org/pull/1031#discussion_r873242341

2022-06-14 13:47 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +recommends :ref:`Hatchling <hatch>` for its simplicity and speed, but it will
Thank you very much for the information @ofek.

2022-06-14 14:40 UTC, bhrutledge commented
> All the other build backends work as expected. I never used `flit` before, but my theory is that it needs some additional configuration to support the src-layout used in the tutorial?

@sbaack I believe you've encountered a known issue, with a discussion starting at https://github.com/pypa/packaging.python.org/pull/1031#discussion_r891096802. TL;DR: The metadata `name` needs to match the directory name in order for `flit` and `hatchling` to work as expected. As noted in the PR description, updating the tutorial to reflect that is currently blocking the merge of this PR. If there's anything you'd like to add, please respond to the thread that I linked.

2022-06-14 14:45 UTC, henryiii commented
I’m unexpectedly traveling but can update the naming when I get back.

2022-06-14 15:32 UTC, sbaack commented
> I believe you've encountered a known issue, with a discussion starting at [#1031 (comment)](https://github.com/pypa/packaging.python.org/pull/1031#discussion_r891096802). TL;DR: The metadata `name` needs to match the directory name in order for `flit` and `hatchling` to work as expected. As noted in the PR description, updating the tutorial to reflect that is currently blocking the merge of this PR. If there's anything you'd like to add, please respond to the thread that I linked.

Thank you and sorry, should have read this discussion properly before adding a comment :-)

2022-06-15 19:17 UTC, henryiii commented
I've matched the package name and module name. I've also standardized on using `_` everywhere. I think it's a bit better practice, avoids an easy mistake, and keeps the SDist name consistent with the wheel name. The old printouts were wrong, by the way; wheel names always replace `-` with `_` so that they can be parsed into tags correctly.

2022-06-15 19:19 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +      example_package_YOUR_USERNAME_HERE-0.0.1-py3-none-any.whl
This was wrong before, the wheel must have the name `example_package_YOUR_USERNAME_HERE-0.0.1-py3-none-any.whl` regardless of wether dashes or underscores were used in defining it. (and in a couple other places)

2022-06-15 19:20 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> -``example-package-YOUR-USERNAME-HERE``).
Pretty sure this isn't needed now that the names match. I added a little note near the beginning about having matching names being better that serves a similar purpose.

2022-06-15 19:45 UTC, henryiii commented
Guessing this is broken by https://github.com/pypa/pip/commit/347e724efe1d0c79ef63415b48295d8f62c11b72

2022-06-16 09:24 UTC, flying-sheep commented on source/tutorials/packaging-projects.rst
> +      example_package_YOUR_USERNAME_HERE-0.0.1-py3-none-any.whl
yeah, that’s probably so you can parse a wheel filename. Since the pattern has exactly one optional component (the build tag: `{distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl`), and no part contains dashes, splitting it on dashes will unambiguously yield the parts.

2022-06-16 21:51 UTC, dstufft commented
FWIW, I see on the preview it says:

> name is the distribution name of your package. This can be any name as long as it only contains letters, numbers, _ , and -.

I'm not sure if the omission was done on purpose, but ``.`` is the other character also valid in distribution names.

2022-06-16 22:54 UTC, ezio-melotti commented on source/tutorials/packaging-projects.rst
> +  your username as you did in the tutorial. But you can't take an existing name.
```suggestion
  your username as you did in the tutorial, but you can't take an existing name.
```

2022-06-17 04:09 UTC, cdfarrow commented on source/tutorials/packaging-projects.rst
> +* Consider packaging tools that with project management features, such as
that {+come} with

2022-06-17 13:19 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +* Consider packaging tools that with project management features, such as
```suggestion
* Consider packaging tools that come with project management features, such as
```

2022-06-17 13:26 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +* Consider packaging tools that with project management features, such as
Actually, this was already changed (moving "that" instead)

2022-06-17 18:42 UTC, pradyunsg commented
> Guessing the build is broken by [pypa/pip@347e724](https://github.com/pypa/pip/commit/347e724efe1d0c79ef63415b48295d8f62c11b72) . `main` has the same problem. @pradyunsg this seems to need to be pointed to `pip:0-repeatability` instead of `pip:repeatability`. Why are the zero's there?

This has been fixed.

2022-06-18 06:18 UTC, abravalheri commented on source/tutorials/packaging-projects.rst
> +metadata>`.
```suggestion
uses :ref:`Hatchling <hatch>` by default, but it will work identically with
:ref:`setuptools`, :ref:`Flit <flit>`, :ref:`PDM <pdm>`, and others that
support the ``[project]`` table for :ref:`metadata <configuring metadata>`.
Feel free to select another backend.
```

This a suggestion from the [discourse thread](https://discuss.python.org/t/removing-setup-cfg-and-setup-py-from-the-packaging-tutorial/16096/83?u=abravalheri) that seems very appropriate.

2022-06-20 15:05 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +  automatically in a temporary, isolated virtual environment.
This is great and addresses a very common misconception people have when working with requires. Maybe we could even go one step further and add:
```suggestion
  don't need to install them; build frontends like :ref:`pip` will install them
  automatically in a temporary, isolated virtual environment; they will only be
  available during the build process.
```

?

2022-06-20 15:07 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +  perform the build.
This is a bit of jargon?

```suggestion
- ``build-backend`` is the name of the Python object that frontends (like `pip` or `build`) will call to perform the build.
```

2022-06-20 19:31 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +  perform the build.
The previous bullet point already says "build frontends like `pip`, and the association was also made at the beginning of this section.

2022-06-20 19:43 UTC, bhrutledge approved these changes
It brings me great pleasure (and relief) to approve this. Further refinements are welcome in future PRs. Thanks @henryiii for pushing this forward, and everyone who contributed to the conversation.

2022-06-20 19:43 UTC, merged

2022-06-21 07:16 UTC, merwok commented on source/tutorials/packaging-projects.rst
> +:file:`pyproject.toml` tells tools "frontend" build tools like :ref:`pip` and
Wording issue: tools frontend build tools