Add PDM to the list of alternatives to Pipenv
pypa/packaging.python.org pull request #1036
Opened 2022-01-03 16:52 UTC by pawamoy

We could also add https://github.com/FFY00/trampolim, but I wanted to see what you think first.
I believe these alternatives deserve an entry on this page :slightly_smiling_face:

2022-01-06 19:47 UTC, henryiii approved these changes

2022-01-06 20:30 UTC, pawamoy commented
Ah, yes, seeing dependencies in their README example confused me. Hatch is already there ;)

2022-01-22 14:45 UTC, bhrutledge requested changes
Thanks for this, and apologies for the lag on the review. I've got a couple requests re: your edits. I also made some of my own suggestions to make the list more useful; if those feel like too much, I can do them in a separate PR.

2022-01-22 14:45 UTC, bhrutledge commented on source/tutorials/managing-dependencies.rst
> +  `PEP 621 <https://www.python.org/dev/peps/pep-0621/>`_.
We prefer to use the `:pep:` role for readability. I also think the parenthetical could be more succinct, and rely on the PEP for details.

```suggestion
* `PDM <https://github.com/pdm-project/pdm>`_ for a modern Python package management
  tool supporting :pep:`582` (replacing virtual environments with ``__pypackages__``
  directory for package installation) and relying on standards such as :pep:`517` and
  :pep:`621`.
```

2022-01-22 14:45 UTC, bhrutledge commented on source/tutorials/managing-dependencies.rst
> +  custom workflow from lower level pieces like ``pip-compile`` and ``pip-sync``
```suggestion
* `pip-tools <https://github.com/jazzband/pip-tools>`_ for creating a lock file of all
  dependencies from a list of packages directly used in a project, and ensuring that
  only those dependencies are installed.
```

2022-01-22 14:45 UTC, bhrutledge commented on source/tutorials/managing-dependencies.rst
>    tagging releases, and creating new skeleton projects from project templates)
```suggestion
  more steps in the project management workflow, such as incrementing versions,
  tagging releases, and creating new skeleton projects from project templates.
```

2022-01-22 14:45 UTC, bhrutledge commented on source/tutorials/managing-dependencies.rst
>    Python applications but not limited to them.
```suggestion
* `micropipenv <https://github.com/thoth-station/micropipenv>`_ for a lightweight
  wrapper around pip that supports ``requirements.txt``, Pipenv and Poetry lock files,
  or converting them to pip-tools compatible output. Designed for containerized
  Python applications, but not limited to them.
```

2022-01-22 14:45 UTC, bhrutledge commented on source/tutorials/managing-dependencies.rst
> +  itself support distribution as a ``pip``-installable Python package).
```suggestion
* `Poetry <https://github.com/python-poetry/poetry>`__ for a tool comparable in scope
  to Pipenv that focuses more directly on use cases where the project being managed is
  structured as a distributable Python package with a valid ``pyproject.toml`` file.
  By contrast, Pipenv explicitly avoids making the assumption that the application
  being worked on will support distribution as a ``pip``-installable Python package.
```

2022-01-22 14:45 UTC, bhrutledge commented on source/tutorials/managing-dependencies.rst
> +at the bottom of the page.
Let's take advantage of [implicit link targets](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#implicit-targets).

```suggestion
For alternatives, see `Other Tools for Application Dependency Management`_.
```

2022-01-23 12:56 UTC, pawamoy commented on source/tutorials/managing-dependencies.rst
>    Python applications but not limited to them.
Applied manually (GitHub wouldn't let me).

2022-01-23 12:57 UTC, pawamoy commented on source/tutorials/managing-dependencies.rst
> +  itself support distribution as a ``pip``-installable Python package).
Applied manually (GitHub wouldn't let me).

2022-01-23 12:58 UTC, pawamoy commented
Hi @bhrutledge, thanks for the review! Nice suggestions, I applied them. Let me know if there's something else to do.

2022-01-23 14:23 UTC, bhrutledge approved these changes
Excellent! Thank you.

2022-01-23 14:23 UTC, merged