Update output filename in packaging-project
pypa/packaging.python.org pull request #1040
Opened 2022-01-15 16:46 UTC by daxamin

#999

2022-01-15 23:16 UTC, webknjaz commented on .gitignore
> +.vscode
This doesn't seem related to changing the docs.

2022-01-16 04:07 UTC, meowmeowmeowcat requested changes

2022-01-16 04:07 UTC, meowmeowmeowcat commented on source/tutorials/packaging-projects.rst
> +https://test.pypi.org/project/example-package-YOUR-USERNAME-HERE
Could you also modify this link in `conf.py` so  linkcheck can ignore it correctly?

2022-01-16 14:57 UTC, daxamin commented on .gitignore
> +.vscode
removed

2022-01-16 14:57 UTC, daxamin commented on source/tutorials/packaging-projects.rst
> +https://test.pypi.org/project/example-package-YOUR-USERNAME-HERE
done

2022-01-16 18:15 UTC, webknjaz approved these changes

2022-01-16 19:20 UTC, bhrutledge commented
@webknjaz Looks like `linkcheck` is failing for reasons unrelated to this PR (http://www.pyinstaller.org/ isn't responding). Is there a way to merge this PR anyway?

2022-01-16 19:28 UTC, webknjaz commented
I don't have override privileges. Somebody needs to fix that link first.

2022-01-16 19:58 UTC, merged