adding a "packaging flow" overview document
pypa/packaging.python.org pull request #1100
Opened 2022-06-28 00:27 UTC by cameron-simpson

Per @pfmoore 's suggestion here:
https://discuss.python.org/t/adding-a-packaging-flow-overview-to-the-pypa-docs/15060/3?u=cameron

this pull request offers a document providing a conceptual overview of the PyPA package publishing flow, proposal here:
https://discuss.python.org/t/adding-a-packaging-flow-overview-to-the-pypa-docs/15060

I came to write this after writing this post: https://discuss.python.org/t/modernising-my-packages-am-i-thinking-about-this-all-wrong/14558?u=cameron where I described the problems I had trying to figure out how to move to a more modern `pyproject.toml` based system for my packages, largely because I became swamped in a sea of detailed documents which I could not string together; the PEPs in particular are written for people _already_ very familiar with the packaging ecosystem.

This document is (a) not a tutorial and (b) not a "how to". Its purpose is to outline the required high level semantic steps involved in publishing a package, showing the flow from the author to (typically) PyPI and then on to the end user.

It has had some mostly positive feedback in the linked discussions which I've tried to take onboard.

2022-06-28 11:20 UTC, abravalheri reviewed
Thank you very much @cameron-simpson!

2022-06-28 11:20 UTC, abravalheri commented on source/flow.rst
> +    ]
In the case of setuptools, I think it would make more sense to strip the `requires` to the bare minimum (since the target audience of the document is "beginners", I suppose). Something like:

```toml
[build-system]
requires = ["setuptools>=61.2"]
```

(I bumped to `.2` because it contains some fixes/it is more permissive with input).

2022-06-28 11:20 UTC, abravalheri commented on source/flow.rst
> +and it is also prudent to provide a stub ``setup.py`` containing::
```suggestion
For example, if using ``setuptools`` you might want to add a ``setup.cfg`` file
containing package metadata and/or a small ``setup.py`` stub for backward
compatibility, for example::
```

2022-06-28 21:37 UTC, cameron-simpson commented on source/flow.rst
> +At a minimum, the ``pyproject.toml`` file needs:
[ I sent this as email, but it seems to have... vanished :-( So I'm inserting it here. Sorry for any duplication. ]

Hmm. Would it make sense to talk about "good practice"? I just reread
the paragraph in PEP 621 under "Table name" more closely and indeed it
is as you say. But it seems like there are standard fields that belong
in ``[project]`` and would presumeably be better there. I'd expect that
the more that can go in that table, the less difficulty there would be
switching tools.

I don't want to provide incorrect information. And I really don't want
to provide _complex_ information in this document.

What about something like this?

    A `pyproject.toml`` file should have:

    * a ``[project]`` table containing the `Core Metadata`_ for the
      project which are defined in ``PEP 621``. See `Declaring
      project metadata`_ for more detail.

    * a ``[tool]`` table containing metadata not defined by ``PEP 621``,
      as described by ``PEP 518``

    * a ``[build-system]`` table specifying your build tool,
      which *you* will use to create the build artifacts
      and which an *installer* such as `pip` will use
      to complete an install from a source distribution

    .. _Declaring project metadata: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

Let me know what you think of the above please.

2022-06-29 16:53 UTC, abravalheri commented on source/flow.rst
> +At a minimum, the ``pyproject.toml`` file needs:
> I don't want to provide incorrect information. And I really don't want
to provide complex information in this document.

Probably you picked the wrong packaging ecosystem to summarise 🤣 

> Would it make sense to talk about "good practice"?

I don't think it is a matter of being good practice or not. In the end of the day it might not be up to the end-user to decide that. A backend might be implemented to consume configuration in `starlark`, `yaml`, `json5`, etc, and that is fine. PEP 621 is clear that backends might opt out completely from it.

Maybe something along the lines:

```rst
At a minimum, the ``pyproject.toml`` file needs:

* a ``[build-system]`` table specifying your build tool,
  which *you* will use to create the build artifacts
  and which an *installer* such as `pip` will use
  to complete an install from a source distribution

Very frequently you might also specify in ``pyproject.toml`` (depending on the tools you use):

* a ``[project]`` table containing project metadata
  (See `Declaring project metadata`_ for more detail).

* a ``[tool]`` table containing tool-specific configuration options.

.. _Declaring project metadata: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
```

2022-06-30 01:48 UTC, cameron-simpson commented on source/flow.rst
> +At a minimum, the ``pyproject.toml`` file needs:
> > And I really don't want
> > to provide complex information in this document.
> 
> Probably you picked the wrong packaging ecosystem to summarise 🤣

I wouldn't be writing a doc like this for a trite ecosystem :-)

> > Would it make sense to talk about "good practice"?
> 
> I don't think it is a matter of being good practice or not. In the end of the day it might not be up to the end-user to decide that. A backend might be implemented to consume configuration in `starlark`, `yaml`, `json5`, etc, and that is fine. PEP 621 is clear that backends might opt out completely from it.

Ah. So `pyproject.toml` is intended as (a) a common way forward for tools and things like `pip` to interoperate and (b) a place where tools _can_ put their information, but that is not prescribed as necessary.

> Maybe something along the lines:

I've used most of this, keeping some of the old text for better context:

```At a minimum, the ``pyproject.toml`` file needs:

* a ``[build-system]`` table specifying your build tool,
  which *you* will use to create the build artifacts
  and which an *installer* such as `pip` will use
  to complete an install from a source distribution

Very frequently you might also specify in ``pyproject.toml``
(depending on the tools you use):

* a ``[project]`` table containing project `Core Metadata`_
  (name, version, author and so forth);
  see `Declaring project metadata`_ for more detail

* a ``[tool]`` table containing tool-specific configuration options

.. _Core Metadata: https://packaging.python.org/en/latest/specifications/core-metadata/
.. _Declaring project metadata: https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
```

2022-06-30 01:52 UTC, cameron-simpson commented on source/flow.rst
> +At a minimum, the ``pyproject.toml`` file needs:
BTW, can I (and should I) use relative URLs in references. For example, where I've got this URL:

    https://packaging.python.org/en/latest/specifications/core-metadata/

would it be better to have:

    specifications/core-metadata/

(which would rather assume the location of this document) or this:

    /specifications/core-metadata/

which knows this document is in the same set but not its in-tree location?

2022-06-30 09:23 UTC, cameron-simpson commented on source/flow.rst
> +At a minimum, the ``pyproject.toml`` file needs:
It feels like this adds further complexity to the paragraph, which is intended to be quite succinct.

We can add terminology like "build frontend" (not in the glossary, BTW) in the `The Build System` elaboration below though.

What do you think of this instead:

```
+ exec git diffdiff --git a/source/flow.rst b/source/flow.rst
index 50c6257..6f0bdd2 100644
--- a/source/flow.rst
+++ b/source/flow.rst
@@ -107,6 +107,11 @@ The Build System
 ----------------

 The build tool itself is specified by the required table ``[build-system]``.
+Most build tools provide a "build frontend" such as a command line mode
+for creating the build artifacts.
+All can also be used via the `build`_ module
+which understands the ``[build-system]`` table.
+
 There are several choices available, including but not limited to:
 `flit`_, `hatch`_, `pdm`_, `poetry`_, `setuptools`_, `trampolim`_,
 `whey`_.
```

2022-06-30 09:35 UTC, pfmoore commented on source/flow.rst
> +At a minimum, the ``pyproject.toml`` file needs:
Sure. The thing I think you should be careful about is implying that the user works directly with the build backend. To a beginner, that's a fairly accurate perception (it's hard to view doing `flit build` or `hatch build` as anything other than "interacting with the backend" unless you're a real pedant!) The fly in the ointment is setuptools - as they've now deprecated running `setup.py` directly, there's no way of building a sdist without using a frontend like `build`.

But I agree, this is getting too complex for what you're trying to say in that paragraph. The later elaboration you suggested sounds good to me.

2022-06-30 10:58 UTC, cameron-simpson commented on source/flow.rst
> +.. _PEP 517: https://peps.python.org/pep-0517/
Aye. Going to use some `:role:` changes too. Thanks!

2022-06-30 10:58 UTC, cameron-simpson commented on source/flow.rst
> +.. _PEP 517: https://peps.python.org/pep-0517/
Sorry, `:doc:` etc.

2022-07-08 01:07 UTC, cameron-simpson commented
@pfmoore @abravalheri if we're broadly happy with this PR as it is now, whom should I petition to get it merged?

2022-07-08 07:45 UTC, pfmoore commented
Sorry, I don't know who the maintainers of packaging.python.org are.

2022-07-19 13:39 UTC, bhrutledge commented
Yep, thanks for the ping. It's on my radar every day, but life has been exceedingly busy, and will continue to be through at least this weekend.

2022-07-19 22:33 UTC, cameron-simpson commented
On 19Jul2022 06:39, Brian Rutledge ***@***.***> wrote:
>   Yep, thanks for the ping. It's on my radar every day, but life has 
>   been exceedingly busy, and will continue to be through at least this
>   weekend.

No worries. Sorry to trouble you. Cheers, Cameron

2022-07-21 15:15 UTC, bhrutledge approved these changes
I just pushed a bunch of edits that I think streamline the description of the flow, while maintaining its overall structure. A number of changes are basic copy-editing for consistency of language. I also removed content that felt overly-specific and/or redundant. The biggest change is probably condensing the `build-system` description. Finally, I left a number of TODOs that can be addressed in this PR, or in follow-ups.

If y'all are content with the changes, I'm happy to merge this.

2022-07-26 09:24 UTC, bhrutledge commented
@cameron-simpson My turn for a quiet ping. 😉

2022-07-26 11:05 UTC, cameron-simpson commented
> @cameron-simpson My turn for a quiet ping. 😉

I've covered off everything except the final TODO about mentioning virtual environments and tools like poetry etc. I'm still a bit reluctant to introduce this in a conceptual explaination like this one, which already feels like it is getting wordy. And I haven't figured out what I would write here anyway.

2022-07-27 12:27 UTC, bhrutledge requested changes
@cameron-simpson Thanks for the updates. I want to make some more to polish it up; I'm aiming to do that in the next few days.

2022-07-27 22:52 UTC, cameron-simpson commented
On 27Jul2022 05:27, Brian Rutledge ***@***.***> wrote:
>   ***@***.*** Thanks for the updates. I want to make some more 
>   to polish it up; I'm aiming to do that in the next few days.

Thank you, Cameron

2022-07-28 12:18 UTC, bhrutledge approved these changes
@cameron-simpson I just pushed my edits. The biggest changes are in the "configuration file" and "built distributions" sections. What do you think?

2022-07-28 12:18 UTC, bhrutledge commented on source/flow.rst
> +These last 2 steps are typically performed by a tool like :ref:`pip`.
@cameron-simpson This is nit-picky, but I removed this line in my first round of edits because the steps didn't mention any other tools, so it seemed out of place. Do you feel strongly about including it?

2022-07-28 22:21 UTC, cameron-simpson commented
On 28Jul2022 05:18, Brian Rutledge ***@***.***> wrote:
>   @bhrutledge approved this pull request.
>
>   ***@***.*** I just pushed my edits. The biggest changes are in
>   the "configuration file" and "built distributions" sections. What do
>   you think?

Thank you. I've reviewed the diff and they look like improvements across 
the board.

>+These last 2 steps are typically performed by a tool like :ref:`pip`.
>
>   ***@***.*** This is nit-picky, but I removed this line in my
>   first round of edits because the steps didn't mention any other tools,
>   so it seemed out of place. Do you feel strongly about including it?

I do, though I'm open to rephrasing to make it clear that this isn't 
something which only `pip` can do.

What I specificly wanted to achieve was to hook an action the reader is 
almost certainly very familiar with (`pip install`) to its place in the 
flow.

How about:

    For example, when an end user runs ``pip install`` to install
    packages, :ref;`pip` is performing these last 2 steps.

Is there a second example tool commonly used to install local packages 
we could also mention?

i wanted it up the front here where the last 2 steps are in front of the 
reader's eyeballs.

Cheers,
Cameron Simpson ***@***.***>

2022-07-28 22:33 UTC, bhrutledge commented on source/flow.rst
> +``pip install``.
@cameron-simpson Thanks for explaining your reasoning; I understand what you're going for. Here's a small tweak.

2022-07-28 22:36 UTC, cameron-simpson commented
On 28Jul2022 15:33, Brian Rutledge ***@***.***> wrote:
>   ***@***.*** Thanks for explaining your reasoning; I 
>   understand
>   what you're going for. Here's a small tweak.

Thank you, that looks great.

Cheers,
Cameron Simpson ***@***.***>

2022-07-28 22:37 UTC, merged

2022-07-28 22:38 UTC, cameron-simpson commented
On 28Jul2022 15:37, Brian Rutledge ***@***.***> wrote:
>   Merged [1]#1100 into main.

Thank you! - Cameron Simpson ***@***.***>

2022-10-11 08:46 UTC, cameron-simpson commented
On 21Jul2022 08:15, Brian Rutledge ***@***.***> wrote:
>   @bhrutledge approved this pull request.
>
>   I just pushed a bunch of edits that I think streamline the description
>   of the flow, while maintaining its overall structure. A number of
>   changes are basic copy-editing for consistency of language.

I see that we like full sentences in bullet lists, and the Oxford comma 
:-) And folding at a line length instead of a sentence/phrase break.

>   I also
>   removed content that felt overly-specific and/or redundant.

Reading the diff now.

Short summary: I like almost everything you've done.

My only objections are:

Under "To use the package, end users must:" you've dropped "These last 2 
steps are typically performed by a tool like `pip`_.". I think that's 
important and concise context, since many (most?) users will already be 
familiar with using pip to fetch packages. I wanted it apparent that 
when they did that familiar action, they're doing these last 2 steps. 
The better to hook this to their mental model and experience.

TODOs:

- I deliberately avoided "build backend"; there's already confusion 
  between a build front end (which I take to be something you directly 
  invoke, such as a command line) and a build back end (which I take to 
  be an API compliant with the PEP so that things like "pip" can run it 
  directly).
  To the new user, this is conceptual noise. They'll be using a build 
  tool (setuptools, flit, whatever) and this is about the process around 
  embedding their chosen tool in their distribution flow.
  So I prefer "build tool" at this point.

- Link to tools: are you suggesting that where there's a tool specific 
  entry in key_projects.rst we should point to it instead of (eg) a PyPI 
  or github link? If so, I am all for it - the links I've found were 
  merely the most apt I could see.

- I don't have an opinion on hatchling vs flit, just that there should 
  be at least 2 examples to show that you can use any compliant build 
  tool in [build-system]. I could argue that it is good to use hatchling 
  if the tutorial uses it, or good to use flit to show that the tutorial 
  isn't the Only Way.

- "build system" vs "build frontend"; see, I thought pip would fetch a 
  module containing a build _backend_. Confusion already. I'd go for 
  saying "build tool" once more. Or, given the TOML table name, "build 
  system" throughout instead of "build tool".
  However, I think "build tool" is a more approachable term; to my mind 
  it feels like something one can just fetch and use versus "build 
  system" which feels to me more like a bulky framework one must work 
  within.

I agree with dropping mention of the stub `setup.py` if that is truly 
redundant these days; a stub seemed to be recommended when I wrote this 
stuff. It is definitely confusing extra noise for this document.

I have mixed feelings about mentioning virtual environments. That's very 
much an end user thing instead of a publisher thing. And there are so 
many choices! For example, I'm still using "python3 -m venv" because I 
have yet to see what value something like pipenv brings :-)

Maybe a rider paragraph right at the end mentioning that there are 
several flavours of "Python environment" end users may be using, with 
some of the links you mention. I would want to make it clear that the 
package _author_ should not need to care how the end user manages their 
Python environment. Without that clarification, authors/publishers have 
an additional (and needless) mental burden when preparing their 
packages. I know extraneous things like this mentally burden me when 
coming to a new area.