Add PEP 621 tab for entry points docs
pypa/packaging.python.org pull request #1115
Opened 2022-07-29 12:33 UTC by flying-sheep

2022-08-24 10:44 UTC, bhrutledge requested changes

2022-08-24 10:44 UTC, bhrutledge commented on source/guides/creating-and-discovering-plugins.rst
> +.. tab:: :file:`pyproject.toml` (PEP 621)
I don't think we should reference `setup.py` at all, and just show `pyproject.toml`, without a reference to PEP 621.

2022-08-24 10:44 UTC, bhrutledge commented on source/guides/creating-and-discovering-plugins.rst
> +plugins can register themselves for discovery.
I think the language could be clearer here. Specifically, "telling your package's build backend" seems vague; what does "telling" mean, and do we need to mention "build backend" at all?

Also, it looks like this intends to link to the [entry points spec](https://packaging.python.org/en/latest/specifications/entry-points/), but it's not in the [PR preview](https://python-packaging-user-guide--1115.org.readthedocs.build/en/1115/guides/creating-and-discovering-plugins/). Perhaps it needs to be a `:ref:` instead?

2022-10-12 10:42 UTC, flying-sheep commented on source/guides/creating-and-discovering-plugins.rst
> +plugins can register themselves for discovery.
both done!

2022-10-13 16:42 UTC, Harlee1994 approved these changes

2022-10-26 10:38 UTC, flying-sheep commented
Hi @bhrutledge, can this be merged?

2022-12-04 23:31 UTC, bhrutledge approved these changes
Thanks for the nudge!

2022-12-04 23:31 UTC, merged