Add PEP 508
pypa/packaging.python.org pull request #1177
Opened 2022-12-06 08:54 UTC by konstin

This moves PEP 508 to packaging.python.org as discussed on discord

Diff between [PEP 508](https://github.com/python/peps/blob/1a87312fb30f86e7690c033574e5f6a2767035f9/pep-0508.txt) and dependency-specifiers.rst: https://gist.github.com/konstin/059c0e72ff77049e0eb2ce0d738990fd

2022-12-06 13:10 UTC, bhrutledge commented
@konstin Thanks for this. I don't feel qualified to review this, and I don't follow Discord. Do you have a sense of who from that discussion would be a good reviewer? And/or, can you provide a link to that discussion?

2022-12-06 13:13 UTC, konstin commented
Either @brettcannon or @pradyunsg probably

2022-12-06 13:16 UTC, konstin commented
I got a CI failure email for https://github.com/pypa/packaging.python.org/actions/runs/3629838663/jobs/6122501649 but unfortunately i don't understand how this relates to this PR or why it failed (all checks on this PR seem to pass?)

2022-12-06 13:18 UTC, bhrutledge commented
> I got a CI failure email for https://github.com/pypa/packaging.python.org/actions/runs/3629838663/jobs/6122501649 but unfortunately i don't understand how this relates to this PR or why it failed (all checks on this PR seem to pass?)

Yeah, not sure what's going on here; see #1178. FYI @webknjaz

2022-12-06 19:49 UTC, brettcannon requested changes
I'm assuming this is mostly a wholesale copying of PEP 508, so I'm reviewing it just from a perspective of not losing key details from what was previous here.

2022-12-06 19:49 UTC, brettcannon commented on source/specifications/dependency-specifiers.rst
> +This document describes the dependency specifiers format.
```suggestion
This document describes the dependency specifiers format as originally specified
in :pep:`508`.
```

2022-12-06 19:49 UTC, brettcannon commented on source/specifications/dependency-specifiers.rst
> -Restrictions on names for extras is defined in :pep:`685`.
This is important information that shouldn't be lost. Ultimately it should be rolled into the spec, but for now there should at least be a reference to it _somewhere_ in this document.

2022-12-06 20:27 UTC, konstin commented
> I'm assuming this is mostly a wholesale copying of PEP 508, so I'm reviewing it just from a perspective of not losing key details from what was previous here.

yes, i've included the gist link at the top so you can review the exact section-by-section differences from the document vs. the original PEP 508.

2022-12-06 20:27 UTC, konstin commented on source/specifications/dependency-specifiers.rst
> -Restrictions on names for extras is defined in :pep:`685`.
re-added both in the appropriate places

2022-12-07 00:34 UTC, pradyunsg approved these changes
Let's do this and we can iterate on this as we see fit. :)

2022-12-07 00:34 UTC, pradyunsg commented on source/specifications/dependency-specifiers.rst
> +than pip's current native format.
Hmm... I'm not a big fan of this since "modern" pip defines it as "PEP 508 + extra stuff" but that's for a follow up. :)

2022-12-07 22:04 UTC, merged