Add a hashes key to the direct URL data structure
pypa/packaging.python.org pull request #1199
Opened 2023-01-29 13:26 UTC by sbidoul

Add the hashes key to the Direct URL data structure, as a approved at https://discuss.python.org/t/draft-pep-amendment-to-the-pep-610-direct-url-json-data-structure/22299/4.

@pfmoore

2023-01-29 13:33 UTC, pfmoore approved these changes
Thanks, this looks good!

2023-01-29 13:34 UTC, pradyunsg approved these changes

2023-01-29 13:41 UTC, sbidoul commented
The linkcheck failure seems unrelated.

2023-01-29 14:04 UTC, pfmoore commented
Apparently I can't merge without all checks passing. @pradyunsg do you know what we do here? (You enabled auto-merge, so I'm assuming you know more about the processes here than me 🙂)

2023-01-29 15:38 UTC, pradyunsg commented
... well, this repo blocks owners from merging PRs that fails CI.

2023-01-29 22:57 UTC, sbidoul commented
:green_apple:

2023-01-29 23:57 UTC, webknjaz requested changes
A syntax fix is needed for this to be acceptable.

2023-01-29 23:57 UTC, webknjaz commented on source/specifications/direct-url.rst
> +  ([discussion](https://discuss.python.org/t/22299)).
This is not a Markdown document. RST is a must.
```suggestion
  (`discussion <https://discuss.python.org/t/22299>`__).
```

It is visible how this is broken in the preview: https://python-packaging-user-guide--1199.org.readthedocs.build/en/1199/specifications/direct-url/#history

2023-01-29 23:59 UTC, webknjaz commented
> do you know what we do here?

@pfmoore we normally fix such things in separate PRs to unblock the CI.

2023-01-30 00:04 UTC, webknjaz commented
> The linkcheck failure seems unrelated.

Looking into https://github.com/pypa/packaging.python.org/actions/runs/4037007410, I see that it's been cancelled because of a newer push to this PR:
> 
Canceling since a higher priority waiting request for 'Test-1199' exists

I don't see it being broken. Unless, I'm looking at the wrong log, that is (some tend to be hidden by force-pushes, so it's best to record the exact URLs in the comments for future investigation).
If a job is flaky, restarting it fixes the branch protection too.

2023-01-30 00:07 UTC, webknjaz commented
Oh, found it: https://github.com/pypa/packaging.python.org/actions/runs/4037021743/jobs/6940079785#step:5:765. So the network was flaky. The solution was indeed restarting the job.

2023-01-30 00:40 UTC, ofek approved these changes

2023-01-30 07:35 UTC, sbidoul commented on source/specifications/direct-url.rst
> +  ([discussion](https://discuss.python.org/t/22299)).
Thanks @webknjaz. Some markdown did indeed sneak in during review. This is fixed, now.

2023-01-30 10:13 UTC, merged