fix: Use 'req@url' syntax to install from remote VCS
pypa/packaging.python.org pull request #1207
Opened 2023-02-11 01:12 UTC by matthewfeickert

Use 'req@url' syntax when using pip to install from a remote git repository over 'url#egg=req' to avoid the use of #egg= fragments with a non-PEP 508 name. This will be required in pip v25.0+.
   - c.f. pypa/pip#11617 for more details.

2023-02-11 01:16 UTC, matthewfeickert commented
This is ready for review. Let me know if you have any questions. :+1: 

cc @pradyunsg @pfmoore given their involvement in https://github.com/pypa/pip/pull/11617

2023-02-13 09:48 UTC, pradyunsg requested changes
Could you add whitespace around `@`? IMO that makes it clearer and easier to read.

2023-02-13 10:17 UTC, matthewfeickert commented
> Could you add whitespace around @? IMO that makes it clearer and easier to read.

Sure. I applied that universally, rebased, and `force-with-lease` pushed back.

2023-02-13 11:39 UTC, pradyunsg approved these changes

2023-02-13 11:40 UTC, merged

2023-02-14 11:24 UTC, sinoroc commented
There are issues with sub-directories.

`pip install "git+https://example.com/repo/app.git#egg=app&subdirectory=setup`

was transformed into

`pip install "app&subdirectory=setup @ git+https://example.com/repo/app.git"`

which does not seem correct to me. Is it?

2023-02-14 14:39 UTC, matthewfeickert commented
@sinoroc do you have a failing example?

2023-02-14 18:28 UTC, sinoroc commented
I might be wrong, but I do not think it has anything to do with "*PEP 610 – Recording the Direct URL Origin of installed distributions*". The issue is that this is not a valid requirement notation for the *pip CLI*.

The best I can find is [this section of *pip*'s documentation on "URL fragments" in "VCS Support"](https://pip.pypa.io/en/stable/topics/vcs-support/#url-fragments) which lists two accepted notations for VCS and subdirectory:

* `python -m pip install "pkg @ vcs+protocol://repo_url/#subdirectory=pkg_dir"`
* `python -m pip install -e "vcs+protocol://repo_url/#egg=pkg&subdirectory=pkg_dir"`

2023-02-14 19:09 UTC, matthewfeickert commented
Thanks @sinoroc. Indeed it looks like

```
python -m pip install "pkg @ vcs+protocol://repo_url/#subdirectory=pkg_dir"
```

is what should have been done. I'll open up a fix PR with this correction once I've finished making coffee.