chore: update name of PDM backend
pypa/packaging.python.org pull request #1220
Opened 2023-03-13 14:30 UTC by henryiii

Updated to the new name (avoiding mentioning a PEP) of pdm-backend.

CC @frostming.

2023-03-13 19:33 UTC, bhrutledge requested changes

2023-03-13 19:33 UTC, bhrutledge commented on source/tutorials/packaging-projects.rst
> +:ref:`Flit-core <flit>`, :ref:`PDM-backend <pdm>`, and others that support the
I would either:

- Revert these to "Flit" and "PDM" (referring to the core project)
- Change them to "flit-core" and "pdm-backend" (referring to the PyPI package)

2023-03-14 18:38 UTC, henryiii commented on source/tutorials/packaging-projects.rst
> +``[project]`` table for :ref:`metadata <configuring metadata>`.
```suggestion
:ref:`Flit <flit>`, :ref:`PDM <pdm>`, and others that support the ``[project]``
table for :ref:`metadata <configuring metadata>`.
```

Okay, let's leave these alone for now.

2023-03-14 22:21 UTC, bhrutledge approved these changes
Thanks!

2023-03-14 22:21 UTC, merged