Remove "Dropping support for older Python versions" guide
pypa/packaging.python.org pull request #1348
Opened 2023-11-05 13:07 UTC by jeanas

This is a bunch of outdated or duplicated info, and does not bring much today. Make it a redirect to the specification for `requires-python` in `pyproject.toml`.

2023-11-05 13:33 UTC, sinoroc approved these changes

2023-11-05 14:58 UTC, pradyunsg requested changes
I don't think we should remove this page, and it would instead be better to update it.

It should describe what requires-python looks like, how it behaves and provide guidance on how to bump the version across releases.

2023-11-06 02:18 UTC, webknjaz commented on requirements.txt
> +sphinx-reredirects==0.1.3
RTD already has its own redirects that work on HTTP level. We don't need to handle the same thing in Sphinx.

2023-11-06 02:20 UTC, webknjaz commented
I agree with Pradyun in general — wiping such pages is not the best solution, unless the important information is preserved elsewhere. One thing I noticed is the `universal` setting explanation, for example.

2023-11-06 10:54 UTC, closed without merging