Improve sidebar presentation in specifications section
pypa/packaging.python.org pull request #1395
Opened 2023-11-14 19:52 UTC by jeanas

This is like https://github.com/pypa/packaging.python.org/pull/1368, for the specifications part. CC @pradyunsg

----
:books: Documentation preview :books:: https://python-packaging-user-guide--1395.org.readthedocs.build/en/1395/

2023-11-15 03:24 UTC, willingc approved these changes
Nice! Big improvement. Will leave for Pradyun and others to review too.

2023-11-15 18:01 UTC, sinoroc approved these changes

2023-11-15 23:53 UTC, pradyunsg requested changes

2023-11-15 23:53 UTC, pradyunsg commented on source/specifications/section-distribution-metadata.rst
> +.. toctree::
```suggestion
.. toctree::
   :titlesonly:
```

2023-11-15 23:53 UTC, pradyunsg commented on source/specifications/section-distribution-formats.rst
> +.. toctree::
```suggestion
.. toctree::
   :titlesonly:
```

2023-11-15 23:53 UTC, pradyunsg commented on source/specifications/index.rst
>  .. toctree::
```suggestion
.. toctree::
   :titlesonly:
```

2023-11-15 23:53 UTC, pradyunsg commented on source/specifications/section-package-indices.rst
> +.. toctree::
```suggestion
.. toctree::
   :titlesonly:
```

2023-11-15 23:54 UTC, pradyunsg commented
(let's reduce the amount of content on the "section" pages, to avoid adding too much content there)

2023-11-16 18:57 UTC, pradyunsg approved these changes

2023-11-16 19:08 UTC, willingc approved these changes

2023-11-16 19:11 UTC, merged