DOC: Document RECORD modification
pypa/packaging.python.org pull request #1423
Opened 2023-11-30 16:35 UTC by larsoner

Distilled based on the conversation in https://github.com/pypa/pip/issues/11835#issuecomment-1833546937 and related comments (cc @pfmoore). Happy to modify language or whatever, or close if this recommendation is incorrect!

----
:books: Documentation preview :books:: https://python-packaging-user-guide--1423.org.readthedocs.build/en/1423/

2023-11-30 17:43 UTC, pfmoore requested changes
I agree that this is a subtle "gotcha" that probably warrants a warning, but we need to be careful not to make too much of this particular issue. After all, it's basically just saying "if you don't maintain the metadata the way you should, then things will break". Which is fairly self-evident when you put it like that.

I don't expect the people who are writing files into site-packages will even think they *need* to read this spec - so this probably isn't going to signficantly reduce how often this issue comes up in practice. It's more about raising general awareness, and should be written from that perspective.

2023-11-30 18:42 UTC, pfmoore commented
> However, I think that this text could lead to the impression that dynamically changing installed packages is officially supported (as long as you do update RECORD). Is there consensus on that?

I think the opposite is true, the presumption is that only installers should be writing to package directories. It's not a *rule* (how would you even define it without having to pin down what counts as an installer?) but it's definitely baked into how people think about things.

I'd be a strong -1 on anything that suggested modifying installed packages was supported. Do it if you have to, but when everything breaks, you have nobody to blame but yourself :-) And in particular, don't expect us to tell you what you need to do in order to do it safely.

2023-12-01 00:45 UTC, larsoner commented
👍 works for me! @jeanas do you want to open a new PR, comment inline as a `suggestion` so you can get credit, or want me to just copy-paste here? Would be nice for you to get credit but if you don't care then I can easily copy-paste

2023-12-01 18:44 UTC, larsoner commented
Put in @jeanas wording, @pfmoore do you want to look?

2023-12-01 22:01 UTC, willingc approved these changes

2023-12-01 22:12 UTC, merged