Deduplicate specification of valid package names
pypa/packaging.python.org pull request #1463
Opened 2023-12-22 14:33 UTC by jeanas

- Rename the "Package name normalization" specification into "Package name grammar and normalization", to make it explicitly about the format of valid names too.

- Link to this spec in the core metadata specification instead of duplicating the part about valid names.

2023-12-22 22:39 UTC, pradyunsg requested changes

2023-12-22 22:39 UTC, pradyunsg commented on source/specifications/name-normalization.rst
> +The name should be lowercased with all runs of the characters ``.``, ``-``, or
nit/off-topic: Did we have agreement at any point on whether to wrap or not-wrap in this docset?

2023-12-22 22:53 UTC, jeanas commented on source/specifications/name-normalization.rst
> +Name grammar
Well, doing a bit of introspection, the reason it was natural to me is that a language recognized by a classic regex can be viewed as a language recognized by a regular grammar. But let's assume not everybody knows that formal language theory stuff... I'd prefer to eschew "valid names" because it feels weird to link to the "valid name specification". Let me change it to "Name format", this is a good idea.

2023-12-22 23:00 UTC, jeanas commented on source/specifications/name-normalization.rst
> +The name should be lowercased with all runs of the characters ``.``, ``-``, or
Do you mean whether paragraphs should be wrapped in general (to which I think the answer is yes based on the vast majority of the content), or whether it's fine to wrap them in PRs if they're not wrapped?

2023-12-22 23:03 UTC, jeanas commented on source/specifications/name-normalization.rst
> +Project names obey a restricted format, and are "normalized" for use in various
Changed, let me know if the next text is OK.

2023-12-22 23:03 UTC, jeanas commented on source/specifications/name-normalization.rst
> +Package name grammar and normalization
Applied.

2023-12-23 14:42 UTC, pradyunsg commented on source/specifications/name-normalization.rst
> +The name should be lowercased with all runs of the characters ``.``, ``-``, or
> Do you mean whether paragraphs should be wrapped in general 

This.

> or whether it's fine to wrap them in PRs if they're not wrapped?

... which informs this because I'd prefer that we enforce consistency in a one-shot. 😅

2023-12-23 14:43 UTC, pradyunsg approved these changes

2023-12-31 17:50 UTC, webknjaz commented on source/specifications/name-normalization.rst
> +The name should be lowercased with all runs of the characters ``.``, ``-``, or
I think the problem with this is that on one hand wrapping is nice but reflowing together with content changes in the same PR has the same problem as reformatting normal source code while also changing behavior. They just have to be separate. And when they're smashed, it's impossible to review sanely.

OTOH, I know there's i18n-related tools that demand complete sentences on dedicated lines and use that for tracking sentence changes across versions when they're updated. That's a translation tooling aspect. I think these is used in "conventional markdown" or something like that.

2023-12-31 17:51 UTC, webknjaz approved these changes

2023-12-31 17:53 UTC, merged