Update tool recommendations
pypa/packaging.python.org pull request #1474
Opened 2023-12-30 13:44 UTC by jeanas

This is my proposal to address #1468.

Fixes #1468

2023-12-30 15:03 UTC, chrysle commented on source/guides/tool-recommendations.rst
> +the Python Packaging Authority (PyPA, the umbrella organization which
```suggestion
the :term:`Python Packaging Authority <Python Packaging Authority (PyPA)>` (PyPA, the umbrella organization which
```

2023-12-30 15:03 UTC, chrysle commented on source/guides/tool-recommendations.rst
> +  For example, do not use ``python setup.py`` invocations
```suggestion
  For example, do **not** use ``python setup.py`` invocations
```

2023-12-30 15:13 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +Lock files
Yes, but follow-up PR?

2023-12-30 15:16 UTC, chrysle commented on source/guides/tool-recommendations.rst
> +Lock files
Yup.

2023-12-30 15:20 UTC, jeanas commented
@chrysle Thanks for reviewing! I've addressed your comments, sometimes with slightly different wordings.

2023-12-31 13:12 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +  (cf. :ref:`setup-py-deprecated`), the ``python_requires`` argument to
```suggestion
  (cf. :ref:`setup-py-deprecated`), the ``setup_requires`` argument to
```

2023-12-31 17:02 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +(PyPA, the umbrella organization which encompasses many packaging tools and
I wouldn't say "organization", it's more like a bunch of people and projects that are sometimes connected loosely, and sometimes not.
https://www.pypa.io/ presents the PyPA as a working group, which is probably a better term to use here.

2023-12-31 17:03 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +example, the reason there exist many build backends is that the landscape was
```suggestion
example, the reason there are many build backends is that the landscape was
```

2023-12-31 17:03 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +opened in order to enable the development of new backends serving certain users'
```suggestion
opened up in order to enable the development of new backends serving certain users'
```

2023-12-31 17:05 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +in most Python installations.
".. through the stdlib package `ensurepip`".

2023-12-31 17:08 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +consider :ref:`pipx`, which is a wrapper around pip that installs each
"pip and virtualenv"?

2023-12-31 17:09 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +the dependencies of different applications. On Linux, pipx is especially
"applications that are distributed as Python package distributions through the PyPI"?

2023-12-31 17:11 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +important because it also avoids conflicts with the system (which are the reason
Not sure I'd separate Linux from others here — it's bad to sure globally shared envs in so many contexts. In GNU/Linux you can break some system software, including package managers, but a similar influence exists in other OS-independent situations.

2023-12-31 17:16 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- Hatchling, which is part of :ref:`Hatch` (but can be used without
It's a part of the same Git repository but is published a fully separate distribution on PyPI. This should either clarify that it's a part of the Hatch ecosystem or just drop the implication.

Hatchling is a build backend, but Hatch is a frontend, installer, resolver, virtualenv manager, command runner, workflow tool. Let's not smash them together.

2023-12-31 17:17 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- :ref:`setuptools`, the historical build backend. It can be configured
It's not historical. It's old, but it's also modern. It has a lot of legacy in its own codebase but that's an implementation detail.

cc @jaraco @abravalheri

2023-12-31 17:19 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +  programmatically through the :file:`setup.py` file (but for basic metadata,
Or `setup.cfg`, if we're listing the configuration details here. But then, why don't we do this for the other list items? If we're listing the config files, why not mention `hatch.toml`, `.pip-tools.toml`, `Pipfile` above too?

I'd drop these from here too.

2023-12-31 17:20 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +- :ref:`setuptools`, the historical build backend. It can be configured
I didn't mean that it shouldn't be used anymore, only that it was the only choice for a long time. I think this is useful to put on this page because many people will be wondering why the heck they didn't have to make any choice of backend when they created a package years ago. Maybe `` :ref:`setuptools`, which used to be the only build backend `` would be clearer?

2023-12-31 17:20 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- Flit-core, part of :ref:`Flit` (but usable standalone). It is meant to be a
Same as with hatch — let's not mix self-sufficient front ends into a section about backends.

2023-12-31 17:24 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +to build distributable wheels.
Let's mention `pip wheel` that can be used as a low-level piece of automation for building platform-specific wheels in places where `cibuildwheel` may be unavailable. With a note that pypa/build can be used for the same.

2023-12-31 17:26 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +The standard tool for this task is :ref:`twine`.
Let's mention that some of the workflow tools (hatch, poetry, flit) invoke it under the hood.

Also, let's link the secretless publishing guide which wraps it but should probably be the first choice for any GitHub-hosted projects using GHA: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

2023-12-31 17:27 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +distributions, uploading to PyPI, or creating and using lock files.
```suggestion
distributions,
uploading to PyPI, or creating and using tool-specific lock files.
They often call the tools mentioned above under the hood.
```

2023-12-31 17:28 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- :ref:`Poetry`.
I suppose `Pipenv` can be mentioned in this section too.

2023-12-31 17:32 UTC, chrysle commented on source/guides/tool-recommendations.rst
> +consider :ref:`pipx`, which is a wrapper around pip that installs each
> "pip and virtualenv"?

Pip and Venv, actually. Virtualenv might be supported in future versions.

2023-12-31 17:44 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- :ref:`setuptools`, the historical build backend. It can be configured
Yep, that would be better. Thanks!

2024-01-03 00:57 UTC, eli-schwartz requested changes

2024-01-03 00:57 UTC, eli-schwartz commented on source/guides/tool-recommendations.rst
> +extension is written in, such as Meson or CMake for C/C++, or Cargo for Rust,
Just want to point out that meson and cmake aren't specific to C/C++

They also support C#, Cuda, Swift, Asm, ObjC, ObjC++, Fortran.
Meson supports D, rust, vala, Java, and cython. CMake supports Hip and ISPC.

They are particularly valuable in cases where you have multiple languages, e.g. a mixture of rust and C++ and Fortran in a single project.

Meson also explicitly allows you to select `*.py files for installation`, do code generation of .py files (and other files), compile data such as gettext .po -> .mo catalogs, produce bundled `*.exe`s, and in general any form of custom build step. In theory CMake allows you to do precisely the same thing, although the scikit-build(-core) docs don't clearly indicate whether they support packaging that into a wheel.

tl;dr saying to use it "to support a dedicated extension language" is vastly underselling them. Even the "C/C++" part is simply *factually* wrong, if you need C/C++ support then setuptools works okay. The killer feature in the data science community is support for *Fortran*.

2024-01-03 00:57 UTC, eli-schwartz commented on source/guides/tool-recommendations.rst
> +Popular :term:`build backends <build backend>` for pure-Python packages include:
```suggestion
Popular :term:`build backends <build backend>` for pure-Python packages include (in alphabetical order):
```

... and sort them.

2024-01-03 11:17 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +  programmatically through the :file:`setup.py` file (but for basic metadata,
I'm just trying to list which backends support plugins / programmatic config. (I think this is important, because those that do have an ecosystem of plugins around them.) `pyproject.toml` was originally not mentioned here, but added per https://github.com/pypa/packaging.python.org/pull/1474#discussion_r1438610971

2024-01-03 11:21 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +to build distributable wheels.
I thought the pip developers were unhappy with `pip wheel` and considering to deprecate it (but I may be misremembering, and I can't find the pip issue right now). @pfmoore @pradyunsg What's your opinion?

2024-01-03 11:25 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +The standard tool for this task is :ref:`twine`.
> Let's mention that some of the workflow tools (hatch, poetry, flit) invoke it under the hood.

I don't think they do? I didn't find any trace of this in the Hatch, Flit and Poetry repos.

2024-01-03 12:55 UTC, abravalheri commented on source/guides/tool-recommendations.rst
> +build backend:
This is probably more direct:

```suggestion
a build system with dedicated support for the language the extension is written in:

- :ref:`setuptools` - natively supports C/C++ (with 3rd-party plugins for Go and Rust);

- :ref:`meson-python` - C, C++, Fortran, and Rust and other languages supported by Meson;

- :ref:`scikit-build-core` - C, C++, Fortran and other languages supported by CMake;

- :ref:`maturin` - Rust, via Cargo.
```

2024-01-03 12:55 UTC, abravalheri commented on source/guides/tool-recommendations.rst
> +- :ref:`setuptools` (which used to be the only build backend). It can be configured
```suggestion
- :ref:`setuptools` (which used to be the only build backend). It can be configured
  using modern standards like `pyproject.toml`, but can also be extended
  and supports customisation via `setup.py`.
```

2024-01-03 13:15 UTC, pfmoore commented on source/guides/tool-recommendations.rst
> +to build distributable wheels.
I'm not aware of plans to deprecate `pip wheel`, but it's worth noting that:

1. *Building* wheels isn't its sole/primary purpose - it downloads wheels, or downloads sdists and builds them into wheels. `pip wheel .` builds a wheel of the current project, but somewhat as a side issue (we could potentially use a cached wheel if we had a way to be sure it matched the source code).
2. There's no pip command to build a sdist, and there may well never be one.

If you want to build a local project, `build` is a much more appropriate tool.

2024-01-03 16:39 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +to build distributable wheels.
Ok, then I'd rather not mention `pip wheel` here.

2024-01-03 17:08 UTC, abravalheri commented on source/guides/tool-recommendations.rst
> +  features which are currently kept for compatibility, but should not be used.
```suggestion
  If you use setuptools, please be aware that some features that predate
  standardisation efforts are now deprecated and only *temporarily kept* for compatibility.
```

2024-01-16 18:21 UTC, jeanas commented
I believe I've addressed all review comments. There were many reviews and it's not clear to me whether reviewers are now OK with the PR or just didn't have the time to take another look.

2024-01-17 02:49 UTC, webknjaz commented
I didn't have time, but I hope to find some.

2024-01-25 02:13 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +.. _tox: https://tox.wiki
Tox is wired through intersphinx.

2024-01-25 02:13 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +.. _nox: https://nox.thea.codes
Nox is wired through intersphinx.

2024-01-25 02:14 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +.. _flit-core: https://pypi.org/project/flit-core/
Flit is wired through intersphinx.

2024-01-25 02:16 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +common tools for this are tox_ and nox_.
```suggestion
common tools for this are :doc:`tox <tox:index>` and :doc:`nox <nox:index>`.
```

2024-01-25 02:22 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- Flit-core_ -- developed with but separate from :ref:`Flit`. A minimal and
```suggestion
- :doc:`Flit-core <flit:pyproject_toml>` -- developed with but separate from :ref:`Flit`. A minimal and
```

2024-01-25 02:29 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +Package Index (PyPI)>`. It can install into the global environment or into
Also, "virtual" (as a concept/word) is not an opposite of "global". I think this may be confusing to some.

2024-01-25 02:34 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +Package Index (PyPI)>`. It can install into the global environment or into
How about "isolated" vs. "shared"?

2024-01-25 02:40 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +command line applications that are distributed through PyPI.
I think it's wrong to emphasize CLI apps, while realistically, it is useful in the context of any packages that are considered distributing apps. GUI included, maybe even web(ish) apps with strict pins could be included. So I'd just drop this clarification as not factual.
```suggestion
applications that are distributed through PyPI.
```

2024-01-25 02:40 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +command line applications that are distributed through PyPI.
Alternatively, clarify that there's more to it:
```suggestion
command line (and other types of) applications that are distributed through PyPI.
```

2024-01-25 02:42 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +(especially on Linux).
```suggestion
the dependencies of different applications, and also with the
ones installed system-wide making use of the same Python
interpreter (especially on GNU/Linux).
```

2024-01-25 03:06 UTC, webknjaz commented on source/guides/tool-recommendations.rst
I feel like this might be the place to remind the readers not to treat this list as sorted by popularity.

```suggestion

.. important::

   Please, remember, this document does not seek to steer the reader towards
   a one-stop show solution. It merely enumerates tools observed within the
   packaging community. Different use-cases often need specialized workflows.

```

2024-01-25 03:15 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +
Should we mention that some tools focus on many things?
```suggestion

.. tip::

   Note that while most tools are is only mentioned under one
   section in this document, some of them cover several use
   cases.

```

2024-01-25 03:23 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +  the ``easy_install`` command (cf. :ref:`pip vs easy_install`).
How about wrapping this with `.. caution::`?

2024-01-25 03:37 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +The standard tool for this task is :ref:`twine`.
Ah, interesting. I thought they did.

@jeanas still worth mention the GHA, I think.

2024-01-25 03:39 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +============
I think it's more accurate to say
```suggestion
Workflow tools
==============
```

Saying "task runners" reduce them to a GNU/make replacement. But really, there's things like venv management that this skips.

2024-01-25 03:51 UTC, webknjaz commented
@jeanas another round of review complete.

2024-01-25 09:23 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +.. _flit-core: https://pypi.org/project/flit-core/
Yes, but I'd like to point to Flit-core here, and preferably not to the main Flit docs, to emphasize the distinction. (The text is `` Flit-core_ -- developed with but separate from :ref:`Flit`. ``.)

2024-01-25 09:24 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +- Flit-core_ -- developed with but separate from :ref:`Flit`. A minimal and
Ah, I only see this now. Well, ok, why not.

2024-01-25 09:35 UTC, jeanas commented on source/guides/tool-recommendations.rst
I'm not sure I understand your meaning of “one-stop shop”. I'm not a native speaker, but I'd read it as “a tool which does everything”, not “a build backend that you should always use”. Also I feel there is already a lot of warning at the beginning of the page.

2024-01-25 09:38 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +
Well, the intent is that all tools presented are single-purpose, except those which are presented under “Integrated workflow tools” (but maybe that title should be more explicit?).

2024-01-25 09:43 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +============
I agree that this could be more precise, but if we make this change then I don't know how to call the section about Flit, Hatch, PDM, Pipenv and Poetry, which is currently called “Integrated workflow tools”. Thoughts?

2024-01-25 11:20 UTC, pfmoore commented on source/guides/tool-recommendations.rst
> +============
Fundamentally, my thought here is that we're trying too hard to classify the tools available in the ecosystem. We might be better leaving it to the tools themselves to choose how they want to present themselves, and not have any headings at all...

2024-01-25 11:30 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +============
I'm not enthusiastic. The problem that this page solves is “it's too hard to understand how the tools fit together”. If it doesn't classify them, then it doesn't serve its purpose well, IMO.

2024-01-25 18:21 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +.. _tox: https://tox.wiki
Marking this as resolved.

2024-01-25 18:21 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +.. _nox: https://nox.thea.codes
Marking this as resolved.

2024-01-25 18:23 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +.. _flit-core: https://pypi.org/project/flit-core/
Yeah, I wasn't completely sure about this one. Though, I see that you still applied the suggested change where I opted to link the doc that talks about `[build-system]` which is closer to the middle ground, it seems.

Marking this as resolved.

2024-01-25 18:23 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +common tools for this are tox_ and nox_.
Marking this as resolved.

2024-01-25 18:24 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- Flit-core_ -- developed with but separate from :ref:`Flit`. A minimal and
Marking this as resolved.

2024-01-25 18:26 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +command line applications that are distributed through PyPI.
I guess that's debatable. But fine. I don't have a better suggestion anyway. Do that.

2024-01-25 18:27 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +(especially on Linux).
Marking this as resolved.

2024-01-25 19:10 UTC, webknjaz commented on source/guides/tool-recommendations.rst
True. Let's wait for more opinions, then. And you're right, I did mean "a tool that does everything". Merely because a lot of people demand one without understanding that it entails. It seems to me that build backends are treated similarly even though, it's a different context. So I kinda wanted to assert the position once again in this section.

2024-01-25 19:11 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +
Perhaps yes. I also don't fully understand why tox/nox are ripped off of that section. I'd say they belong in it just as well.

2024-01-25 19:12 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +  the ``easy_install`` command (cf. :ref:`pip vs easy_install`).
Marking this as resolved.

2024-01-25 19:14 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +============
I suppose, I'd be in favor of combining these two sections into one. I feel like there's not enough differences in general to justify outing tox/nox vs. poetry/hatch et al.

2024-01-25 19:15 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +Package Index (PyPI)>`. It can install into the global environment or into
@jeanas @pfmoore ideas?

2024-01-25 19:16 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +extension is written in, such as Meson or CMake for C/C++, or Cargo for Rust,
@eli-schwartz are you okay with how it's been updated after your comment?

2024-01-25 19:23 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +to build distributable wheels.
Marking this as resolved.

2024-01-25 19:24 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- Flit-core, part of :ref:`Flit` (but usable standalone). It is meant to be a
Marking this as resolved.

2024-01-25 19:24 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- :ref:`setuptools`, the historical build backend. It can be configured
Marking this as resolved.

2024-01-25 19:25 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +- Hatchling, which is part of :ref:`Hatch` (but can be used without
Marking this as resolved.

2024-01-25 19:25 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +important because it also avoids conflicts with the system (which are the reason
Marking this as resolved.

2024-01-25 19:26 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +the dependencies of different applications. On Linux, pipx is especially
Marking this as resolved.

2024-01-25 19:26 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +consider :ref:`pipx`, which is a wrapper around pip that installs each
Marking this as resolved.

2024-01-25 19:27 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +in most Python installations.
Marking this as resolved.

2024-01-25 19:27 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +opened in order to enable the development of new backends serving certain users'
Marking this as resolved.

2024-01-25 19:27 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +example, the reason there exist many build backends is that the landscape was
Marking this as resolved.

2024-01-25 19:28 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +(PyPA, the umbrella organization which encompasses many packaging tools and
Marking this as resolved.

2024-01-25 19:29 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +distributions, uploading to PyPI, or creating and using lock files.
Marking this as resolved.

2024-01-25 19:45 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +     in pyproject.toml <writing-pyproject-toml>` whenever possible and keep
I'd like this to avoid ignoring the existence of `setup.cfg`:
```suggestion
     in pyproject.toml <writing-pyproject-toml>` (or :file:`setup.cfg`) whenever possible and keep
```

2024-01-25 19:45 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +  programmatically through the :file:`setup.py` file (but for basic metadata,
Okay, but I still want https://github.com/pypa/packaging.python.org/pull/1474/files#r1466878549.

I'll mark this as resolved in favor of that thread.

2024-01-25 19:46 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +The standard tool for this task is :ref:`twine`.
Sorry, I forgot about this one, done.

2024-01-25 19:47 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +The standard tool for this task is :ref:`twine`.
Marking this as resolved.

2024-01-25 19:52 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +For projects hosted on GitHub, PyPI recommends using :ref:`trusted publishing
Maybe, mention it's the PyPA?
```suggestion
For projects hosted on GitHub, the PyPA and the PyPI recommend using :ref:`trusted publishing
```

2024-01-25 19:53 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +For projects hosted on GitHub, PyPI recommends using :ref:`trusted publishing
Alternatively,
```suggestion
For projects hosted on GitHub, it is recommended to use the :ref:`trusted publishing
```

2024-01-25 19:56 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +For projects hosted on GitHub, PyPI recommends using :ref:`trusted publishing
I'll go for the second, it's simpler.

2024-01-25 20:06 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +============
It looks like not everyone has the same mental model as me on the nox/tox vs. Flit/Hatch/PDM/Pipenv/Poetry distinction.

For background, the two I've used the most are tox and Hatch, and I've sometimes used nox (in this repo). Tox is an environment manager that lets me define virtual environments and run tasks in them. Meanwhile, Hatch also does environment management and task execution, but also: building, uploading to PyPI, and managing Python interpreters (plus reformatting the code). So I view tox as a single-purpose tool (environment manager) along with other single-purpose tools (build, twine, pyenv) and Hatch as a tool that combines the features of lots of single-purpose tools (build, twine, tox, pyenv).

Merging these two sections is possible but I'm not sure how I'd fill the description.

Making the list task-oriented is also possible, but then Flit, Hatch, Poetry and PDM all are going to get listed in three categories (building, publishing, managing environments, except Flit doesn't manage environments).

This also makes me think that by my categorization, Pipenv should be with tox and nox. (For my defense, I know very little about it except that it sparked controversies years ago.)

2024-01-25 20:17 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +Package Index (PyPI)>`. It can install into the global environment or into
Maybe we should just remove this sentence? Or replace it with “It can install into arbitrary environments.”?

2024-01-25 20:50 UTC, pfmoore commented on source/guides/tool-recommendations.rst
> +Package Index (PyPI)>`. It can install into the global environment or into
I think remove the sentence. It isn't in the version of the text that's currently live, and I don't think it adds anything.

2024-01-25 21:01 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +Package Index (PyPI)>`. It can install into the global environment or into
Done.

2024-01-25 22:39 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +============
Technically, tox is used in the same way. People automate calling the underlying tools (like build or twine) and have tox as a workflow tool with a unified interfaces. It doesn't have some things built into the codebase but it also has plugins and stuff. So the use case for it is exactly the same, it just allows more low-level configuration. And it does implement some things that others don't (like parallel execution of several things), but that's just one of the differences. Other tools also differ between each other.

All of these are workflow tools. They just allow different levels of configuration and different have things implemented by default. But from the project contributor (end-user of those tools / the caller), they provide a CLI to call those processes as a part of their workflow.

@gaborbernat correct me if I'm missing something...

2024-01-25 22:41 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +Package Index (PyPI)>`. It can install into the global environment or into
Marking as resolved.

2024-01-26 04:01 UTC, gaborbernat commented on source/guides/tool-recommendations.rst
> +============
You're correct.

2024-01-30 10:44 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +============
Ok, I've merged the two sections.

2024-01-30 10:44 UTC, jeanas commented on source/guides/tool-recommendations.rst
> +
I've merged them.

2024-01-30 14:39 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +============
Marking as resolved, then.

2024-01-30 14:40 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +
Marking as resolved.

2024-01-30 14:41 UTC, webknjaz commented on source/guides/tool-recommendations.rst
> +command line applications that are distributed through PyPI.
Marking as resolved.

2024-02-01 02:24 UTC, webknjaz commented on source/guides/tool-recommendations.rst
@pfmoore do you have any thoughts on this?

2024-02-01 07:40 UTC, pfmoore commented on source/guides/tool-recommendations.rst
Looks ok to me. I’d say “a particular solution” rather than “a one-stop shop solution”. But otherwise it’s good.

2024-02-01 11:11 UTC, jeanas commented on source/guides/tool-recommendations.rst
Applied, with a slightly more concise wording.

2024-02-22 00:58 UTC, webknjaz approved these changes
I marked all the threads as resolved as there doesn't seem to be anything more actionable or blocking.

2024-02-22 01:06 UTC, webknjaz commented
The CI seems to be failing for an unrelated reason:
```console
(tutorials/installing-packages: line  444) broken    https://stackoverflow.com/a/14638025 - 403 Client Error: Forbidden for url: https://stackoverflow.com/a/14638025
```

The deps don't seem to differ compared to `main` so it's probably SO that's blocking HTTP requests from GH somehow. Will need to figure it out first.

2024-02-22 01:21 UTC, willingc commented
@webknjaz Maybe for CI, we change the SO link in the source to: https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix/14638025#14638025 It's where the CI link actually redirects if entered in the browser.

2024-02-22 01:29 UTC, webknjaz commented
@willingc that might work but needs checking. It should be done in a separate PR, though. An alternative would be adding a pattern to `linkcheck_ignore` if it's found that this problem exists with any StackOverflow links.

2024-02-22 13:55 UTC, webknjaz commented
@jeanas while that's being sorted out, what do you think about possibly linking https://pip.pypa.io/en/latest/topics/workflow/ / https://github.com/pypa/pip/pull/12503 in follow-ups? Not sure if it'd go in this specific doc, though.

2024-02-29 18:39 UTC, merged