Update glossary.rst
pypa/packaging.python.org pull request #1537
Opened 2024-04-30 10:18 UTC by Sam1320

fix seeming typo and add link to the correct term

2024-04-30 12:31 UTC, webknjaz requested changes
The phrasing is sub-optimal but it's correct: a build backend does indeed build an sdist or a wheel.

2024-05-02 10:29 UTC, Sam1320 commented
> The phrasing is sub-optimal but it's correct: a build backend does indeed build an sdist or a wheel.

Good point. What about the phrasing in the last commit? I feel is less ambiguous this way. I also removed the reference to "wheel" for clarity and also because its already inside the "Built Distribution" description.

2024-05-08 19:23 UTC, chrysle commented on source/glossary.rst
> +        and builds a :term:`source distribution <Source Distribution (or "sdist")>` or :term:`built distribution <Built Distribution>` from it.
Let's not make the line too long.

```suggestion
        and builds a :term:`source distribution <Source Distribution (or "sdist")>` or 
        :term:`built distribution <Built Distribution>` from it.
```

2024-05-13 16:48 UTC, sinoroc approved these changes
I wrote the initial glossary entry. I recall struggling to find a phrasing I would be entirely happy with, but gave up and settled on this awkward phrasing.

I guess, technically the step from sdist to wheel goes through unpacking the sdist into a source tree before this source tree to the build backend. I am not sure the build backends really do accept an sdist as input. So this new phrasing might be correct enough.

2024-05-15 15:44 UTC, webknjaz commented
> I am not sure the build backends really do accept an sdist as input.

They don't. The frontends do the unpacking as a part of the ephemeral build environment provisioning and call the backends against that dir on disk. cibuildwheel does that, and build recently got this feature. Pip was the first frontend to implement this logic, I think.

2024-05-15 15:51 UTC, webknjaz approved these changes

2024-05-15 16:00 UTC, merged

2024-05-23 11:33 UTC, Mohdhafez86 approved these changes