WIP: updated single_source_version with a much simpler page.
pypa/packaging.python.org pull request #1578
Opened 2024-07-25 16:47 UTC by ChrisBarker-NOAA

NOTE: this is quick draft I whipped out -- I"d like to get a read on whether something along these lines would be accepted before I put too much work into it.

As per discussion on Discourse, and #1276, here is a single source page that is far simpler, and essentially refers users to their build systems for instructions.

Questions:

Should we provide links to build systems docs?

Should we provide actual instructions for key build systems, e.g. setuptools -- these docs used to be largely about setuptools, but are no longer, so probably not, but it's nice to have one source of advice, too.

2024-07-25 16:59 UTC, tacaswell commented on source/single_source_version.rst
> +    print(a_package.__version__)
```suggestion
    print(a_package.__version__)
* In the metadata of the artifacts for each of the packaging ecosystems    
```

2024-07-25 17:07 UTC, webknjaz commented on source/single_source_version.rst
> +* It needs to be specified when building the package (e.g. in pyproject.toml)
```suggestion
* It needs to be specified when building the package (e.g. in :file:`pyproject.toml`)
```

2024-07-25 17:09 UTC, webknjaz commented on source/single_source_version.rst
> +* It needs to be specified when building the package (e.g. in pyproject.toml)
Also… Perhaps, not “specified” but “sourced”? There are cases when it's generated dynamically, based on the Git repo state, for example. In which case, it's not put into the metadata config file directly. I feel like “specified” here implies “hardcoded” which would be misleading. WDYT?

2024-07-25 18:17 UTC, ChrisBarker-NOAA commented on source/single_source_version.rst
> +    __version__ = importlib.metadata.version('the_distribution_name')
Actually, I think that whether having an attribute is a good idea or not is debatable, it's not debatable that **if** you have an attribute, everyone should use the same name -- and `__version__` is by far the most common convention.

So yes, it *does* have some importance and [should be] be followed :-)

If you really don't want to make that clear, then we can simply say that you can access the distribution version at run time with `importlib.metadata.version()`

2024-07-25 18:20 UTC, ChrisBarker-NOAA commented on source/single_source_version.rst
> +    print(a_package.__version__)
I'm accepting this, but I'm not sure how clear to newbies "In the metadata of the artifacts" is. 

Anyone have a idea for a better phrasing?

2024-07-25 18:25 UTC, ChrisBarker-NOAA commented on source/single_source_version.rst
> +* Some projects require that there be a version string available as an attribute in the importable module, e.g::
And we're back to the debate.

There is no consensus on whether `__version__` is a good idea or not.

I think this guide should be documenting the state of the practice -- not documenting what some people think are best practices.

Should a best practice be determined? I suppose so, but this PR is not the place to have that discussion.

"Why is this so far up?" Because it is a common practice. 

> . Ideally __version__ is mentioned 0 times in the main part of this guide 

That is not the ideal we all agree on -- that's EXACTLY why the previous PRs were derailed.

2024-07-25 21:14 UTC, bwoodsend commented on source/single_source_version.rst
> +    __version__ = importlib.metadata.version('the_distribution_name')
This is implying that `__version__` should be set by `importlib.metadata.version()` which is something that seemingly almost everyone opposes (it adds to startup time whilst solving none of the issues that the pro-`__version__` people have with using metadata). I think the two concepts need to be separated out:
* A package *may*, if the maintainers think it useful to be able to determine the version of the package from Python code without relying on a package manager's metadata, set a top level `__version__` attribute. The value of `__version__` and that passed to the build system can (and should) be kept in sync in ``:ref:`the build systems's recommended way <link to per build system breakout section>` ``.
* Should a package not set a top level `__version__` attribute, the version can still be accessed using `importlib.metadata.version("distribution_name")`. Since loading `importlib.metadata` has a non negligible startup cost, this lookup should ideally be deferred until when it's required (e.g. a `--version` flag is provided or an *About* dialog is opened)

2024-07-25 21:18 UTC, bwoodsend commented on source/single_source_version.rst
> +* Some projects require that there be a version string available as an attribute in the importable module, e.g::
How about just replacing `require` with `prefer`? That hopefully keeps both sides of the fence happy.

2024-07-25 21:51 UTC, ChrisBarker-NOAA commented on source/single_source_version.rst
> +-- I have no idea which are currently robust and maintained -- do we want to get into seeming endorsing particular tools in this doc?
great, thanks! -- I'll add those

2024-07-25 21:58 UTC, ChrisBarker-NOAA commented
By the way, when putting in links to the build system's docs, I noticed that they all support `__version__`, and at least flit does it by default.

So it is absolutely a common practice.

2024-07-26 01:02 UTC, tacaswell commented on source/single_source_version.rst
> +    print(a_package.__version__)
I was trying to refer to `.deb`, `.rpm`, ... for each of the downstream packaging ecosystems, not just the variety of Python side build tools.

2024-07-26 01:08 UTC, tacaswell commented on source/single_source_version.rst
> +Should a package not set a top level ``__version__`` attribute, the version can still be accessed using ``importlib.metadata.version("distribution_name")``.
```suggestion
In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
```

2024-07-26 01:17 UTC, tacaswell commented on source/single_source_version.rst
> +While different projects have different needs, it's important to make sure that there is a single source of truth for the version number.
```suggestion
To ensure that version numbers do not get out of sync, it is recommended that there is a single source of truth for the version number.
```

2024-07-26 01:28 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may, if the maintainers think it useful, to be able to determine the version of the package from Python code without relying on a package manager's metadata, set a top level ``__version__
```suggestion
* A package may set a top level ``__version__`` attribute to provide trivial runtime access to the version without needing to rely on any package manager's metadata.
```

2024-07-26 07:31 UTC, flying-sheep commented on source/single_source_version.rst
> +* Some projects require that there be a version string available as an attribute in the importable module, e.g::
I’m not trying to be complicated, I just really don’t know what is meant by “projects” here.
- individual packages that opted to use `__version__`? Then you could say something like “you might encounter a `__version__` variable set in `__init__.py` of a top level package, which is a convention that existed before standard methods to access package metadata existed”
- projects that access that variable automatically? I only know of one, and I wouldn’t recommend using it because of various issues that this is not the place for expanding.

2024-07-26 08:50 UTC, bwoodsend commented on source/single_source_version.rst
> +Consult your build system documentation for how to implement your preferred method.
Can we loose the word *implement* – it's too close to *roll your own DIY method*?
```suggestion
Consult your build system's documentation for their recommended method.
```

2024-07-26 08:50 UTC, bwoodsend commented on source/single_source_version.rst
> +3) The version string can be hard-coded into the source code -- either in a special purpose file, such as ``_version.txt``, or as a attribute in the ``__init__.py``, and the build system can extract
What exactly is this ``_version.txt``? It sounds uncomfortably like the approach where both the `setup.py` and the `__init__.py` both read from a shared text file and at least one release ends up defunct because the text file didn't get packaged properly. I'd be more comfortable if it wasn't mentioned.

2024-07-30 13:45 UTC, webknjaz commented on source/single_source_version.rst
> +* It needs to be specified when building the package (e.g. in :file:``pyproject.toml``)
```suggestion
* It needs to be specified when building the package (e.g. in :file:`pyproject.toml`)
```

2024-07-30 13:49 UTC, webknjaz commented on source/single_source_version.rst
> +.. _how_to_set_version_links:
It looks like other references use spaces. Perhaps, follow the same style?

2024-07-30 13:50 UTC, webknjaz commented on source/single_source_version.rst
> +2) The version can be hard-coded into the `pyproject.toml` file -- and the build system can copy it into other locations it may be required.
```suggestion
2) The version can be hard-coded into the :file:`pyproject.toml` file -- and the build system can copy it into other locations it may be required.
```

2024-07-30 13:51 UTC, webknjaz commented on source/single_source_version.rst
> +3) The version string can be hard-coded into the source code -- either in a special purpose file, such as ``_version.txt``, or as a attribute in the ``__init__.py``, and the build system can extract
```suggestion
3) The version string can be hard-coded into the source code -- either in a special purpose file, such as :file:`_version.txt`, or as a attribute in the :file:`__init__.py`, and the build system can extract it at build time.
```

2024-07-30 13:51 UTC, webknjaz commented on source/single_source_version.rst
>  :Last Reviewed: 2015-09-08
Update this before merging?

2024-07-30 13:52 UTC, webknjaz commented on source/single_source_version.rst
> +   - That will assure that it is properly assigned in the distribution file name, and in the installed package.
```suggestion
   - That will assure that it is properly assigned in the distribution file name, and in the installed package metadata.
```

2024-07-30 13:58 UTC, tacaswell commented on source/single_source_version.rst
> +3) The version string can be hard-coded into the source code -- either in a special purpose file, such as ``_version.txt``, or as a attribute in the ``__init__.py``, and the build system can extract
Every version of this is going to have failure modes.  One of the reasons I'm so in favor of the "git-tag-is-truth" and letting the build system sort it out is that in the past I have done broken releases using the "manually update hard code static strings" approach you are advocating @bwoodsend .

If the existence of a broken release eliminates a method, we would be unable to make any more releases 🤣 .

2024-07-30 13:59 UTC, webknjaz commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
I feel like this introduced a lot of controversy in the past. The way it's written here, it reads as though the “`__version__`” name specifically must be used and nothing else. The reality is that the variable name can be arbitrary. And it doesn't have to be top-level to work, either. Additionally, I see that here and in the previous point, the word “package” is used, but it means different things. Here, you talk about an importable, while there it's about a distribution. Can we do anything about this?

Could you try rephrasing this to say that an in-project importable module may have a hard-coded variable that can be wired into packaging metadata by name? We can mention that many projects use `__version__` for the variable name, but there is no standard mandating it to be that.

2024-07-30 14:01 UTC, webknjaz commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
Additionally, we should maybe mention that `__version__` may be populated from `importlib.metadata.version(__name__)` to provide the version string from installed packaging metadata as an importable.

2024-07-30 14:01 UTC, webknjaz commented on source/single_source_version.rst
> +1) If the code is in a version control system (VCS), e.g. git, then the version can be extracted from the VCS.
```suggestion
1) If the code is in a version control system (VCS), e.g. Git, then the version can be extracted from the VCS.
```

2024-07-30 14:06 UTC, webknjaz commented on source/single_source_version.rst
> +* `Hatch <https://hatch.pypa.io/1.9/version/>`_
Let's keep the order alphabetical here, as it is done in other parts of PyPUG. Otherwise, there's going to be debate regarding how to sort these. If we'd want to sort by adoption, we'd put `setuptools` first, of course.

2024-07-30 14:07 UTC, webknjaz commented on source/single_source_version.rst
> +* `Hatch <https://hatch.pypa.io/1.9/version/>`_
Additionally, Hatch is a build front-end. Their related build backend is called Hatchling.

2024-07-30 14:10 UTC, webknjaz commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
*(ref https://github.com/pypa/packaging.python.org/pull/1276#issuecomment-1709137303)*

2024-07-30 14:11 UTC, webknjaz commented
@ChrisBarker-NOAA could you try working my diagram from https://github.com/pypa/packaging.python.org/pull/1276#issuecomment-1709024176 into this?

P.S. Looks like there's a merge conflict to be solved.

2024-07-30 14:19 UTC, webknjaz commented on source/single_source_version.rst
> +    __version__ = importlib.metadata.version('the_distribution_name')
> This is implying that `__version__` should be set by `importlib.metadata.version()` which is something that seemingly almost everyone opposes (it adds to startup time whilst solving none of the issues that the pro-`__version__` people have with using metadata). I think the two concepts need to be separated out:
>

I would say that `__version__` should be set from `importlib.metadata.version()` as opposed to any other methods (it just can be called something else if somebody wants that).

>     * A package _may_, if the maintainers think it useful to be able to determine the version of the package from Python code without relying on a package manager's metadata, set a top level `__version__` attribute. The value of `__version__` and that passed to the build system can (and should) be kept in sync in `` :ref:`the build systems's recommended way <link to per build system breakout section>`  ``.

Agreed.

>     * Should a package not set a top level `__version__` attribute, the version can still be accessed using `importlib.metadata.version("distribution_name")`. Since loading `importlib.metadata` has a non negligible startup cost, this lookup should ideally be deferred until when it's required (e.g. a `--version` flag is provided or an _About_ dialog is opened)

The performance bit is a good point that I didn't consider. In that case, I'd recommend perhaps wrapping that into a module-level `__getattr__()` and computing it dynamically on first access (plus caching). This would still expose the same API/interface while pushing the lookup cost to the moment when it's needed.

2024-07-30 14:22 UTC, webknjaz commented on source/single_source_version.rst
> +* Some projects require that there be a version string available as an attribute in the importable module, e.g::
> individual packages that opted to use `__version__`? Then you could say something like “you might encounter a `__version__` variable set in `__init__.py` of a top level package, which is a convention that existed before standard methods to access package metadata existed”

I'd say “which is a convention some people follow that is not backed by standards, so feel free to opt for using any other name, depending on your use case”

2024-07-30 14:23 UTC, webknjaz commented on source/single_source_version.rst
> +* Some projects require that there be a version string available as an attribute in the importable module, e.g::
> What I’m saying here is that it should be documented as the convention it is: I’m pretty sure the right way to structure a guide is to first talk about standards and what to do achieve the challenge at hand (single sourcing the version) in conjunction with them, _then_ go for how to integrate conventions with the solution that has just been outlined.

I like this explanation.

2024-07-30 14:27 UTC, webknjaz commented on source/single_source_version.rst
> +-- I have no idea which are currently robust and maintained -- do we want to get into seeming endorsing particular tools in this doc?
@flying-sheep that's a tutorial. In guides, we specifically avoided any bias-based sorting to avoid the perception of one tool being more blessed than the other: https://packaging.python.org/en/latest/guides/tool-recommendations/#workflow-tools.

2024-07-30 14:34 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
```suggestion
* An importable module (formally packaged for distribution or not) may set a top level attribute to provide runtime access to the version of the installed package.  The defacto standard name for this attribute, dating back to at least 2011 and with wide community usage, is ``__version__``.   If the runtime version string is set, the distribution version should be kept in sync with the runtime version using :ref:`the build systems's recommended way <how_to_set_version_links>`.
```

2024-07-30 14:35 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
I suggested an edit in response to your comment.

2024-07-30 14:40 UTC, tacaswell commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
As near as I can tell, the push to get rid of `__version__` came from people protesting to this pattern (as a waste of runtime on import).

2024-07-30 14:44 UTC, webknjaz commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
Yeah, I'm starting to understand this better now, having read another thread: https://github.com/pypa/packaging.python.org/pull/1578#discussion_r1697056367

2024-07-30 14:47 UTC, webknjaz commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
@tacaswell perhaps, drop the “top-level” bit? Any level of nesting would work for as long as it's importable (which usually means not triggering imports of the deps…)

Also, it seems like “de facto” is spelled separately: https://en.wikipedia.org/wiki/De_facto.

2024-07-30 15:05 UTC, flying-sheep commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
It also comes from the fact that `__version__` is just a conventional place to duplicate the information in that already has a canonical place: not very pythonic

2024-07-30 15:31 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
Edited in-place to drop the top-level and fixed the typos.

2024-07-30 15:37 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
I also updated the year to be the first commit in Matplotlib that used `__version__` not the date of pep 396.

2024-07-30 15:53 UTC, tacaswell commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
> It also comes from the fact that __version__ is just a conventional place to duplicate the information in that already has a canonical place: not very pythonic

I respectfully, but completely disagree with this characterization.  `__version__` is the (defacto) standard which predates the existence of pip by at least 7 years (in Matplotlib I have a commit from 2004 using `__version__`) let alone the current push to bootstrap another (Python -specific) packaging ecosystem.

From my perspective the "duplicate" here is `dist-info` and as I noted on [discourse](https://discuss.python.org/t/please-make-package-version-go-away/58501/38) I am not worried about this.  Package managers (apt/dpkg, yum, pacman, conda, pip, ....) all need their own copy of the version metadata (and dependencies) to do their jobs.  This is OK and expected as each of these systems, and runtime, have different needs and hence (may) need their own copy of the information. 

It comes across as very hostile to invent a new place to put the version information and then declare the _existing_ location an upythonic duplicate!

As a thought experiment, if I said "We can scrap all of `dist-info`, we can query pacman to get all of it when we need it" I don't think it would be taken seriously.  "just use the metadata for pip" reads exactly the same to me.

2024-07-30 15:54 UTC, webknjaz commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
@flying-sheep I think that it's a bit more complicated than that. Duplicating the hardcoded values is bad. But if only one place is the actual source of the information and another just reflects the same information though a different API, that should be okay.

2024-07-30 15:55 UTC, webknjaz commented on source/single_source_version.rst
> +    __version__ = importlib.metadata.version('the_distribution_name')
Because there's no standard or a convention for disallowing this. I think, it's okay to highlight the problems and controversy. However, making imperative recommendations is reaching too far.

2024-07-30 15:57 UTC, webknjaz commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
@tacaswell I additionally edited your suggestion to remove the word “standard” as I believe it may be taken the wrong way.

2024-07-30 16:05 UTC, webknjaz commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
> "just use the metadata for pip" reads exactly the same to me.

@tacaswell TBF, from the Python packaging perspective, that is not “metadata for pip” by a standardized machine-readable information. That said, *if* a project is meant to be installed and the installed dist metadata contains a version, it's reasonable to threat it as the source for the most accurate information (even if it originated from some importables that could be accessed separately). From that perspective, it might be the source of truth in many contexts.

But it's rather tricky to explain/document this in an accessible manner. Hence, my suggestion to attempt visualizing these relationships with my diagram https://github.com/pypa/packaging.python.org/pull/1276#issuecomment-1709024176 (or something close to it).

2024-07-30 16:35 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
Thanks @webknjaz .

2024-07-30 17:15 UTC, flying-sheep commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
> if only one place is the actual source of the information and another just reflects the same information though a different API, that should be okay.

there should be one – and preferably only one – way to do it

the preferable way is the standard way

> I respectfully, but completely disagree with this characterization.

` __version__` is older, but it’s not standardized in a PEP, so it’s not the standard.

also putting that info into an **import package** doesn’t make sense, as the versioned unit is the **distribution package** – i.e. the thing that has the `dist-info` directory in it that contains the standard metadata. *most* distribution packages might come with one main import package (e.g. `Pillow` contains the import package `PIL`), but that’s not a rule, so the only place that will reliably match 1:1 with versioned units is the distribution package, complete with its metadata.

2024-07-30 20:17 UTC, ChrisBarker-NOAA commented
OK all -- I *think* I've addressed everyone's comments.

Also -- please see my updated initial comment -- trying to keep the scope of this very narrow.

2024-07-31 09:42 UTC, flying-sheep requested changes

2024-07-31 09:42 UTC, flying-sheep commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
This is not true

*Every* distribution package will *always* have standard metadata, so no “may” here

How about you delete that here …

```suggestion
```

2024-07-31 09:42 UTC, flying-sheep commented on source/single_source_version.rst
… then you add it back in the place where you mention standard metadata first:

```suggestion
   - the version is accessible at runtime via ``importlib.metadata.version("distribution_name")``.

```

2024-07-31 09:42 UTC, flying-sheep commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
Finally you need to improve the wording of “to provide runtime access”, because the line above mentioning `importlib.metadata.version` already describes how to get runtime access.

2024-07-31 13:20 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
As I keep saying, not everything is a "distribution package" and there is no guarantee that the thing you imported (which is what matters) is the thing that the packaging system thinks is installed.

2024-07-31 13:21 UTC, tacaswell commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
```suggestion
* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the imported package. If this is done, the value of ``__version__`` attribute and that used by the build system to set the distribution's version should be kept in sync in :ref:`the build systems's recommended way <how_to_set_version_links>`.
```

change "installed" (which is a packaging time concept) to "imported" (which is a runtime concept).

2024-07-31 15:38 UTC, webknjaz commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
So `s/may still/is always/` then.

2024-07-31 16:08 UTC, bwoodsend commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
I meant *may* to mean *can* here as opposed to *sometimes can* when I originally suggested that sentence. Just replacing *may* with either *can* or *is* sounds like the way to avoid that potential interpretation?

2024-07-31 18:34 UTC, flying-sheep commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
neither, the whole phrasing implies that `__version__` is the primary way to do it, and `importlib.metadata.version()` is a kind of fallback, which it isn’t. So more like

```diff
-In the cases where a package does not set a top level ``__version__`` attribute,
 the version
-may still be accessible using
+is accessible at runtime via
 ``importlib.metadata.version("distribution_name")``.
```

2024-07-31 18:38 UTC, flying-sheep commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
Yes, everything this guide is about is contained in a distribution package. .deb/.rpm, … packages contain them. conda packages contain them.

There are some counter examples like fintech, but `__version__` doesn’t apply to these either.

2024-07-31 18:38 UTC, flying-sheep commented on source/single_source_version.rst
@tacaswell why the :-1:? what’s wrong?

2024-07-31 18:56 UTC, tacaswell commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
If I delete the `dist-info` folder does anything break at runtime?

2024-07-31 18:57 UTC, tacaswell commented on source/single_source_version.rst
I do not think either edit should be made.

2024-07-31 19:01 UTC, abravalheri commented on source/single_source_version.rst
> +In the cases where a package does not set a top level ``__version__`` attribute, the version may still be accessible using ``importlib.metadata.version("distribution_name")``.
@tacaswell, if you manually delete the `dist-info` folder lots of stuff will break at runtime (e.g. entry-points). I believe that only package managers are meant to modify such files.

For every distribution installed using the default procedure a corresponding `dist-info` is supposed to be present (otherwise the system is in an inconsistent state).

2024-07-31 19:05 UTC, abravalheri commented on source/single_source_version.rst
> +* A package may set a top level ``__version__`` attribute to provide runtime access to the version of the installed package. If this is done, the value of ``__version__`` attribute and that used by t
> As I keep saying, not everything is a "distribution package" and there is no guarantee that the thing you imported (which is what matters) is the thing that the packaging system thinks is installed.


I think that for the sake of simplicity developers should seek to align versions of all import packages with the version of the corresponding distribution package and differ only if there is a good reason for doing so. Having `pip install distname==2.0` resulting in `__import__("distname").__version__ == "1.0"` would be too chaotic otherwise. Also in the case the same distribution contains multiple import packages (which is already considered an edge case), it would be good practice to coincide them unless there is a good reason not to.

2024-07-31 22:30 UTC, ChrisBarker-NOAA commented
> @ChrisBarker-NOAA could you try working my diagram from [#1276 (comment)](https://github.com/pypa/packaging.python.org/pull/1276#issuecomment-1709024176) into this?

Hmm -- I'm trying to keep this page as simple as possible and not get into too many tech details.

But if the Doc Editors (who are they?) think it should be included, then sure.

2024-07-31 22:31 UTC, ChrisBarker-NOAA commented
By the way, I have not idea what to do with this:

The required .readthedocs.yaml configuration file was not found at repository's root. Learn how to use this file in our [configuration file tutorial](https://docs.readthedocs.io/en/stable/config-file/index.html).

But I suppose that explains the lack of a preview.

2024-07-31 22:50 UTC, webknjaz commented
> By the way, I have not idea what to do with this:
> 
> The required .readthedocs.yaml configuration file was not found at repository's root. Learn how to use this file in our [configuration file tutorial](https://docs.readthedocs.io/en/stable/config-file/index.html).
> 
> But I suppose that explains the lack of a preview.

I believe RTD would build against the merge commit of your PR branch into main. Since there's merge conflicts, there's no merge commit, hence no place to check the config from.

Action item: address the merge conflicts (I personally like rebasing) and it should work then.

2024-08-01 00:00 UTC, closed without merging

2024-08-01 00:14 UTC, ChrisBarker-NOAA commented
Turns out I had not synced my fork before doing this, and it was a serious mess, due to the restructuring of the docs. So I wan't able to fix it in place.

But the discussion had gotten pretty convoluted anyway, so a new PR has its benifits:

#1580