Add notes on runtime version access
pypa/packaging.python.org pull request #1607
Opened 2024-10-06 07:47 UTC by ncoghlan

Also redirects the obsolete single-source version guide to the updated single-source version discussion.

2024-10-06 07:48 UTC, ncoghlan commented
Seeing if we can make HTTP redirects work without an extension like https://pypi.org/project/sphinx-reredirects/

2024-10-06 08:03 UTC, ncoghlan commented
Found a surprising CPython docs issue here: https://github.com/python/cpython/issues/125018

2024-10-06 08:12 UTC, webknjaz commented
@ncoghlan thanks for taking this on! I was hoping to take a stub at actually writing some content, but it doesn't look like I'm going to get to that anytime soon, so I guess this is the way.

Seeing that you're repeating some of #1276, I think it would be nice to add a `Co-Authored-By: wim glenn <hey@wimglenn.com>` trailer to Git commits… That's possible via `git commit --amend --trailer='wim glenn <hey@wimglenn.com>'`. WDYT?

2024-10-06 08:12 UTC, webknjaz approved these changes

2024-10-06 11:51 UTC, ncoghlan commented on source/discussions/versioning.rst
> +   '23.3.2'
In the thread that prompted this updated PR, one of the key points of confusion was the assumption that because PEP 396 was rejected, packages shouldn't be setting `__version__` at all. The reason that PEP was rejected as a general requirement is the fact that the distribution package version and the import package API version *aren't* required to be the same (the names aren't even required to be the same).

Even though these versions are *often* the same, they're technically versioning different things (the distribution package and the import package's API), so requiring a specific relationship between them isn't valid.

The updated text in this PR aims to make that distinction clearer.

2024-10-06 14:13 UTC, ChrisBarker-NOAA requested changes
Thanks for finishing this up!

2024-10-06 14:13 UTC, ChrisBarker-NOAA commented on source/discussions/versioning.rst
> +distribution package version information (see the rejected proposal in
I really wish Barry had Withdrawn, rather than Rejected, that one -- which I think is closer to the truth, but oh well. In any case, this text isn't opinionated -- thanks!

2024-10-06 14:13 UTC, ChrisBarker-NOAA commented on source/discussions/single-source-version.rst
> +To ensure that version numbers do not get out of sync, it may be sufficient to add
This feels out of place to me -- perhaps it can be moved to after the discussion of how to single source.

Having the build system do it for you is not an alternative to a test -- a test is a way to ensure that it was done correctly, regardless of the approach. Now that i think about it, relying on a test for a non-DRY method is an alternative to the DRY method, not the other way around.

[But I'm word-smithing here, not a blocker.]

2024-10-06 14:41 UTC, ncoghlan commented on source/discussions/versioning.rst
> +distribution package version information (see the rejected proposal in
Heh, I had exactly the same thought when I was re-reading the PEP to check exactly why it was rejected :)

2024-10-06 14:42 UTC, ncoghlan commented
I posted a PR for the lack of semantic reference targets in the CPython docs, so assuming that review goes smoothly I may be able to fix this PR to use proper references before it gets merged: https://github.com/python/cpython/pull/125027

2024-10-06 14:47 UTC, ncoghlan commented on source/discussions/single-source-version.rst
> +To ensure that version numbers do not get out of sync, it may be sufficient to add
Yeah, I was genuinely unsure where best to include that note.

The other option I meant to add, but forgot to mention in the initial draft, is that https://peps.python.org/pep-0562/ now makes it possible to *lazily* populate `__version__` from `importlib.metadata.version(__spec__.name)`, so I'll definitely be making another pass over that bit (since it eliminates the main downside of doing that implicitly: the upfront import time cost, even if nobody ever accesses `__version__` on a given run).

2024-10-06 14:55 UTC, eli-schwartz commented on source/discussions/versioning.rst
> +Library publishers wishing to ensure their reported distribution package and
This focuses on libraries specifically, but I'm not sure why. Applications, both CLI and GUI, often have the same concern -- more strongly for CLI than for GUI, as the latter are usually not installable via python packaging at all due to deficiencies in the wheel format.

Applications usually *must* report their version number at runtime somehow, and at least one of those locations is typically `progname --version` which is desired to complete as fast as possible in as few imports as possible. Applications may also support being packaged in a zipapp or PyInstaller or similar, in which case there is no "distribution metadata" anyway (but for the sake of people `pip install`ing the CLI application it's desirable to be able to specify the version to install, regardless of whether "distribution metadata" is also created).

All in all, the references to "libraries" comes across as weird to me.

2024-10-06 15:02 UTC, eli-schwartz commented on source/discussions/single-source-version.rst
> +To ensure that version numbers do not get out of sync, it may be sufficient to add
Note that lazy population makes the assumption that the rationale for avoiding importlib.metadata is the cost "when not accessed anyway" which I feel is a fairly big assumption even for libraries (why write even more complicated code just to make a certain part of your API even slower when you can just do it right to begin with for less code, less maintenance, and better performance?).

 But it's completely invalid for the application use case as the primary concern there is to make the happy path of running the application just to report the version be as fast as possible -- and of course that's the one case where you're absolutely guaranteed to (slowly) access this attribute. The rest of the time, you may not care if the attribute is eagerly loaded and incurs a universal slowdown since the application is probably doing loads of work anyway and importing the importlib.metadata indirector (sic) could end up drowned out in the noise.

2024-10-06 15:15 UTC, pradyunsg commented on source/discussions/versioning.rst
> +   >>> import pip
I would prefer if we used something other than pip as an example of this. 😅

We actively discourage using pip as an importable package.

2024-10-06 17:53 UTC, merwok commented on source/guides/single-sourcing-package-version.rst
> +If the page doesn't automatically refresh, click :ref:`here <single-source-version>`.
«here» is not a good practice for link text 🙂 

```suggestion
If the page doesn't automatically refresh, see :ref:`single-source-version`.
```

2024-10-06 18:09 UTC, bwoodsend commented on source/discussions/single-source-version.rst
> +   such as :file:`_version.txt`, or as an attribute in a module, such as :file:`__init__.py`, and the build
I don't want to start a big debate here so if there's any conflict then just say no and resolve this comment.

Could we not mention version files? Seeing defunct packages on PyPI produce `FileNotFoundError: version.txt` on build because they forgot to add the file to their manifest is my primary motivation for being so opposed to `__version__` attributes in the first place.

2024-10-06 21:27 UTC, webknjaz commented
@ncoghlan so I made a mistake in the suggested attribution command earlier (I've updated that comment to correct it since) and missed a chunk of the trailer in it, which is why GitHub didn't attribute that commit to wim glenn. It was supposed to be `git commit --amend --trailer='Co-Authored-By: wim glenn <hey@wimglenn.com>'`.
I must note, however, that this command modifies the last commit, and you seem to have produced a separate empty commit (I'm guessing with `--allow-empty`).

Normally, I'd suggest just putting this trailer as a `Co-Authored-By: wim glenn <hey@wimglenn.com>` line into the merge commit and use the squash button. But this repository is set up to use natural merge when accepting PRs, so you won't have this option. All of the individual commits here will become a part of `main` and the empty commit will be what's credited. So my recommendation is to squash the commits locally, with an interactive rebase, adding that line to the resulting commit message. This can be done right before merging.

2024-10-07 08:32 UTC, ncoghlan reviewed
Assorted review comments addressed. Build will currently fail, as I went back to using semantic cross-references to `importlib.metadata` APIs (in anticipation of getting the stdlib docs update PR and its backports merged)

2024-10-07 08:43 UTC, ncoghlan commented on source/discussions/single-source-version.rst
> +To ensure that version numbers do not get out of sync, it may be sufficient to add
I reworked this to move the testing recommendation to the end, and ultimately decided not to mention the lazy loading idea (since @eli-schwartz is right and it's basically the worst possible solution).

2024-10-07 08:49 UTC, ncoghlan commented
@webknjaz Huh, interesting, I hadn't realised that squash merges could be disabled outright (although I can see what enabled the merge queue would do so). I'll do the full squash on the PR branch just before merge (since it messes up the comment threads if I do it beforehand)

2024-10-07 11:41 UTC, webknjaz commented
@ncoghlan yep, you're right. Technically that's not disabled directly but when merge queues is required for a branch, it only lets one select a single method. Overriding it is possible for admins as they'd be able to bypass the merge queues when force-merging.

2024-10-08 07:41 UTC, ncoghlan commented
The semantic link targets are live on docs.python.org, so I'll remove the `!` prefixes from the PR (since https://docs.python.org/3/library/importlib.metadata.html#importlib.metadata.version is a valid target now).

2024-10-08 07:43 UTC, ncoghlan commented on source/discussions/single-source-version.rst
> +as :func:`!importlib.metadata.version` reports for the distribution package
```suggestion
as :func:`importlib.metadata.version` reports for the distribution package
```

2024-10-08 07:43 UTC, ncoghlan commented on source/discussions/versioning.rst
> +using the standard library's :func:`!importlib.metadata.version` function::
```suggestion
using the standard library's :func:`importlib.metadata.version` function::
```

2024-10-08 07:43 UTC, ncoghlan commented on source/discussions/versioning.rst
> +   :func:`!importlib.metadata.packages_distributions` function. This means that
```suggestion
   :func:`importlib.metadata.packages_distributions` function. This means that
```

2024-10-08 17:59 UTC, tabedzki reviewed
Lines 101-114 seem to overlap with lines 154-167 since they both cover the versioning dynamically though only one points to the updated "single source version" discussion page while the other doesn't. 

Should we (1) update the example for static vs dynamic to not be version but some other attribute, (2) update lines 113-114 to point to the discussion as well, or (3) remove one of these two sections?

I will note that the [#1276](https://github.com/pypa/packaging.python.org/pull/1276/commits/cde56ce42eb10c77ad646486983bd923cddc29fa) only had this included in the static vs dynamic section and did not include it under version section itself.

2024-10-08 18:16 UTC, tabedzki commented on source/guides/writing-pyproject-toml.rst
> +discussion for more details.
Lines [101-114](https://github.com/ncoghlan/packaging.python.org/blob/bbf6d6618ebebaf0b609c637a2e107f0a1556f4e/source/guides/writing-pyproject-toml.rst?plain=1#L101-L114) seem to overlap with lines [154-167](https://github.com/ncoghlan/packaging.python.org/blob/bbf6d6618ebebaf0b609c637a2e107f0a1556f4e/source/guides/writing-pyproject-toml.rst?plain=1#L154-L167) since they both cover the versioning dynamically though only one points to the updated "single source version" discussion page while the other doesn't.

Should we (1) update the example for static vs dynamic to not be version but some other attribute, (2) update lines [113-114](https://github.com/ncoghlan/packaging.python.org/blob/bbf6d6618ebebaf0b609c637a2e107f0a1556f4e/source/guides/writing-pyproject-toml.rst?plain=1#L113-L114) to point to the discussion as well, or (3) remove one of these two sections?

I will note that the [#1276](https://github.com/pypa/packaging.python.org/pull/1276/commits/cde56ce42eb10c77ad646486983bd923cddc29fa) only had this included in the static vs dynamic section and did not include it under version section itself.

2024-10-08 19:28 UTC, ChrisBarker-NOAA commented on source/guides/writing-pyproject-toml.rst
> +discussion for more details.
>  (1) update the example for static vs dynamic to not be version but some other attribute

Please keep version as an example, it's one of the most common use cases.

I think it's OK for 113-114 to be like it is -- refer to the build system docs. while version is the example, that section is not specifically about version.

101--114 could be shortened some, so as not to be too repetitive.

2024-10-12 05:13 UTC, ncoghlan commented on source/guides/writing-pyproject-toml.rst
> +discussion for more details.
I'd prefer to keep the scope of this PR's effect on the pyproject.toml guide to just simplifying the link reference. Happy to take a look at a separate PR tightening up the wording, though.

2024-10-12 05:15 UTC, ncoghlan commented
Given the +1's above and the lack of objections on the discuss.python.org thread, I'm going to go ahead and merge this one to give us a solid foundation for any future updates.

2024-10-12 05:27 UTC, ncoghlan commented
@webknjaz Rather than force-pushing to this branch, I decided it would be cleaner to supersede this PR with a new one (so the comment history doesn't get messed up), but that does mean the new PR needs approval from a second reviewer: #1612

2024-10-12 05:27 UTC, closed without merging