Update conf.py automatically keep copyright date the current year
pypa/packaging.python.org pull request #1762
Opened 2024-12-19 22:11 UTC by clintonsteiner

2024-12-19 22:49 UTC, webknjaz commented
The correct fix for linkcheck is described in #1744. Submit it separately.
Don't change the documents, that's not necessary.
As for the copyright, I'm not sure. It might be a good idea to just keep the first year. FWIW, copyright is supposed to signal the content creation. Updating it to a random year just because somebody restarted Sphinx is plain wrong.

2024-12-19 23:39 UTC, clintonsteiner commented
Removed - then began reading about copyrights
I'll stand by the change as if we are using it incorrectly we should keep it up to date - stating that pypa still has copyright on the material

Agree with what you said that it doesn't serve a purpose, however it may as well indicate that the website is still maintained

2024-12-23 03:14 UTC, ncoghlan commented
The question of static years in copyright notices came up recently(ish) for the main CPython documentation:

* Issue for the change (with advice from PSF legal counsel): https://github.com/python/cpython/issues/126133
* Resulting ongoing guidance (just list the *first* year, not subsequent years): https://devguide.python.org/getting-started/pull-request-lifecycle/#copyrights

The CPython reasoning is applicable here as well, so just saying "2013" would make sense.

(there are other issues with the notice due to the PyPA not really existing in any legal sense, but we're not going to try to sue anyone for copyright infringement over the packaging guide, so it doesn't particularly bother me)

2024-12-23 03:17 UTC, ncoghlan commented
For reference, #1767 has the linkcheck workaround to avoid having pypi.org anchor checks fail due to the active botscraping load reduction defences.

2024-12-26 19:28 UTC, webknjaz requested changes
> keep it up to date [...] indicate that the website is still maintained

Well, this would be just wrong because it has nothing to do with the maintenance status. It's just the indication that somebody wanted to update this string, and that's about it. Here's another explanation why this is pointless: https://hynek.me/til/copyright-years/.

So I don't think that creating a false feeling of maintenance for arbitrary individuals on the internet is enough justification for contributing to the confusion further.

An acceptable change would be deleting the end-year or both years. The LF and many other respected organizations and individuals all agree on this generic guidance.

Another possible improvement here would be extending “PyPA” to “PyPA with PyPUG maintainers and contributors”. Technically, the contributors do not surrender their copyright to us fully, as I understand (since we don't demand that people sign a CLA).

2025-01-07 09:20 UTC, clintonsteiner commented
@webknjaz I actually disagree with you here
The examples listed such as LF list current year for copyright
PyPi uses copyright current year here
Python.org uses Copyright beg year to cur year
Linux foundation uses copyright current year

![image](https://github.com/user-attachments/assets/5fa0e588-d1bf-4216-aa38-c499e70252b3)
[Linux Foundation](https://training.linuxfoundation.org/?campaignid=21372675077&adgroupid=171974510868&creative=704304945812&matchtype=e&network=g&device=c&keyword=linux%20foundation&hsa_acc=8666746580&hsa_cam=21372675077&hsa_grp=171974510868&hsa_ad=704304945812&hsa_src=g&hsa_tgt=kwd-319242482088&hsa_kw=linux%20foundation&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gad_source=1&gbraid=0AAAAAD2R-lqgn4NVlj9HU6JIopz--dkKG&gclid=Cj0KCQiAvvO7BhC-ARIsAGFyToVlfil6jawEHqr9jNH3BkR4fqvMJ6V5GEJi7OUkibIMvHB3r1J_4X8aApI_EALw_wcB&utm_source=google&utm_medium=paid-search&utm_campaign=24q2-evergreen-lf_training&utm_term=tnc-na-search-lf-brand&utm_content=eg_rsa&utm_term=linux%20foundation&utm_campaign=tnc-na-search-lf)

Python software foundation
![image](https://github.com/user-attachments/assets/4f46a281-ba6c-42ae-b756-61988d2b64ef)
[Pypi](https://pypi.org/manage/account/#account-emails)

Python.org
![image](https://github.com/user-attachments/assets/819b27d0-b5a6-4553-918b-fce5b36b9332)
[Python.org](https://www.python.org/psf-landing/)

2025-01-08 12:33 UTC, clintonsteiner commented
This is being hotly contested in the public forum of reddit https://www.reddit.com/r/webdev/comments/1hwbsou/do_you_not_code_the_copyright_year_to_be_dynamic/
Seems the community is split 50-50, although the logic shoudln't matter, companies keep the year up to date so it doesn't look abandoned
I'd argue to do the same here, but splitting hairs on a unimportant thing

2025-01-14 20:21 UTC, closed without merging