PEP 627: Recording installed projects
pypa/packaging.python.org pull request #756
Opened 2020-07-16 11:30 UTC by encukou

Hello,
This is my proposed update to "Recording installed distributions", moving from [PEP 376](https://www.python.org/dev/peps/pep-0376/) to a specification under PyPA.
See:
* [The PEP](https://github.com/encukou/peps/blob/pep-0627/pep-0627.rst) (currently in a PR) for the rationales;
* the [Discourse thread](https://discuss.python.org/t/pep-627/4126) for discussion;
* the [added page](https://github.com/encukou/packaging.python.org/blob/pep-627-recording-installed-projects/source/specifications/recording-installed-packages.rst) rendered by GitHub.

This should not be merged until the PEP is accepted, but the proposal needs to be available while the PEP is reviewed.

2020-09-02 19:11 UTC, pfmoore requested changes

2020-09-02 19:11 UTC, pfmoore commented on source/specifications/recording-installed-packages.rst
> +
Can we say that the encoding SHOULD be UTF-8? That's reasonable advice, and doesn't invalidate anything while still offering guidance for the future?

2020-09-03 05:48 UTC, pradyunsg commented on source/specifications/recording-installed-packages.rst
> +`version` fields corresponding to :ref:`core-metadata`.
@pfmoore PEP 627 is this PEP. Did you mean that a sentence like this should be added? Or, did you mean to reference some other PEP? Or am I confused? 🙃

2020-09-03 09:07 UTC, pfmoore commented on source/specifications/recording-installed-packages.rst
> +`version` fields corresponding to :ref:`core-metadata`.
Bah. I meant PEP 503. The link's right, at least.

2020-09-03 15:00 UTC, encukou commented on source/specifications/recording-installed-packages.rst
> +
If we already know what it should be, and all the tools use UTF-8 already, why not standardize it right now?
If some tools have reason to use something else, or we don't know, then I believe there should be a PEP about it.

Myself, I am not sure if this should be UTF-8 or the filesystem encoding – I happen to work on systems where they're the same.

2020-09-03 15:12 UTC, encukou commented on source/specifications/recording-installed-packages.rst
> +packages (commonly, the ``site-packages`` directory).
I did have a bit of trouble wording this, and I'm sure it can still be made clearer, but I don't think your suggestion is better.
Formally, *path* may be [...] relative to *the directory containing the ``.dist-info`` directory*, but that is quite a mouthful and hard to keep in your brain as you read on.
Usually, *the directory containing the ``.dist-info`` directory* *is* ``site-packages``, and unless you're after the formal specification, you should really be thinking ``site-packages`` here.

It is not the case that *the directory containing the ``.dist-info`` directory* is **in** ``site-packages``. They're the same.

The same wording appears a few sections up:
> ## The .dist-info directory
> Each project installed from a distribution must, in addition to files,
> install a "``.dist-info``" directory located alongside importable modules and
> packages (commonly, the ``site-packages`` directory).

2020-09-03 15:17 UTC, encukou commented on source/specifications/recording-installed-packages.rst
> +Each project installed from a distribution shall, in addition to files,
OK.
(I won't capitalize the term; if we want that I'd also want to add the [RFC 2119](https://tools.ietf.org/html/rfc2119) blurb, ideally in all the PyPA specs.)

2020-09-03 15:38 UTC, pfmoore commented on source/specifications/recording-installed-packages.rst
> +
Pip uses UTF-8, so it's probably always UTF-8 right now. I don't want to force PEP 627 back through another round of discussion by mandating anything, so SHOULD makes it advisory but clear. We can change SHOULD to MUST in a follow-up discussion/PEP.

(Given that the wheel spec says somewhere that filenames must be encoded in UTF-8 in the zip file, I don't see how we could ever end up with something on the filesystem for which UTF-8 didn't work).

If you're uncomfortable with it, though, I'm fine with you doing what you prefer. That's the basis I approved the PEP on.

2020-09-03 15:40 UTC, pfmoore commented on source/specifications/recording-installed-packages.rst
> +packages (commonly, the ``site-packages`` directory).
OK, I'm fine with leaving this.

2020-09-03 16:04 UTC, pfmoore commented on source/specifications/recording-installed-packages.rst
> +
OK, cool.

2020-09-03 16:04 UTC, pfmoore approved these changes

2020-09-03 16:07 UTC, merged