Specify PEP 621
pypa/packaging.python.org pull request #797
Opened 2020-11-23 01:15 UTC by brettcannon

2020-11-23 10:09 UTC, pfmoore requested changes

2020-11-23 10:09 UTC, pfmoore commented on source/specifications/declaring-project-metadata.rst
> +  data for it.
Maybe clarify this? Backends may determine dynamically that the correct value is "omitted", and therefore the final value won't be present, without that being an error. Maybe just add a second sentence to that effect?

2020-11-23 10:09 UTC, pfmoore commented on source/specifications/declaring-project-metadata.rst
> +
There should be a brief description here of what "static" and "dynamic" mean, before you use the terms in the next paragraph.

2020-11-25 02:32 UTC, brettcannon commented
@pfmoore PTAL

2020-11-25 07:55 UTC, pfmoore approved these changes

2020-11-25 18:50 UTC, brettcannon commented
@pfmoore do you want me to go ahead and merge this, or wait until PEP 621 is no longer provisional?

2020-11-25 18:58 UTC, pfmoore commented
I think it should be merged now.

2020-11-25 18:59 UTC, merged