Use `python -m pip` instead of just `pip` in pip invocations
pypa/packaging.python.org pull request #808
Opened 2020-12-29 21:23 UTC by scop

Stdlib has done that since 2014, and pip's own docs do that too.

Note: python vs python3 is used inconsistently between files in the
tree; this attempts to follow the existing per-file convention and does
not modify/unify it.

Note #2: this change doesn't intentlonally wrap any lines that became "long" as a result of these changes for easier reviewability. I can do that too if that's preferred, let me know.

2021-02-03 10:32 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/a166e08adae30f2886d975d7ba75a80c/tenor.gif)

2021-02-03 14:24 UTC, webknjaz requested changes

2021-02-03 14:24 UTC, webknjaz commented on source/discussions/install-requires-vs-requirements.rst
> +just a list of :ref:`pip:python -m pip install` arguments placed into a file.
It's not a command but a reference to a label in pip's Sphinx docs. You must use an existing label for it to work. Here's a list of what's available: https://webknjaz.github.io/intersphinx-untangled/pip.pypa.io/.

```suggestion
just a list of :ref:`pip:pip install` arguments placed into a file.
```

2021-02-03 14:24 UTC, webknjaz commented on source/discussions/pip-vs-easy-install.rst
> +|                              |``python -m pip freeze``)             |                               |
Not sure if it's worth doing this in tables...

2021-02-03 14:24 UTC, webknjaz commented on source/guides/index-mirrors-and-caches.rst
> +   the requirements using `python -m pip wheel
I wouldn't use it in links, only in code blocks.

2021-02-03 14:24 UTC, webknjaz commented on source/tutorials/installing-packages.rst
> +   with ``python3`` and the ``python -m pip`` command with ``python3 -m pip3 --user``. Do *not*
```suggestion
   with ``python3`` and the ``python -m pip`` command with ``python3 -m pip --user``. Do *not*
```
There's no module called `pip3`, only an executable console script.

2021-02-03 14:24 UTC, webknjaz commented on source/tutorials/managing-dependencies.rst
>  .. code-block:: python
While you're here, fix this:
```suggestion
.. code-block:: bash
```

2021-02-03 14:24 UTC, webknjaz commented on source/tutorials/packaging-projects.rst
> +* Install your package from the real PyPI using ``python3 -m pip install [your-package]``.
Why don't we keep consistency with other places?
```suggestion
* Install your package from the real PyPI using ``python -m pip install [your-package]``.
```

2021-02-07 06:50 UTC, scop commented on source/tutorials/packaging-projects.rst
> +* Install your package from the real PyPI using ``python3 -m pip install [your-package]``.
This file uses `python3` for all its samples, using that here specifically to keep the consistency within the file.

2021-02-07 06:52 UTC, scop commented on source/discussions/pip-vs-easy-install.rst
> +|                              |``python -m pip freeze``)             |                               |
I don't see a reason to be inconsistent, but if you feel strongly about this, feel free to push a change to the PR branch.

2021-02-07 06:53 UTC, scop commented on source/guides/index-mirrors-and-caches.rst
> +   the requirements using `python -m pip wheel
Same as above re using in tables.

2021-02-08 00:40 UTC, webknjaz commented on source/discussions/pip-vs-easy-install.rst
> +|                              |``python -m pip freeze``)             |                               |
I don't have access to that. Not all org members have commit bits in all the repos.

My understanding is that this compares rather abstract ways of doing things and not ways of invoking pip with a specific interpreter. It makes sense to have `python -m` in code blocks as they are what the readers would copy-and-paste most often. But in other places, the long-form seems to be overkill...

2021-02-08 00:43 UTC, webknjaz approved these changes
While I've expressed my preference to have some things done slightly differently, that is not to be considered as a blocker. LGTM regardless of whether the suggestions are incorporated or not.

2021-02-08 19:47 UTC, di approved these changes

2021-02-08 19:50 UTC, merged