This commit adds the manimce deprecate documentation in RST format
pypa/packaging.python.org pull request #884
Opened 2021-04-18 19:44 UTC by dayvheed

2021-04-22 18:48 UTC, naveen521kk commented on source/mamince_release_documentation.rst
> +deprecated going forward.
Aren't you writing a general guide about "how to deprecate a package"?

2021-04-25 16:34 UTC, dayvheed commented on source/mamince_release_documentation.rst
> +deprecated going forward.
From a developer standpoint? I will love to. Please can you give me a little insight of what you would be expecting in the article

2021-04-25 19:28 UTC, webknjaz requested changes
Thanks for this effort but it looks like you've misunderstood the task.

The project https://packaging.python.org aims to provide generic guides for the package maintainers on how to do things related to this topic. We don't need to publish user-facing instructions for every other project on the internet.

To specify the task clearer: we need a guide answering the question "Given that I'm a project maintainer, what steps should I take in order to deprecate it?"

2021-04-26 07:59 UTC, dayvheed commented
> Thanks for this effort but it looks like you've misunderstood the task.
> 
> The project https://packaging.python.org aims to provide generic guides for the package maintainers on how to do things related to this topic. We don't need to publish user-facing instructions for every other project on the internet.
> 
> To specify the task clearer: we need a guide answering the question "Given that I'm a project maintainer, what steps should I take in order to deprecate it?"

Alright. Thanks for the clarification. I will edit and come up another write up

2021-05-16 11:51 UTC, webknjaz commented
I think I'll close this for now. Feel free to open up a new pull request with the updated guide.

2021-05-16 11:51 UTC, closed without merging