binary-extensions: add cibuildwheel and multibuild
pypa/packaging.python.org pull request #910
Opened 2021-06-01 14:55 UTC by henryiii

This adds a mention of pypa's cibuildwheel and multibuild here before going into the (highly outdated, currently) specifics of building wheels. For most users, this likely is the correct place to go, rather than trying to set things up themselves. For those who might want to do things themselves, the following sections still need updating.

2021-06-27 10:32 UTC, bhrutledge requested changes
Thanks for starting to improve this doc. I have no direct experience with binary extensions, so it's a good read for me. There's one spelling fix, plus some suggestions for clarity.

2021-06-27 10:32 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +`multibuild <https://github.com/matthew-brett/multibuild>`__.
I think the pattern has been to link to the [project summaries](https://github.com/pypa/packaging.python.org/blob/main/source/key_projects.rst):

```suggestion
:ref:`cibuildwheel` and :ref:`multibuild`.
```

2021-06-27 10:32 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +Building extensions in CI
Readers might not know what CI is, and I think focusing on the desired outcome is clearer:

```suggestion
Building extensions for multiple platforms
```

2021-06-27 10:32 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +module per Python version times the number of OS and archetectures you support.
I _think_ this is more accurate, based on my understanding:

```suggestion
If you plan to distribute your extension, you should provide :term:`wheels <Wheel>` for all the
platforms you intend to support. For most extensions, this is at least one
package per Python version times the number of OS and architectures you support.
```

2021-06-28 13:29 UTC, henryiii commented
Thanks, @bhrutledge!

2021-06-28 15:02 UTC, henryiii commented
There's no multibuild project summary, so this PR is failing after the change. I think the best fix would be to add a multibuild section under non PyPA project, rather than to revert to a link. Will make a PR for that that this PR will then depend on.

2021-06-29 19:37 UTC, pradyunsg approved these changes
LGTM, although this whole guide likely needs to be updated and completed. :)

2021-06-29 19:38 UTC, pradyunsg commented on source/guides/packaging-binary-extensions.rst
> +-------------------------
This underline needs to be fixed tho. :)

2021-06-29 19:38 UTC, henryiii commented on source/guides/packaging-binary-extensions.rst
> +-------------------------
Too late. ;)

2021-06-29 19:39 UTC, pradyunsg commented on source/guides/packaging-binary-extensions.rst
> +<Wheel>` for all the platforms you intend to support. For most extensions, this
I don't think splitting a directive across multiple lines works, but hey, I'd be willing to be surprised. :)

2021-06-29 19:39 UTC, henryiii commented
I'm working on it, in small pieces. I'll tag a few possibly interested parties when I make the next PRs (likely after PyHEP and SciPy, so in a couple of weeks at the earliest)

2021-06-29 19:40 UTC, henryiii commented on source/guides/packaging-binary-extensions.rst
> +<Wheel>` for all the platforms you intend to support. For most extensions, this
Ahh, reflowed that and didn't watch for directives. We can see, I guess. :)

2021-06-29 19:41 UTC, henryiii commented on source/guides/packaging-binary-extensions.rst
> +<Wheel>` for all the platforms you intend to support. For most extensions, this
Nope.

2021-06-29 19:44 UTC, merged