binary-extensions: update Windows instructions
pypa/packaging.python.org pull request #911
Opened 2021-06-01 15:15 UTC by henryiii

About a month ago Microsoft permanently killed off https://www.microsoft.com/en-gb/download/details.aspx?id=8279 (MSVC 2008 for Python 2.7); it was officially at end-of-really-extended-life-for-python-2.7 since 2018. I don't think details about Python 3.4 are all that interesting to anyone anymore, either.

Included the caveat discovered by matplotlib for MSVC 2019.

2021-06-27 10:56 UTC, bhrutledge requested changes
I'm not a Windows user, so these are just suggested copy edits for clarity (plus one for spelling).

2021-06-27 10:56 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +file, ``VCRUNTIME140_1.dll``, in addition to the ``VCRUNTIME140.dll`` all previous
```suggestion
One caveat: if you use Visual Studio 2019 or later, your extension will depend on an "extra"
file, ``VCRUNTIME140_1.dll``, in addition to the ``VCRUNTIME140.dll`` that all previous
```

2021-06-27 10:56 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +can add the compile-time argument ``/d2FH4-`` to avoid this link on 2019+.
```suggestion
your extension on versions of CPython that do not include this extra file. To
avoid this, you can add the compile-time argument ``/d2FH4-``.
```

2021-06-27 10:56 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +and you should exercize care when designing your extension not to malloc/free
```suggestion
and you should exercise care when designing your extension not to malloc/free
```

2021-06-27 10:56 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
>  is used throughout the Python process.
This feel unnecessary, or it could be conveyed introductory paragraph.

```suggestion
```

2021-06-27 10:56 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +available from Microsoft, so building for CPython < 3.5 is discouraged. If you do
I'm not sure the extra detail is necessary here (though maybe a mention of Visual Studio 2015 would still be useful).

```suggestion
Building for Python prior to 3.5 is discouraged, because older versions of
Visual Studio are no longer available from Microsoft. If you do
```

2021-06-27 10:56 UTC, bhrutledge commented on source/guides/packaging-binary-extensions.rst
> +recent version is fine.
This feels like the most important bit. Could it go before the "older versions" paragraph above?

2021-06-28 14:30 UTC, henryiii commented on source/guides/packaging-binary-extensions.rst
> +recent version is fine.
Moved.

2021-06-28 14:31 UTC, henryiii commented on source/guides/packaging-binary-extensions.rst
> +compile-time argument ``/d2FH4-``. Recent versions of Python may include this
I'd like to put exact numbers, but I'm not sure which ones they are (it might have changed in patch releases, too?)

2021-06-29 00:23 UTC, bhrutledge approved these changes
I think this reads much better. Thanks!

2021-07-12 15:46 UTC, webknjaz commented
I'm not a Windows user either so I'd feel much more comfortable merging the change if one could be found and posted a review. If nobody is available for some time, we'll merge this as is.

2021-07-12 15:51 UTC, pfmoore approved these changes
(Windows user here!) This looks good to me, although I only very rarely build C extensions these days, so while the technical details of the content look accurate to me, I'm not an expert.

I'd say this can be merged as is, though - we can always iterate on the technical details if further nuances are reported.

2021-07-12 15:52 UTC, webknjaz commented
Thanks, Paul!

2021-07-12 15:52 UTC, merged

2021-07-12 17:50 UTC, henryiii commented
Thanks for the review! I'll try to work on updating macOS and Linux next (though likely after SciPy).