Fix executable dir in + tabify pip & virtual envs guide
pypa/packaging.python.org pull request #928
Opened 2021-06-27 15:52 UTC by ichard26

Fixes #783.

This patch also completes the "tabification" this document.

2021-06-27 15:54 UTC, ichard26 commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        .../env/Scripts/python.exe
This is where the `bin` to `Script` fix happened, this diff is harder to parse than I'd have hoped :/

2021-06-27 19:29 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        .../env/Scripts/python.exe
It's easier if you [hide whitespace changes](https://github.blog/2018-05-01-ignore-white-space-in-code-review/).

https://github.com/pypa/packaging.python.org/pull/928/files?diff=unified&w=1

2021-06-27 19:45 UTC, bhrutledge reviewed
Thanks for this; I like seeing the adoption of tabs in this doc. I've got a few questions/suggestions.

2021-06-27 19:45 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 9.0.1 from c:\python36\lib\site-packages (Python 3.6.1)
This is a very old version of pip and Python. Can we take the opportunity to show the latest version for Windows and Unix/macOS?

2021-06-27 19:45 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        .../env/Scripts/python.exe
Should this be:

```suggestion
        ...\env\Scripts\python.exe
```

2021-06-27 19:45 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 9.0.1 from c:\python36\lib\site-packages (Python 3.6.1)
Also, this is one of a few places in this document where the command and its output are shown in a single `code-block`, but with no distinction between them, which might lead folks to thinking that `pip 9.0.1 ...` is a command to execute.

If the output is valuable, I recommend putting into a separate `code-block`, maybe something like:

```suggestion
    .. code-block:: text

        pip 9.0.1 from c:\python36\lib\site-packages (Python 3.6.1)
```

Again, we'd want to do the same for Unix/macOS, and similarly for the "You can confirm you're in the virtual environment" instructions. But that could also be a follow-up PR.

2021-06-27 20:49 UTC, ichard26 commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        .../env/Scripts/python.exe
Ah, I forgot about this feature, thank you!

2021-06-27 20:51 UTC, ichard26 commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        .../env/Scripts/python.exe
Ugh, the fact I switched from Windows to Linux since 6 months really shows. My bad.

2021-06-27 20:52 UTC, ichard26 commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 9.0.1 from c:\python36\lib\site-packages (Python 3.6.1)
I was avoiding any informational changes to the document since I was afraid I lack the domain knowledge to do them properly, but this seems reasonable and I like it! I think it's fine to include these changes (at on a first glance) since this PR already makes significant visual changes.

2021-06-27 21:17 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 9.0.1 from c:\python36\lib\site-packages (Python 3.6.1)
Actually, I think the fact this PR makes significant visual changes is reason enough to do this in a subsequent PR. Let's just update the slashes for now.

2021-06-28 10:37 UTC, bhrutledge approved these changes
Thanks!

2021-06-28 10:45 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 9.0.1 from c:\python36\lib\site-packages (Python 3.6.1)
I've created https://github.com/pypa/packaging.python.org/issues/931 as a follow-up.

2021-06-28 15:25 UTC, henryiii commented
There there a way to avoid the syntax highlighting doing this with the backslashes?

<img width="296" alt="Screen Shot 2021-06-28 at 11 24 44 AM" src="https://user-images.githubusercontent.com/4616906/123662479-84d53980-d803-11eb-9b5f-f36bf359674f.png">

2021-06-28 15:34 UTC, henryiii commented
I think you can use the `.. code-block:: bat` lexer. This problem happens on other pages, too, not something to fix right now, but good idea for later.

2021-06-29 00:29 UTC, bhrutledge requested changes
One more small tweak, based on @henryiii's observation.

2021-06-29 00:29 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +    .. code-block:: bash
Looking at the other Windows output in this doc (e.g. line 143), I think this should address https://github.com/pypa/packaging.python.org/pull/928#issuecomment-869780161:

```suggestion
    .. code-block:: text
```

2021-07-01 23:36 UTC, ichard26 commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +    .. code-block:: bash
Committed, thanks!

2021-07-02 00:05 UTC, bhrutledge approved these changes

2021-07-03 11:37 UTC, pradyunsg approved these changes

2021-07-03 11:37 UTC, merged

2021-07-04 21:45 UTC, ichard26 commented
Thanks @henryiii, @pradyunsg and @bhrutledge for the reviews, it's well appreciated! :slightly_smiling_face:

2021-07-05 13:21 UTC, bhrutledge commented
@ichard26 Thank for the improvements! If you feel like doing more, https://github.com/pypa/packaging.python.org/issues/931 would be a good follow-up.