Add Translatable Files
pypa/packaging.python.org pull request #930
Opened 2021-06-28 03:26 UTC by meowmeowmeowcat

Fixes #927

2021-06-28 07:02 UTC, webknjaz commented on .gitignore
> +source/_build/
This is unnecessary — our `nox` setup uses `build/` dir. We shouldn't ignore every possible dir name contributors may use — the only supported sphinx invocation is via `nox`. And any helper commands should be added there too (to `noxfile.py`).

2021-06-28 07:02 UTC, webknjaz commented on source/conf.py
> +gettext_compact = "messages"
Could you explain what this does?

2021-06-28 07:04 UTC, webknjaz reviewed
I'm pretty sure we only need a `pot` file with the translation. Weblate will generate the target po files by itself. Let's not publish content with no translation at all. This is the process Warehouse follows too.

2021-06-28 07:05 UTC, meowmeowmeowcat commented on .gitignore
> +source/_build/
OK

I will remove them

2021-06-28 07:10 UTC, meowmeowmeowcat commented on source/conf.py
> +gettext_compact = "messages"
At first, if we run a command like this : `sphinx-intl update -p _build/gettext -l es_AR`, it will generate a few of `.po` files.

However, when we use `gettext_compact = "messages"` here, it will generate a new file called `messages.po` only.

2021-06-28 07:12 UTC, meowmeowmeowcat commented on source/conf.py
> +gettext_compact = "messages"
> I'm pretty sure we only need a `pot` file with the translation. Weblate will generate the target po files by itself. Let's not publish content with no translation at all. This is the process Warehouse follows too.

Okay. So now I have to remove `locales` right?

2021-06-28 07:25 UTC, meowmeowmeowcat commented
Okay. So now I have to remove locales right?

2021-06-28 10:42 UTC, meowmeowmeowcat commented
I have removed `locales` folder.

2021-06-28 10:50 UTC, meowmeowmeowcat commented on .gitignore
> +.DS_Store
I added .DS_Store here because I think these files are useless.

2021-06-28 11:23 UTC, webknjaz commented on .gitignore
> +.DS_Store
Sure, this one is okay.

2021-06-28 11:24 UTC, webknjaz requested changes
Please don't commit `source/_build/` folder.

2021-06-28 11:24 UTC, meowmeowmeowcat commented on .gitignore
> +.DS_Store
And also do we need `.doctree` actually?

2021-06-28 11:25 UTC, webknjaz commented on source/conf.py
> +gettext_compact = "messages"
Sounds like we need to embed invoking `sphinx-intl` into `noxfile.py`.

2021-06-28 11:26 UTC, webknjaz commented
> I have removed `locales` folder.

The `pot` file is still necessary, I think.

2021-06-28 11:26 UTC, meowmeowmeowcat commented
Yes, and it is located in `source/_build/` folder

2021-06-28 11:27 UTC, webknjaz commented on .gitignore
> +.DS_Store
No, we don't. The reason it appeared in your repo is that you used a different build directory that is not gitignored. Use the correct directory called `build/` and things under it will be ignored.

2021-06-28 11:27 UTC, meowmeowmeowcat commented
So maybe I should put `messages.pot` in  a new folder?

2021-06-28 11:28 UTC, webknjaz commented
> So maybe I should put `messages.pot` in a new folder?

I think it should probably be in `locales/`.

2021-06-28 11:30 UTC, webknjaz commented
Are you familiar with https://nox.thea.codes? I suggest you start by adding a new command there that invokes i18n-related executables. Use the same directories as in other commands, and hopefully, the rest will fall into place.

2021-06-28 11:34 UTC, meowmeowmeowcat commented
> Are you familiar with https://nox.thea.codes? I suggest you start by adding a new command there that invokes i18n-related executables. Use the same directories as in other commands, and hopefully, the rest will fall into place.

I am not really familiar with it, but I will try and see if I can make it.

2021-06-28 12:26 UTC, meowmeowmeowcat reviewed
Therefore, people will be required to run these (build the new `.pot`)after they have changed the docs

2021-06-28 12:26 UTC, meowmeowmeowcat commented on noxfile.py
> +    session.run("make","gettext")
Is something like these?

2021-06-29 07:04 UTC, webknjaz commented on noxfile.py
> +    session.run("make","gettext")
Let's not use `make` but invoke the commands directly instead.

2021-06-29 07:05 UTC, webknjaz commented on noxfile.py
> +    session.run("cd","source")
I don't think we should `cd` into `source/` — just follow what other commands do. I'm pretty sure you could pass dirs as CLI args.

2021-06-29 07:05 UTC, meowmeowmeowcat commented on noxfile.py
> +    session.run("make","gettext")
Okay

2021-06-29 07:06 UTC, webknjaz commented on Makefile
> +# Minimal makefile for Sphinx documentation
Let's not add additional to nox command runner — we don't need make.

2021-06-29 07:06 UTC, webknjaz commented on .gitignore
> +source/locales/template/gettext/.doctrees/
I'd move `locales` outside of `source/` maybe + could we put doctrees into the top-level `build/`?

2021-06-29 07:08 UTC, meowmeowmeowcat commented on Makefile
> +# Minimal makefile for Sphinx documentation
Okay. I will remove it.

2021-06-29 07:09 UTC, meowmeowmeowcat commented on .gitignore
> +source/locales/template/gettext/.doctrees/
But do I have to to commit `.doctree`?

2021-06-29 07:10 UTC, meowmeowmeowcat commented on noxfile.py
> +    session.run("cd","source")
OK

2021-06-29 07:42 UTC, meowmeowmeowcat commented
I also have a question

2021-06-29 09:44 UTC, webknjaz commented
> How many `.pot` files I have to generate? Join all `.pot` files in one or just let them separate out?

I'm not sure, I was about to ask you the same :) Originally, I was thinking about one but OTOH maybe having a per-article file could be useful. Is Weblate able to handle multiple files as a single project?

2021-06-29 09:45 UTC, webknjaz commented
I think, if we'll be able to make the workflow Weblate-centric, we would care less about the local commands as most folks would just use that.

2021-06-29 10:01 UTC, meowmeowmeowcat commented
> > How many `.pot` files I have to generate? Join all `.pot` files in one or just let them separate out?
> 
> I'm not sure, I was about to ask you the same :) Originally, I was thinking about one but OTOH maybe having a per-article file could be useful. Is Weblate able to handle multiple files as a single project?

I think Weblate is able to handle multiple files by [add-on](https://docs.weblate.org/en/latest/admin/addons.html#addon-weblate-discovery-discovery).

2021-06-29 10:42 UTC, meowmeowmeowcat commented
> > How many `.pot` files I have to generate? Join all `.pot` files in one or just let them separate out?
> 
> I'm not sure, I was about to ask you the same :) Originally, I was thinking about one but OTOH maybe having a per-article file could be useful. Is Weblate able to handle multiple files as a single project?

I noticed that Warehouse has a file called `messages.pot` only, which contains all contents they have to translate in a file.

2021-06-29 10:56 UTC, meowmeowmeowcat commented
So I think we should run this command in local: `xgettext locales/*.pot locales/discussions/*.pot locales/guides/*.pot locales/specifications/*.pot locales/tutorials/*.pot -o messages.pot` to generate one `.pot` file. ( It will be contained in the `noxfile.py` later)

2021-06-29 11:00 UTC, meowmeowmeowcat commented
> So I think we should run this command in local: `xgettext locales/*.pot locales/discussions/*.pot locales/guides/*.pot locales/specifications/*.pot locales/tutorials/*.pot -o messages.pot` to generate one `.pot` file. ( It will be contained in the `noxfile.py` later)

But I think this command is quite long.

2021-06-29 12:25 UTC, meowmeowmeowcat commented on source/conf.py
> +gettext_compact = "messages"
> Sounds like we need to embed invoking `sphinx-intl` into `noxfile.py`.

Added.

2021-06-29 12:33 UTC, meowmeowmeowcat commented
And I've changed Sphinx version to `3.3.0` in `requirements.txt`

2021-06-29 12:50 UTC, meowmeowmeowcat commented
According to this [pull request](https://github.com/meowmeowmeowcat/packaging.python.org/pull/1), I think we can move to next step

2021-06-29 12:53 UTC, meowmeowmeowcat commented
Now we can go on to the next step.

2021-07-01 08:20 UTC, meowmeowmeowcat commented
I think this pull request can be merged now.

2021-07-03 13:32 UTC, closed without merging