Change to `code-block :: text` from `code-block:: bash` & update the version of pip
pypa/packaging.python.org pull request #937
Opened 2021-07-09 07:23 UTC by meowmeowmeowcat

- Fixes #934 and #931

2021-07-09 07:25 UTC, pradyunsg commented
Hmm... This PR make me think that we should not checkin the `.pot` file, and instead generate that in a GitHub action instead.

2021-07-09 07:37 UTC, meowmeowmeowcat commented
> Hmm... This PR make me think that we should not checkin the `.pot` file, and instead generate that in a GitHub action instead.

I will open another PR for this.

2021-07-09 08:49 UTC, ed738 approved these changes

2021-07-09 14:45 UTC, webknjaz commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
How about
```suggestion
        .. code-block:: console

            > py -m pip install twine
```

2021-07-09 15:37 UTC, bhrutledge commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
@webknjaz Are you suggesting that for just this instance, or as a pattern to follow for all commands?

Assuming it's the latter, do you know how that renders Windows commands that contain `\`?

2021-07-09 15:38 UTC, bhrutledge commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
Also, including a prompt character in the command would be a stylistic change from the Linux/macOS commands. As it is, readers can copy and paste the whole code block.

2021-07-09 18:58 UTC, webknjaz commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
Yeah, I know. It's just a separate lexer that highlights lines with the prompt in a different color than the ones w/o it assuming that's the command output.
It'd need to be a global change. I don't think it really parses the command contents though.
The important thing is that it doesn't attempt to highlight things with `$` as vars in shell scripts or detect keywords like `for` or `if`.

2021-07-09 19:00 UTC, webknjaz commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
I know that snippets on docs.python.org have a button that removes all the prompt chars for copying. That requires some sphinx ext.

2021-07-10 01:46 UTC, bhrutledge requested changes
Thanks for the comprehensive update! Beyond the question of `text` vs other lexers, just a couple some small tweaks to `installing-using-pip-and-virtual-environments.rst` for consistency.

2021-07-10 01:46 UTC, bhrutledge commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
Looks like `console` is specifically for Bash sessions: https://pygments.org/docs/lexers/#pygments.lexers.shell.BashSessionLexer

Besides plain `text`, it looks like the Windows options are `bat` (suggested by @henryiii) and maybe `powershell`:

https://pygments.org/docs/lexers/#pygments.lexers.shell.BatchLexer
https://pygments.org/docs/lexers/#pygments.lexers.shell.PowerShellLexer

I'm honestly not sure which is best. @meowmeowmeowcat if you want to try one of those to see how it changes the rendering, go for it, but I'm guessing `text` is sufficient.

2021-07-10 01:46 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
This isn't a `bash` command, but rather its output, so I think it should be `text`:

```suggestion
    .. code-block:: text

        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
```

2021-07-10 01:46 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
Also, I think these blocks under "Activating Virtual Environments" should similarly separate the command from its output:

```rst
.. tab:: Unix/macOS

    .. code-block:: bash

        which python
        .../env/bin/python

.. tab:: Windows

    .. code-block:: text

        where python
        ...\env\Scripts\python.exe
```

2021-07-10 02:36 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
> I know that snippets on docs.python.org have a button that removes all the prompt chars for copying. That requires some sphinx ext.

@webknjaz Do you think that we should add this sphinx ext to our docs?

2021-07-10 02:37 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
> Looks like `console` is specifically for Bash sessions: https://pygments.org/docs/lexers/#pygments.lexers.shell.BashSessionLexer
> 
> Besides plain `text`, it looks like the Windows options are `bat` (suggested by @henryiii) and maybe `powershell`:
> 
> https://pygments.org/docs/lexers/#pygments.lexers.shell.BatchLexer
> https://pygments.org/docs/lexers/#pygments.lexers.shell.PowerShellLexer
> 
> I'm honestly not sure which is best. @meowmeowmeowcat if you want to try one of those to see how it changes the rendering, go for it, but I'm guessing `text` is sufficient.

Thanks @bhrutledge! I will try them out.

2021-07-10 02:45 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
After testing `bat` ,`powershell` and `text`, I think there is no difference between them. So probably we should keep using `text`.

2021-07-10 03:01 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
> I know that snippets on docs.python.org have a button that removes all the prompt chars for copying. That requires some sphinx ext.

@webknjaz I think that button is for removing `>>>` in the interactive mode only.

2021-07-10 03:04 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
Maybe we should follow the docs of [pip](https://pip.pypa.io/en/stable/quickstart/)?

They use something like this for UNIX/macOS:

```
$ python -m pip install SomePackage
[...]
Successfully installed SomePackage
```

And this for Windows:
```
C:\> py -m pip install SomePackage
[...]
Successfully installed SomePackage
```

2021-07-10 04:08 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
I have an idea here.

We could use `Sphinx-copybutton` for folks to copy the command.
However, it won't copy `$` or `C:\>`.

Example:

Command:
```
$ python3 -m pip install --user --upgrade pip
```
After they copied, this command will be paste in their terminal:
```
python3 -m pip install --user --upgrade pip
```

2021-07-10 13:48 UTC, bhrutledge approved these changes
Thanks for the changes. I pushed a couple more tweaks to the `installing-using-pip` doc.

Since this would be my first merge as a maintainer, I'll leave this open for another day to allow for more comments.

2021-07-10 13:48 UTC, bhrutledge commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
Thanks for the ideas. While I like the idea of following the conventions in other docs, I'm not sure pip is doing the right thing here. Looking at the [source for the quickstart doc](https://github.com/pypa/pip/blob/21.1.3/docs/html/quickstart.rst), it's using `console` for all tabs. Also, their copy button copies the prompt, command, and output. I think it's also worth noting that pip is in the process of migrating all of their docs to Markdown (https://github.com/pypa/pip/issues/9475), so trying to follow their patterns could be challenging.

2021-07-10 13:48 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
>          ...\env\Scripts\python.exe
I thought having more distinction between the command and its output would read better.

2021-07-10 13:48 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
In retrospect, the changes to this section probably should be in a separate PR, but I took the opportunity to (hopefully) add some additional clarity.

2021-07-11 05:53 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
Therefore, our copy button won't copies the prompt but only command. We have also separated the output out so it won't copy the output too. Adding the prompt will make folks know that it is a command easily.

2021-07-11 13:39 UTC, meowmeowmeowcat commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
So now we should just keep the same as I found that they will add the prompt when the code block includes some other text only.

2021-07-11 18:17 UTC, webknjaz commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
I'm pretty sure it's console rather than text.

2021-07-11 19:06 UTC, henryiii commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
"Text" removes all semantic meaning from the highlighting, promising you will never do better than text, and making it indistinguishable from a text output. I'd think `bat` or `powershell` would be better, as that's actually the language this is in, even if there's no current visual difference. `console` is supposed to be somewhat agnostic, even if bash-like - was it rendering incorrectly? Also, if they are struggling with output vs. input, what about:

```rst
    .. code-block:: bat

        where python

    .. code-block:: text

        ...\env\Scripts\python.exe
```

? Does that break it up too much? I used to have a "input" and "output" type (gitbook plugin, IIRC) that would handle this nicely. As long as we are consistent, it's easy to refactor in the future - going to "text" makes it harder, because there may really be some "text" blocks that are not Windows shell inputs.

2021-07-11 19:35 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
Those are good points re: semantics and refactoring, @henryiii. Since I was the one who originally suggested `text`, I just pushed the change to `bat` for Windows inputs (4e01f46), plus a couple remaining `bash` for Unix inputs (ee40d83).

I don't think `console` is correct for outputs, because [according to the docs](https://pygments.org/docs/lexers/#pygments.lexers.shell.BashSessionLexer), it's a "lexer for Bash shell sessions, i.e. command lines, including a prompt, interspersed with output". `text` is widely-used throughout this project for outputs.

2021-07-11 22:49 UTC, meowmeowmeowcat commented
Thanks for @henryiii's suggestion and @bhrutledge's commits!

2021-07-12 06:30 UTC, meowmeowmeowcat commented
@bhrutledge Do you think we should add copy button for folks so they can copy the command directly? It's very easy to do this( just add a sphinx extension).

2021-07-12 08:33 UTC, webknjaz commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
For win console, it's probably just
```suggestion
        .. code-block:: doscon

            > py -m pip install twine
```

2021-07-12 08:33 UTC, webknjaz commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
Or maybe 
```suggestion
        .. code-block:: ps1con

            $ py -m pip install twine
```

2021-07-12 08:34 UTC, webknjaz commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
cc @bhrutledge have you seen these?

2021-07-12 08:35 UTC, webknjaz commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
Yep, also, the console session should be coupled with the output after the prompt input.

2021-07-12 09:40 UTC, bhrutledge approved these changes
Thanks for the additional comments. I'm going to merge this as-is, because I think it's a nice improvement. Folks can follow up with additional issues/PRs if they like.

> Do you think we should add copy button for folks so they can copy the command directly?

@meowmeowmeowcat That sounds handy. I'd probably start with a PR that just adds the button, but _not_  the prompt characters and the configuration to remove it.

2021-07-12 09:40 UTC, bhrutledge commented on source/guides/distributing-packages-using-setuptools.rst
>              py -m pip install twine
D'oh. I missed those. I agree those seem appropriate, _if_ there's a parallel change of all of the `bash` inputs, i.e.:

```
.. code-block:: console

    $ twine upload dist/*
```

I think that's beyond the scope of this PR. Also, as noted in an earlier discussion, I'm not sure it's a better experience, because it adds a little more work to copying a command.

2021-07-12 09:40 UTC, bhrutledge commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
> coupled with the output after the prompt input

If you mean there shouldn't be any explanatory text between the input and the output `code-block`, I disagree. That's how it was in earlier commits, and I thought it was a bit confusing. Also, there are already places in this doc (and I assume others) where they are separated, e.g.:

https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#installing-packages

2021-07-12 09:42 UTC, merged

2021-07-12 09:48 UTC, webknjaz commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
@bhrutledge I think I've seen `console` perform well with windows-based prompts. My understanding that it only highlights the lines starting with some sort of a prompt differently from those that don't.
But yes, looking at https://github.com/pygments/pygments/blob/1ea5fc3/pygments/lexers/shell.py#L226 and https://github.com/pygments/pygments/blob/1ea5fc3/pygments/lexers/shell.py#L556, it seems like `doscon` is a windows counterpart of the `console` lexer.

@henryiii I do think that having clear input (with prompt) + output coupled would be beneficial

2021-07-12 09:50 UTC, webknjaz commented on source/guides/installing-using-pip-and-virtual-environments.rst
> +        pip 21.1.3 from $HOME/.local/lib/python3.9/site-packages (python 3.9)
It's confusing when the input line isn't marked with a prompt. If it is, that should be rendered better.

2021-07-12 09:51 UTC, webknjaz commented
re:copybutton — it'd be nice to integrate https://github.com/executablebooks/sphinx-copybutton + https://github.com/python/python-docs-theme/blob/master/python_docs_theme/static/copybutton.js

2021-07-12 09:53 UTC, meowmeowmeowcat commented
> re:copybutton — it'd be nice to integrate https://github.com/executablebooks/sphinx-copybutton + https://github.com/python/python-docs-theme/blob/master/python_docs_theme/static/copybutton.js

Thanks for this!

2021-07-12 10:58 UTC, meowmeowmeowcat commented
> https://github.com/python/python-docs-theme/blob/master/python_docs_theme/static/copybutton.js

@webknjaz Is this necessary for the docs? I think most of the code blocks in the docs are shell commands.

2021-07-12 11:43 UTC, webknjaz commented
Dunno, I think it'd be nice to have the ability to easily copy those commands w/o the prompt.

2021-07-12 12:01 UTC, meowmeowmeowcat commented
I agree. I will test sphinx-copybutton and see if it can integrate the function of the copybutton in python docs .