Add backquotes for commands
pypa/packaging.python.org pull request #973
Opened 2021-09-02 09:24 UTC by meowmeowmeowcat

Found this issue when fixing broken links.

2021-09-02 13:22 UTC, bhrutledge requested changes

2021-09-02 13:22 UTC, bhrutledge commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
This is rendering strangely: https://python-packaging-user-guide--973.org.readthedocs.build/specifications/direct-url/#example-pip-commands-and-their-effect-on-direct-url-json. I wonder if it's the parenthetical clause. Maybe that could a nested list item instead? Or maybe it's not necessary at all?

2021-09-02 13:22 UTC, bhrutledge commented on source/specifications/direct-url.rst
> +* ``pip install -e ./app``
For consistency with the previous command:

```suggestion
* ``pip install --editable ./app``
```

2021-09-02 13:26 UTC, meowmeowmeowcat commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
https://packaging.python.org/guides/installing-using-linux-tools/#centos-rhel has the same problem, but I don't have a solution for it.

2021-09-02 13:27 UTC, meowmeowmeowcat commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
I prefer using a nested list item instead.

2021-09-02 13:35 UTC, meowmeowmeowcat commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
![Image](https://user-images.githubusercontent.com/68463158/131853090-8122e73c-ebc6-48e9-8a6a-becb4e2ec23b.png)

It doesn't work too.

2021-09-02 13:40 UTC, meowmeowmeowcat commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
I guess the reason is that the command `pip install --editable "git+https://example.com/repo/app.git#egg=app&subdirectory=setup"` is too long.

2021-09-02 17:38 UTC, webknjaz commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
Are you talking about the justified text alignment? If yes, it's probably something to fix on the CSS level in the theme rather than in this PR.

2021-09-02 17:41 UTC, webknjaz commented on source/specifications/direct-url.rst
> +* ``pip install --editable ./app``
This change is not related to the PR description/title/goal. Please avoid making such changes to make sure that the review and merge happen quickly.

If it wasn't here, I would've merged this already. But now I have to wait until you either revert this or justify why it is important to have the option format change *in this specific PR*.

2021-09-02 17:44 UTC, webknjaz commented on source/specifications/direct-url.rst
> +* ``pip install -e ./app``
Not this is inconsistent with the main goal of the PR. Such a change should happen in a separate PR.

2021-09-02 17:46 UTC, webknjaz commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
FTR this is coming from
```css
_static/classic.css:197
div.body p, div.body dd, div.body li, div.body blockquote {
    text-align: justify;
    line-height: 130%;
}
```
This is probably coming from one of the underlying themes in Sphinx. But again, this is not something we can fix in this PR.

2021-09-02 18:00 UTC, webknjaz commented on source/specifications/direct-url.rst
>    ``vcs_info`` will be set)
P.S. If #791 ever gets merged (or replaced but a better theme), the problem should go away.

2021-09-03 11:02 UTC, webknjaz approved these changes

2021-09-03 11:02 UTC, merged